Update to 0.3.11 to support more recent apps that use it.
Also take MAINTAINER.

ok nino@

diff --git a/textproc/scrollkeeper/pkg/INSTALL b/textproc/scrollkeeper/pkg/INSTALL
--- a/textproc/scrollkeeper/pkg/INSTALL
+++ b/textproc/scrollkeeper/pkg/INSTALL
@@ -1,28 +1,98 @@
 #!/bin/sh
 #
-# $OpenBSD: INSTALL,v 1.1.1.1 2001/09/13 20:40:56 todd Exp $
-#
+# $OpenBSD: INSTALL,v 1.2 2002/11/30 04:41:29 marcm Exp $
+
+P_NAME=scrollkeeper
+
+DIRS='
+'
+
+FILES='
+scrollkeeper.conf
+'
+
+set -e
+PREFIX=${PKG_PREFIX:-/usr/local}
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+
+do_post() {
+
+	DEST_PFX=${SYSCONFDIR}
+	SOURCE_PFX=${PREFIX}/share/examples/${P_NAME}
+
+	echo 
+	echo "+--------------- ${P_NAME}"
+
+	# install dirs if neccessary
+	for d in ${DIRS}; do
+		if [ ! -d "${DEST_PFX}/$d" ]; then
+			install -d ${DEST_PFX}/$d
+		fi
+	done
+	install -d /var/db/scrollkeeper
+
+	# install or take note of existing config files
+	for f in ${FILES}; do
+		if [ -f "${DEST_PFX}/$f" ]; then
+			OLD_CONFS="${OLD_CONFS} $f"
+		else
+			if ! install -m 644 ${SOURCE_PFX}/$f ${DEST_PFX}/$f; then
+				echo "| ERROR: The following file could not be installed, exiting: ${DEST_PFX}/$f"
+				exit 1
+			fi
+			NEW_CONFS="${NEW_CONFS} $f"
+		fi
+	done
+
+	# print status report
+	if [ -n "${NEW_CONFS}" ]; then
+		echo "| The following NEW configuration files have been installed:"
+		echo "|"
+		for f in ${NEW_CONFS}; do
+			echo "| ${DEST_PFX}/$f"
+		done 
+	fi
+	
+	if [ -n "${OLD_CONFS}" ]; then
+		if [ -n "${NEW_CONFS}" ]; then
+			echo "|"
+		fi
+		echo "| The following OLD configuration files were found and have NOT been"
+		echo "| overwritten:"
+		echo "|"
+		for f in ${OLD_CONFS}; do
+			echo "| ${DEST_PFX}/$f"
+		done
+		echo "|"
+		echo "| You should however manually compare them to their equivalents in"
+		echo "|"
+		echo "| ${SOURCE_PFX}"
+		echo "|"
+		echo "| and update your configuration as needed." 
+	fi
+	echo "+--------------- ${P_NAME}"
+	echo 
+}
 
 # verify proper execution
 #
 if [ $# -ne 2 ]; then
-    echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
-    exit 1
+	echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
+	exit 1
 fi
 
 # Verify/process the command
 #
 case $2 in
-    PRE-INSTALL)
-        ;;
-    POST-INSTALL)
-	# localstatedir
-        install -d /var/lib/scrollkeeper
-        ;;
-    *)
-        echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
-        exit 1
-        ;;
+	PRE-INSTALL)
+		;;
+	POST-INSTALL)
+		do_post
+		;;
+	*)
+		echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
+		exit 1
+		;;
 esac
 
 exit 0
