equate powerpc with ppc and amd64 with x86_64 for alignment checks based on diffs to the scummvm port from Donovan Watteau

diff --git a/games/scummvm-tools/patches/patch-configure b/games/scummvm-tools/patches/patch-configure
--- a/games/scummvm-tools/patches/patch-configure
+++ b/games/scummvm-tools/patches/patch-configure
@@ -1,7 +1,7 @@
-$OpenBSD: patch-configure,v 1.1 2011/05/29 14:05:15 jsg Exp $
---- configure.orig	Sun May 29 14:18:48 2011
-+++ configure	Sun May 29 14:20:00 2011
-@@ -338,6 +338,9 @@ EOF
+$OpenBSD: patch-configure,v 1.2 2014/11/29 10:22:37 jsg Exp $
+--- configure.orig	Sat Jul 12 07:36:17 2014
++++ configure	Sat Nov 29 20:08:34 2014
+@@ -381,6 +381,9 @@ EOF
  	fi
  done # for parm in ...
  
@@ -11,3 +11,12 @@ $OpenBSD: patch-configure,v 1.1 2011/05/29 14:05:15 jsg Exp $
  for ac_option in $@; do
  	case "$ac_option" in
  	--enable-vorbis)          _vorbis=yes     ;;
+@@ -1020,7 +1023,7 @@ test $TMPR -eq 0 || exit 1	# check exit code of subshe
+ # for the smaller sizes.
+ echo_n "Alignment required... "
+ case $_host_cpu in
+-	i[3-6]86 | x86_64 | ppc*)
++	i[3-6]86 | amd64 | x86_64 | powerpc* | ppc*)
+ 		# Unaligned access should work
+ 		_need_memalign=no
+ 		;;
