update to scummvm-tools 2.6.0

diff --git a/games/scummvm-tools/patches/patch-configure b/games/scummvm-tools/patches/patch-configure
--- a/games/scummvm-tools/patches/patch-configure
+++ b/games/scummvm-tools/patches/patch-configure
@@ -1,6 +1,7 @@
---- configure.orig	Wed Oct 12 07:08:18 2016
-+++ configure	Tue Nov  1 21:31:29 2016
-@@ -386,6 +386,9 @@ EOF
+Index: configure
+--- configure.orig
++++ configure
+@@ -427,6 +427,9 @@ EOF
  	fi
  done # for parm in ...
  
@@ -9,8 +10,8 @@
 +
  for ac_option in $@; do
  	case "$ac_option" in
- 	--enable-vorbis)          _vorbis=yes     ;;
-@@ -1068,7 +1071,7 @@ test $TMPR -eq 0 || exit 1	# check exit code of subshe
+ 	# Silently ignore options valid for Autotools configure.
+@@ -1152,7 +1155,7 @@ test $TMPR -eq 0 || exit 1	# check exit code of subshe
  # for the smaller sizes.
  echo_n "Alignment required... "
  case $_host_cpu in
