touch up packing lists

diff --git a/x11/gtk+/Makefile b/x11/gtk+/Makefile
--- a/x11/gtk+/Makefile
+++ b/x11/gtk+/Makefile
@@ -1,4 +1,4 @@
-# $OpenBSD: Makefile,v 1.14 1999/03/21 05:14:23 brad Exp $
+# $OpenBSD: Makefile,v 1.15 1999/03/26 04:50:45 marc Exp $
 
 DISTNAME=		gtk+-1.2.0
 CATEGORIES=     	x11
@@ -13,7 +13,7 @@ MASTER_SITES=	ftp://ftp.gimp.org/pub/gtk/v1.2/ \
 
 BUILD_DEPENDS=	gettext:${PORTSDIR}/devel/gettext
 RUN_DEPENDS=	gettext:${PORTSDIR}/devel/gettext
-LIB_DEPENDS=    glib\\.1\\.2:${PORTSDIR}/devel/glib
+LIB_DEPENDS=    glib.1.2:${PORTSDIR}/devel/glib
 
 USE_X11=		yes
 USE_PERL5=		yes
@@ -25,7 +25,25 @@ CONFIGURE_ARGS+=	--enable-static --sysconfdir=${SYSCONFDIR}
 CONFIGURE_ENV=		CPPFLAGS="-I${LOCALBASE}/include" \
 			LIBS="-L${LOCALBASE}/lib"
 
-MAN1=	gtk-config.1
+# People that installed an older version of gtk+ wound up with
+# libglib.a and other things in /usr/X11R6/lib... these files
+# MUST be removed as the version was incorrect (it came from 1.0.6
+# sources). Check that out here (and bitch if necessary).
+# 
+pre-extract:
+	@if [ -f ${X11BASE}/lib/libglib.a ]; then \
+	   echo "+-------------------"; \
+	   echo "| ERROR: you MUST remove the existing gtk+ installation"; \
+	   echo "| before installing this version.  Run these commands"; \
+	   echo "| as user root to remove the package:"; \
+	   echo "|"; \
+	   echo "|	pkg_delete -f `pkg_info -e 'gtk+-*'`"; \
+	   echo "|	ldconfig ${X11BASE}/lib"; \
+	   echo "|	ldconfig -m ${LOCALBASE}/lib"; \
+	   echo "|"; \
+	   echo "+-------------------"; \
+	   exit 1; \
+	fi
 
 post-extract:
 	@${RM} ${WRKSRC}/docs/*.info
