- update to sqlite-3.5.9 - merge espie's patches - fix apps such as p5-DBD-SQLite, by adding weak pthread functions. also include some bug fixes from kurt@.  the work has been done by kurt@, and espie@.  thanks! ok kurt@, espie@, bernd@

diff --git a/databases/sqlite3/patches/patch-configure b/databases/sqlite3/patches/patch-configure
--- a/databases/sqlite3/patches/patch-configure
+++ b/databases/sqlite3/patches/patch-configure
@@ -1,7 +1,16 @@
-$OpenBSD: patch-configure,v 1.2 2007/04/14 19:34:03 steven Exp $
---- configure.orig	Thu Mar 29 20:39:30 2007
-+++ configure	Sat Apr  7 08:04:17 2007
-@@ -19338,7 +19338,7 @@ echo "${ECHO_T}file not found" >&6; }
+$OpenBSD: patch-configure,v 1.3 2008/07/23 17:31:17 martynas Exp $
+--- configure.orig	Mon May 12 20:57:21 2008
++++ configure	Mon Jul 21 11:26:29 2008
+@@ -11088,7 +11088,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  ac_cv_search_pthread_create="-l$ac_lib"
++  ac_cv_search_pthread_create="-$ac_lib"
+ break
+ else
+   echo "$as_me: failed program was:" >&5
+@@ -11433,7 +11433,7 @@ echo "${ECHO_T}file not found" >&6
  
      eval "TCL_STUB_LIB_FILE=\"${TCL_STUB_LIB_FILE}\""
      eval "TCL_STUB_LIB_FLAG=\"${TCL_STUB_LIB_FLAG}\""
