update to ImageMagick-6.2.0-8; Bernd Ahlers <b.ahlers@ba-net.org>

diff --git a/graphics/ImageMagick/Makefile b/graphics/ImageMagick/Makefile
--- a/graphics/ImageMagick/Makefile
+++ b/graphics/ImageMagick/Makefile
@@ -1,15 +1,16 @@
-# $OpenBSD: Makefile,v 1.78 2005/01/09 11:06:38 alek Exp $
+# $OpenBSD: Makefile,v 1.79 2005/03/31 04:23:42 pvalchev Exp $
 
 COMMENT=	"image processing tools"
 
-VER=		6.0.0
-DASHVER=	2
+VER=		6.2.0
+DASHVER=	8
 DISTNAME=	ImageMagick-${VER}-${DASHVER}
-PKGNAME=	${DISTNAME}p3
 CATEGORIES=	graphics
-MASTER_SITES=	${MASTER_SITE_SOURCEFORGE:=imagemagick/}
 
-HOMEPAGE=	http://www.simplesystems.org/ImageMagick/
+HOMEPAGE=	http://www.imagemagick.org
+
+MASTER_SITES=	${HOMEPAGE}/download/ \
+		${MASTER_SITE_SOURCEFORGE:=imagemagick/}
 
 LIB_DEPENDS+=	bz2.10::archivers/bzip2 \
 		jbig.1.2::graphics/jbigkit \
@@ -17,13 +18,15 @@ LIB_DEPENDS+=	bz2.10::archivers/bzip2 \
 		tiff.35::graphics/tiff \
 		xml2.6::textproc/libxml \
 		lcms::graphics/lcms \
-		jasper::graphics/jasper
+		jasper::graphics/jasper \
+		ltdl::devel/libtool
+
 RUN_DEPENDS	::graphics/mpeg-lib
 BUILD_DEPENDS=	${RUN_DEPENDS}
 
 MAINTAINER=	Brad Smith <brad@openbsd.org>
 
-# http://www.imagemagick.org/www/Copyright.html 
+# http://www.imagemagick.org/www/Copyright.html
 PERMIT_PACKAGE_CDROM=	Yes
 PERMIT_PACKAGE_FTP=	Yes
 PERMIT_DISTFILES_CDROM=	Yes
@@ -36,16 +39,16 @@ SEPARATE_BUILD=	concurrent
 CONFIGURE_STYLE= autoconf
 AUTOCONF_VERSION= 2.59
 CONFIGURE_ARGS+= ${CONFIGURE_SHARED}
-CONFIGURE_ARGS+= --enable-lzw \
-		 --with-quantum-depth=16 \
+CONFIGURE_ARGS+= --with-quantum-depth=16 \
 		 --without-dot \
 		 --without-dps \
 		 --without-fpx \
-		 --without-hdf \
 		 --without-modules \
 		 --without-threads \
 		 --without-perl \
-		 --without-wmf
+		 --without-wmf \
+		 --disable-ltdl-install
+
 CONFIGURE_ENV+=	CPPFLAGS="-I${LOCALBASE}/include/libpng -I${LOCALBASE}/include/libxml2 -I${LOCALBASE}/include" \
 		LDFLAGS="-L${WRKBUILD}/magick/.libs -L${LOCALBASE}/lib" \
 		ac_cv_path_LaunchDelegate=no
@@ -64,13 +67,30 @@ RUN_DEPENDS+=	:ghostscript-*:print/ghostscript/gnu
 USE_X11=	Yes
 RUN_DEPENDS+=	:transfig-*:print/transfig
 BUILD_DEPENDS+=	:transfig-*:print/transfig
-WANTLIB+=	ICE SM X11 Xext freetype
+WANTLIB+=	ICE SM X11 Xext Xt freetype
 .endif
 
 RUN_DEPENDS+=	:netpbm-*:graphics/netpbm
 BUILD_DEPENDS+=	:netpbm-*:graphics/netpbm
 
-WRKDIST=	${WRKDIR}/${DISTNAME:S/-${DASHVER}//}
+WRKDIST=	${WRKDIR}/${DISTNAME:S/-${DASHVER}$//}
+
+pre-configure:
+	@if pkg dependencies check ImageMagick-\*; then \
+		if pkg dependencies check ${DISTNAME}; then \
+			:; \
+		else \
+			echo 1>&2 "+-------------------"; \
+			echo 1>&2 "| Error: you must remove the existing ImageMagick installation"; \
+			echo 1>&2 "| before compiling this version. To fully remove run"; \
+			echo 1>&2 "| these commands as user root"; \
+			echo 1>&2 "|"; \
+			echo 1>&2 "|      pkg_delete `pkg_info -e 'ImageMagick-*'`"; \
+			echo 1>&2 "|"; \
+			echo 1>&2 "+-------------------"; \
+			exit 1; \
+		fi; \
+	fi
 
 post-install:
 	@perl -pi -e s#'-L${WRKBUILD}/magick/.libs '#''#g \
