Update to mplayer-20101024. Noteworthy improvements include vpx (webm) support and alpha support. This work is a joint effort from myself, naddy@ and jakemsr@. Cheers.
OK jakemsr@

diff --git a/x11/mplayer/patches/patch-configure b/x11/mplayer/patches/patch-configure
--- a/x11/mplayer/patches/patch-configure
+++ b/x11/mplayer/patches/patch-configure
@@ -1,7 +1,7 @@
-$OpenBSD: patch-configure,v 1.56 2010/05/26 21:29:56 jakemsr Exp $
---- configure.orig	Thu Mar  4 14:46:44 2010
-+++ configure	Mon Mar  8 21:09:42 2010
-@@ -423,6 +423,7 @@ Audio output:
+$OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
+--- configure.orig	Thu Oct 21 10:35:56 2010
++++ configure	Sat Nov  6 13:41:02 2010
+@@ -461,6 +461,7 @@ Audio output:
    --disable-nas          disable NAS audio output [autodetect]
    --disable-sgiaudio     disable SGI audio output [autodetect]
    --disable-sunaudio     disable Sun audio output [autodetect]
@@ -9,7 +9,7 @@ $OpenBSD: patch-configure,v 1.56 2010/05/26 21:29:56 jakemsr Exp $
    --disable-kai          disable KAI audio output [autodetect]
    --disable-dart         disable DART audio output [autodetect]
    --disable-win32waveout disable Windows waveout audio output [autodetect]
-@@ -665,6 +666,7 @@ _xf86keysym=auto
+@@ -698,6 +699,7 @@ _xf86keysym=auto
  _mlib=no #broken, thus disabled
  _sgiaudio=auto
  _sunaudio=auto
@@ -17,7 +17,7 @@ $OpenBSD: patch-configure,v 1.56 2010/05/26 21:29:56 jakemsr Exp $
  _alsa=auto
  _fastmemcpy=yes
  hardcoded_tables=no
-@@ -1098,6 +1100,8 @@ for ac_option do
+@@ -1126,6 +1128,8 @@ for ac_option do
    --disable-mlib)       _mlib=no        ;;
    --enable-sunaudio)    _sunaudio=yes   ;;
    --disable-sunaudio)   _sunaudio=no    ;;
@@ -26,7 +26,7 @@ $OpenBSD: patch-configure,v 1.56 2010/05/26 21:29:56 jakemsr Exp $
    --enable-sgiaudio)    _sgiaudio=yes   ;;
    --disable-sgiaudio)   _sgiaudio=no    ;;
    --enable-alsa)        _alsa=yes       ;;
-@@ -1434,7 +1438,7 @@ if test -z "$_target" ; then
+@@ -1446,7 +1450,7 @@ if test -z "$_target" ; then
        sh3|sh4|sh4a) host_arch=sh ;;
        s390) host_arch=s390 ;;
        s390x) host_arch=s390x ;;
@@ -35,7 +35,16 @@ $OpenBSD: patch-configure,v 1.56 2010/05/26 21:29:56 jakemsr Exp $
        vax) host_arch=vax ;;
        xtensa*) host_arch=xtensa ;;
        *) host_arch=UNKNOWN ;;
-@@ -2456,7 +2460,7 @@ cat > $TMPC << EOF
+@@ -2157,7 +2161,7 @@ case "$host_arch" in
+     arch='sparc'
+     iproc='sparc'
+     if test "$host_arch" = "sparc64" ; then
+-      _vis='yes'
++      # _vis='yes'
+       proc='ultrasparc'
+       def_fast_64bit='#define HAVE_FAST_64BIT 1'
+     elif sunos ; then
+@@ -2476,7 +2480,7 @@ cat > $TMPC << EOF
  int ff_extern;
  EOF
  cc_check -c || die "Symbol mangling check failed."
@@ -44,15 +53,40 @@ $OpenBSD: patch-configure,v 1.56 2010/05/26 21:29:56 jakemsr Exp $
  extern_prefix=${sym%%ff_extern*}
  def_extern_asm="#define EXTERN_ASM $extern_prefix"
  def_extern_prefix="#define EXTERN_PREFIX \"$extern_prefix\""
-@@ -3205,6 +3209,7 @@ if test "$_struct_sockaddr_storage" = auto; then
- #if HAVE_WINSOCK2_H
- #include <winsock2.h>
- #else
-+#include <stdlib.h>
- #include <sys/socket.h>
- #endif
- int main(void) { struct sockaddr_storage sas; return 0; }
-@@ -3613,7 +3618,7 @@ int main(void) { pthread_t tid; return pthread_create(
+@@ -2535,7 +2539,7 @@ elif test -z "$CFLAGS" ; then
+   elif test "$cc_vendor" != "gnu" ; then
+     CFLAGS="-O2 $_march $_mcpu $_pipe"
+   else
+-    CFLAGS="-O4 $_march $_mcpu $_pipe -ffast-math -fomit-frame-pointer"
++    CFLAGS="$_march $_mcpu $_pipe -ffast-math -fomit-frame-pointer"
+     WARNFLAGS="-Wall -Wno-switch -Wno-parentheses -Wpointer-arith -Wredundant-decls"
+     extra_ldflags="$extra_ldflags -ffast-math"
+   fi
+@@ -2817,8 +2821,11 @@ echores "$ibm_asm"
+ def_gnu_as='#define HAVE_GNU_AS 0'
+ gnu_as=no
+ echocheck "GNU assembler"
+-inline_asm_check '".macro m n\n\\n:.int 0\n.endm\nm x"' &&
+-  gnu_as=yes && def_gnu_as='#define HAVE_GNU_AS 1'
++# OpenBSD - some altivec stuff causes build failures, fix from kili
++if ! ppc; then
++	inline_asm_check '".macro m n\n\\n:.int 0\n.endm\nm x"' &&
++	  gnu_as=yes && def_gnu_as='#define HAVE_GNU_AS 1'
++fi
+ echores "$gnu_as"
+ 
+ fi
+@@ -3436,7 +3443,8 @@ if test "$_memalign" = yes ; then
+ else
+   def_memalign='#define HAVE_MEMALIGN 0'
+   def_map_memalign='#define memalign(a, b) malloc(b)'
+-  darwin || def_memalign_hack='#define CONFIG_MEMALIGN_HACK 1'
++  # OpenBSD - prevent CONFIG_MEMALIGN_HACK which causes exit crash
++  #darwin || def_memalign_hack='#define CONFIG_MEMALIGN_HACK 1'
+ fi
+ echores "$_memalign"
+ 
+@@ -3543,7 +3551,7 @@ int main(void) { pthread_t tid; return pthread_create(
  EOF
  _pthreads=no
  if ! hpux ; then
@@ -61,16 +95,16 @@ $OpenBSD: patch-configure,v 1.56 2010/05/26 21:29:56 jakemsr Exp $
      # for crosscompilation, we cannot execute the program, be happy if we can link statically
      cc_check $THREAD_CFLAGS $_ld_tmp && (tmp_run || test "$_ld_static") && _ld_pthread="$_ld_tmp" && _pthreads=yes && break
    done
-@@ -4892,6 +4897,8 @@ if test "$_aa" = yes ; then
+@@ -4664,6 +4672,8 @@ if test "$_aa" = yes ; then
    def_aa='#define CONFIG_AA 1'
    if cygwin ; then
      libs_mplayer="$libs_mplayer $(aalib-config --libs | cut -d " " -f 2,5,6)"
 +  else
 +    libs_mplayer="$libs_mplayer $(aalib-config --libs)"
    fi
-   _vomodules="aa $_vomodules"
+   vomodules="aa $vomodules"
  else
-@@ -5188,14 +5195,14 @@ int main(void) {
+@@ -4873,14 +4883,14 @@ int main(void) {
    return !p_ver || p_ver[0] == 0;
  }
  EOF
@@ -87,15 +121,7 @@ $OpenBSD: patch-configure,v 1.56 2010/05/26 21:29:56 jakemsr Exp $
  else
    def_mng='#undef CONFIG_MNG'
  fi
-@@ -5823,6 +5830,7 @@ fi
- if test "$_jack" = yes ; then
-   def_jack='#define CONFIG_JACK 1'
-   _aomodules="jack $_aomodules"
-+  libs_mplayer="$libs_mplayer $(pkg-config --libs jack)"
- else
-   _noaomodules="jack $_noaomodules"
- fi
-@@ -5985,6 +5993,26 @@ fi
+@@ -5691,6 +5701,26 @@ fi
  echores "$_sunaudio"
  
  
@@ -122,62 +148,46 @@ $OpenBSD: patch-configure,v 1.56 2010/05/26 21:29:56 jakemsr Exp $
  def_mlib='#define CONFIG_MLIB 0'
  if sunos; then
  echocheck "Sun mediaLib"
-@@ -6100,7 +6128,7 @@ elif dragonfly ; then
- elif freebsd ; then
-   default_cdrom_device="/dev/acd0"
- elif openbsd ; then
--  default_cdrom_device="/dev/rcd0a"
-+  default_cdrom_device="/dev/rcd0c"
- elif sunos ; then
-   default_cdrom_device="/vol/dev/aliases/cdrom0"
-   # Modern Solaris versions use HAL instead of the vold daemon, the volfs
-@@ -6169,8 +6197,9 @@ elif test "$_dvdread" = auto ; then
- #include <dvdread/nav_read.h>
- int main(void) { return 0; }
- EOF
--    _dvdreadcflags=$($_dvdreadconfig --cflags)
--    _dvdreadlibs=$($_dvdreadconfig --libs)
+@@ -5860,8 +5890,9 @@ if test "$_dvdread_internal" = auto ; then
+ elif test "$_dvdread" = auto ; then
+   _dvdread=no
+   if test "$_dl" = yes; then
+-    _dvdreadcflags=$($_dvdreadconfig --cflags 2> /dev/null)
+-    _dvdreadlibs=$($_dvdreadconfig --libs 2> /dev/null)
 +# OpenBSD - we do not use dvdread-config, picked up anyway without
-+#    _dvdreadcflags=$($_dvdreadconfig --cflags)
-+#    _dvdreadlibs=$($_dvdreadconfig --libs)
-     if cc_check -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE \
-       $_dvdreadcflags $_dvdreadlibs $_ld_dl ; then
++#    _dvdreadcflags=$($_dvdreadconfig --cflags 2> /dev/null)
++#    _dvdreadlibs=$($_dvdreadconfig --libs 2> /dev/null)
+     if header_check dvdread/dvd_reader.h $_dvdreadcflags $_dvdreadlibs $_ld_dl ; then
        _dvdread=yes
-@@ -6848,7 +6877,7 @@ if test "$_libdca" = auto ; then
- #include <dts.h>
- int main(void) { dts_init(0); return 0; }
- EOF
+       extra_cflags="$extra_cflags $_dvdreadcflags"
+@@ -6347,7 +6378,7 @@ elif test "$_libvorbis" = yes ; then
+   def_vorbis='#define CONFIG_OGGVORBIS 1'
+   codecmodules="libvorbis $codecmodules"
+   res_comment="libvorbis"
+-  extra_ldflags="$extra_ldflags -lvorbis -logg"
++  extra_ldflags="$extra_ldflags -lvorbisenc -lvorbis -logg"
+   libavencoders="$libavencoders LIBVORBIS_ENCODER"
+ else
+   _vorbis=no
+@@ -6547,7 +6578,7 @@ echores "$_libmpeg2"
+ echocheck "libdca support"
+ if test "$_libdca" = auto ; then
+   _libdca=no
 -  for _ld_dca in -ldca -ldts ; do
 +  for _ld_dca in -ldca; do
-     cc_check $_ld_dca $_ld_lm && extra_ldflags="$extra_ldflags $_ld_dca" \
-       && _libdca=yes && break
+     statement_check_broken stdint.h dts.h 'dts_init(0)' $_ld_dca $_ld_lm &&
+       extra_ldflags="$extra_ldflags $_ld_dca" && _libdca=yes && break
    done
-@@ -6898,7 +6927,7 @@ int main(void) { unsigned long x, y; faacEncOpen(48000
- EOF
-   _faac=no
-   for _ld_faac in "-lfaac" "-lfaac -lmp4v2 -lstdc++" ; do
--    cc_check -O4 $_ld_faac $_ld_lm && libs_mencoder="$libs_mencoder $_ld_faac" && _faac=yes && break
-+    cc_check $_ld_faac $_ld_lm && libs_mencoder="$libs_mencoder $_ld_faac" && _faac=yes && break
-   done
- fi
- if test "$_faac" = yes ; then
-@@ -7899,6 +7928,15 @@ if test "$_tv_v4l2" = auto ; then
- int main(void) { return 0; }
- EOF
-     cc_check && _tv_v4l2=yes
-+  else
-+    cat > $TMPC <<EOF
-+#include <stdlib.h>
-+#include <sys/types.h>
-+#include <sys/ioctl.h>
-+#include <sys/videoio.h>
-+int main(void) { return 0; }
-+EOF
-+    cc_check && _tv_v4l2=yes
+@@ -7448,6 +7479,8 @@ if test "$_tv_v4l2" = auto ; then
+   _tv_v4l2=no
+   if test "$_tv" = yes && linux ; then
+     header_check linux/videodev2.h && _tv_v4l2=yes
++  elif test "$_tv" = yes && openbsd ; then
++    header_check sys/videoio.h && _tv_v4l2=yes
    fi
  fi
  if test "$_tv_v4l2" = yes ; then
-@@ -8637,6 +8675,7 @@ SPEEX = $_speex
+@@ -8158,6 +8191,7 @@ SPEEX = $_speex
  STREAM_CACHE = $_stream_cache
  SGIAUDIO = $_sgiaudio
  SUNAUDIO = $_sunaudio
@@ -185,7 +195,7 @@ $OpenBSD: patch-configure,v 1.56 2010/05/26 21:29:56 jakemsr Exp $
  SVGA = $_svga
  TDFXFB = $_tdfxfb
  TDFXVID = $_tdfxvid
-@@ -9026,6 +9065,7 @@ $def_ossaudio_devmixer
+@@ -8540,6 +8574,7 @@ $def_ossaudio_devmixer
  $def_pulse
  $def_sgiaudio
  $def_sunaudio
