Update mplayer to a newer snapshot, this time with dynamic linking of ffmpeg! With help from and OK landry@, jakemsr@

diff --git a/x11/mplayer/patches/patch-configure b/x11/mplayer/patches/patch-configure
--- a/x11/mplayer/patches/patch-configure
+++ b/x11/mplayer/patches/patch-configure
@@ -1,7 +1,62 @@
-$OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
---- configure.orig	Thu Oct 21 10:35:56 2010
-+++ configure	Sat Nov  6 13:41:02 2010
-@@ -461,6 +461,7 @@ Audio output:
+$OpenBSD: patch-configure,v 1.58 2011/03/29 20:04:41 edd Exp $
+--- configure.orig	Wed Mar  9 00:33:03 2011
++++ configure	Wed Mar  9 00:46:58 2011
+@@ -35,29 +35,33 @@
+ #
+ #############################################################################
+ 
+-if test -e ffmpeg/.svn ; then
+-  echo "You have an outdated FFmpeg SVN checkout in ffmpeg/, please (re)move or replace it"
+-  exit 1
+-fi
+ 
+-if test -e ffmpeg/mp_auto_pull ; then
+-  if ! (cd ffmpeg && git pull --rebase --ff-only) ; then
+-    echo "git pull failed, (re)move ffmpeg/mp_auto_pull to disable pulling"
+-    exit 1
+-  fi
+-fi
++# OpenBSD
++# Don't do anything funky with git or svn, we will provide mplayer with ffmpeg
++#
++#if test -e ffmpeg/.svn ; then
++#  echo "You have an outdated FFmpeg SVN checkout in ffmpeg/, please (re)move or replace it"
++#  exit 1
++#fi
++#
++#if test -e ffmpeg/mp_auto_pull ; then
++#  if ! (cd ffmpeg && git pull --rebase --ff-only) ; then
++#    echo "git pull failed, (re)move ffmpeg/mp_auto_pull to disable pulling"
++#    exit 1
++#  fi
++#fi
++#
++#if ! test -e ffmpeg ; then
++#  echo "No FFmpeg checkout, press enter to download one with git or CTRL+C to abort"
++#  read tmp
++#  if ! git clone --depth 1 git://git.videolan.org/ffmpeg.git ffmpeg ; then
++#    rm -rf ffmpeg
++#    echo "Failed to get a FFmpeg checkout"
++#    exit 1
++#  fi
++#  touch ffmpeg/mp_auto_pull
++#fi
+ 
+-if ! test -e ffmpeg ; then
+-  echo "No FFmpeg checkout, press enter to download one with git or CTRL+C to abort"
+-  read tmp
+-  if ! git clone --depth 1 git://git.videolan.org/ffmpeg.git ffmpeg ; then
+-    rm -rf ffmpeg
+-    echo "Failed to get a FFmpeg checkout"
+-    exit 1
+-  fi
+-  touch ffmpeg/mp_auto_pull
+-fi
+-
+ # Prevent locale nonsense from breaking basic text processing utils
+ export LC_ALL=C
+ 
+@@ -510,6 +514,7 @@ Audio output:
    --disable-nas          disable NAS audio output [autodetect]
    --disable-sgiaudio     disable SGI audio output [autodetect]
    --disable-sunaudio     disable Sun audio output [autodetect]
@@ -9,7 +64,7 @@ $OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
    --disable-kai          disable KAI audio output [autodetect]
    --disable-dart         disable DART audio output [autodetect]
    --disable-win32waveout disable Windows waveout audio output [autodetect]
-@@ -698,6 +699,7 @@ _xf86keysym=auto
+@@ -745,6 +750,7 @@ _xf86keysym=auto
  _mlib=no #broken, thus disabled
  _sgiaudio=auto
  _sunaudio=auto
@@ -17,7 +72,7 @@ $OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
  _alsa=auto
  _fastmemcpy=yes
  hardcoded_tables=no
-@@ -1126,6 +1128,8 @@ for ac_option do
+@@ -1169,6 +1175,8 @@ for ac_option do
    --disable-mlib)       _mlib=no        ;;
    --enable-sunaudio)    _sunaudio=yes   ;;
    --disable-sunaudio)   _sunaudio=no    ;;
@@ -26,7 +81,7 @@ $OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
    --enable-sgiaudio)    _sgiaudio=yes   ;;
    --disable-sgiaudio)   _sgiaudio=no    ;;
    --enable-alsa)        _alsa=yes       ;;
-@@ -1446,7 +1450,7 @@ if test -z "$_target" ; then
+@@ -1489,7 +1497,7 @@ if test -z "$_target" ; then
        sh3|sh4|sh4a) host_arch=sh ;;
        s390) host_arch=s390 ;;
        s390x) host_arch=s390x ;;
@@ -35,7 +90,7 @@ $OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
        vax) host_arch=vax ;;
        xtensa*) host_arch=xtensa ;;
        *) host_arch=UNKNOWN ;;
-@@ -2157,7 +2161,7 @@ case "$host_arch" in
+@@ -2200,7 +2208,7 @@ case "$host_arch" in
      arch='sparc'
      iproc='sparc'
      if test "$host_arch" = "sparc64" ; then
@@ -44,7 +99,7 @@ $OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
        proc='ultrasparc'
        def_fast_64bit='#define HAVE_FAST_64BIT 1'
      elif sunos ; then
-@@ -2476,7 +2480,7 @@ cat > $TMPC << EOF
+@@ -2519,7 +2527,7 @@ cat > $TMPC << EOF
  int ff_extern;
  EOF
  cc_check -c || die "Symbol mangling check failed."
@@ -53,7 +108,7 @@ $OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
  extern_prefix=${sym%%ff_extern*}
  def_extern_asm="#define EXTERN_ASM $extern_prefix"
  def_extern_prefix="#define EXTERN_PREFIX \"$extern_prefix\""
-@@ -2535,7 +2539,7 @@ elif test -z "$CFLAGS" ; then
+@@ -2578,7 +2586,7 @@ elif test -z "$CFLAGS" ; then
    elif test "$cc_vendor" != "gnu" ; then
      CFLAGS="-O2 $_march $_mcpu $_pipe"
    else
@@ -62,7 +117,7 @@ $OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
      WARNFLAGS="-Wall -Wno-switch -Wno-parentheses -Wpointer-arith -Wredundant-decls"
      extra_ldflags="$extra_ldflags -ffast-math"
    fi
-@@ -2817,8 +2821,11 @@ echores "$ibm_asm"
+@@ -2860,8 +2868,11 @@ echores "$ibm_asm"
  def_gnu_as='#define HAVE_GNU_AS 0'
  gnu_as=no
  echocheck "GNU assembler"
@@ -76,7 +131,7 @@ $OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
  echores "$gnu_as"
  
  fi
-@@ -3436,7 +3443,8 @@ if test "$_memalign" = yes ; then
+@@ -3480,7 +3491,8 @@ if test "$_memalign" = yes ; then
  else
    def_memalign='#define HAVE_MEMALIGN 0'
    def_map_memalign='#define memalign(a, b) malloc(b)'
@@ -86,7 +141,7 @@ $OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
  fi
  echores "$_memalign"
  
-@@ -3543,7 +3551,7 @@ int main(void) { pthread_t tid; return pthread_create(
+@@ -3585,7 +3597,7 @@ int main(void) { pthread_t tid; return pthread_create(
  EOF
  _pthreads=no
  if ! hpux ; then
@@ -95,7 +150,7 @@ $OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
      # for crosscompilation, we cannot execute the program, be happy if we can link statically
      cc_check $THREAD_CFLAGS $_ld_tmp && (tmp_run || test "$_ld_static") && _ld_pthread="$_ld_tmp" && _pthreads=yes && break
    done
-@@ -4664,6 +4672,8 @@ if test "$_aa" = yes ; then
+@@ -4661,6 +4673,8 @@ if test "$_aa" = yes ; then
    def_aa='#define CONFIG_AA 1'
    if cygwin ; then
      libs_mplayer="$libs_mplayer $(aalib-config --libs | cut -d " " -f 2,5,6)"
@@ -104,24 +159,31 @@ $OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
    fi
    vomodules="aa $vomodules"
  else
-@@ -4873,14 +4883,14 @@ int main(void) {
-   return !p_ver || p_ver[0] == 0;
- }
- EOF
--  if cc_check -lmng -lz $_ld_lm ; then
-+  if cc_check -lmng -llcms -ljpeg -lz -lm $_ld_lm ; then
-     _mng=yes
-   fi
+@@ -4846,7 +4860,7 @@ fi
+ echores "$_png"
+ if test "$_png" = yes ; then
+   def_png='#define CONFIG_PNG 1'
+-  extra_ldflags="$extra_ldflags -lpng -lz"
++  extra_ldflags="$extra_ldflags -lpng -lz -lm"
+ else
+   def_png='#undef CONFIG_PNG'
+ fi
+@@ -4854,12 +4868,12 @@ fi
+ echocheck "MNG support"
+ if test "$_mng" = auto ; then
+   _mng=no
+-  return_statement_check libmng.h 'const char * p_ver = mng_version_text()' '!p_ver || p_ver[0] == 0' -lmng -lz $_ld_lm && _mng=yes
++  return_statement_check libmng.h 'const char * p_ver = mng_version_text()' '!p_ver || p_ver[0] == 0' -llcms -ljpeg -lmng -lz $_ld_lm && _mng=yes
  fi
  echores "$_mng"
  if test "$_mng" = yes ; then
    def_mng='#define CONFIG_MNG 1'
 -  extra_ldflags="$extra_ldflags -lmng -lz"
-+  extra_ldflags="$extra_ldflags -lmng -llcms -ljpeg -lz -lm"
++  extra_ldflags="$extra_ldflags -lmng -llcms -lz -ljpeg $_ld_m"
  else
    def_mng='#undef CONFIG_MNG'
  fi
-@@ -5691,6 +5701,26 @@ fi
+@@ -5663,6 +5677,26 @@ fi
  echores "$_sunaudio"
  
  
@@ -148,7 +210,7 @@ $OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
  def_mlib='#define CONFIG_MLIB 0'
  if sunos; then
  echocheck "Sun mediaLib"
-@@ -5860,8 +5890,9 @@ if test "$_dvdread_internal" = auto ; then
+@@ -5832,8 +5866,9 @@ if test "$_dvdread_internal" = auto ; then
  elif test "$_dvdread" = auto ; then
    _dvdread=no
    if test "$_dl" = yes; then
@@ -160,16 +222,7 @@ $OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
      if header_check dvdread/dvd_reader.h $_dvdreadcflags $_dvdreadlibs $_ld_dl ; then
        _dvdread=yes
        extra_cflags="$extra_cflags $_dvdreadcflags"
-@@ -6347,7 +6378,7 @@ elif test "$_libvorbis" = yes ; then
-   def_vorbis='#define CONFIG_OGGVORBIS 1'
-   codecmodules="libvorbis $codecmodules"
-   res_comment="libvorbis"
--  extra_ldflags="$extra_ldflags -lvorbis -logg"
-+  extra_ldflags="$extra_ldflags -lvorbisenc -lvorbis -logg"
-   libavencoders="$libavencoders LIBVORBIS_ENCODER"
- else
-   _vorbis=no
-@@ -6547,7 +6578,7 @@ echores "$_libmpeg2"
+@@ -6521,7 +6556,7 @@ echores "$_libmpeg2"
  echocheck "libdca support"
  if test "$_libdca" = auto ; then
    _libdca=no
@@ -178,16 +231,16 @@ $OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
      statement_check_broken stdint.h dts.h 'dts_init(0)' $_ld_dca $_ld_lm &&
        extra_ldflags="$extra_ldflags $_ld_dca" && _libdca=yes && break
    done
-@@ -7448,6 +7479,8 @@ if test "$_tv_v4l2" = auto ; then
+@@ -7360,6 +7395,8 @@ if test "$_tv_v4l2" = auto ; then
    _tv_v4l2=no
    if test "$_tv" = yes && linux ; then
-     header_check linux/videodev2.h && _tv_v4l2=yes
+     header_check_broken sys/time.h linux/videodev2.h && _tv_v4l2=yes
 +  elif test "$_tv" = yes && openbsd ; then
 +    header_check sys/videoio.h && _tv_v4l2=yes
    fi
  fi
  if test "$_tv_v4l2" = yes ; then
-@@ -8158,6 +8191,7 @@ SPEEX = $_speex
+@@ -8069,6 +8106,7 @@ SPEEX = $_speex
  STREAM_CACHE = $_stream_cache
  SGIAUDIO = $_sgiaudio
  SUNAUDIO = $_sunaudio
@@ -195,7 +248,7 @@ $OpenBSD: patch-configure,v 1.57 2010/11/08 21:25:44 edd Exp $
  SVGA = $_svga
  TDFXFB = $_tdfxfb
  TDFXVID = $_tdfxvid
-@@ -8540,6 +8574,7 @@ $def_ossaudio_devmixer
+@@ -8445,6 +8483,7 @@ $def_ossaudio_devmixer
  $def_pulse
  $def_sgiaudio
  $def_sunaudio
