Allow this port to be built with a 1.4 or 1.5 jdk too by including javac arguments -target 1.3 and -source 1.3 (if javac supports it).

diff --git a/databases/db/v4/patches/patch-dist_configure b/databases/db/v4/patches/patch-dist_configure
--- a/databases/db/v4/patches/patch-dist_configure
+++ b/databases/db/v4/patches/patch-dist_configure
@@ -1,6 +1,6 @@
-$OpenBSD: patch-dist_configure,v 1.7 2006/11/01 22:26:28 kurt Exp $
+$OpenBSD: patch-dist_configure,v 1.8 2006/11/15 17:23:27 kurt Exp $
 --- dist/configure.orig	Wed Dec  3 16:10:02 2003
-+++ dist/configure	Wed Jul 26 16:57:11 2006
++++ dist/configure	Tue Nov 14 17:26:54 2006
 @@ -5889,12 +5889,10 @@ nto-qnx | nto-qnx6*)
    ;;
  
@@ -64,7 +64,31 @@ $OpenBSD: patch-dist_configure,v 1.7 2006/11/01 22:26:28 kurt Exp $
  MAKEFILE_CXXLINK="\$(LIBTOOL) --mode=link ${MAKEFILE_CXXLINK}"
  
  LIBTOOL="\$(SHELL) ./libtool"
-@@ -20876,6 +20891,7 @@ if test "$_JTOPDIR" != "/usr"; then
+@@ -20313,13 +20328,22 @@ cat << \EOF > $JAVA_TEST
+ public class Test {
+ }
+ EOF
+-if { ac_try='$JAVAC $JAVACFLAGS $JAVA_TEST'
++if { ac_try='$JAVAC -source 1.3 -target 1.3 $JAVACFLAGS $JAVA_TEST'
+   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+   (eval $ac_try) 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; } >/dev/null 2>&1; then
++  JAVACFLAGS="-source 1.3 -target 1.3 $JAVACFLAGS"
+   ac_cv_prog_javac_works=yes
++elif { ac_try='$JAVAC -target 1.3 $JAVACFLAGS $JAVA_TEST'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; } >/dev/null 2>&1; then
++  JAVACFLAGS="-target 1.3 $JAVACFLAGS"
++  ac_cv_prog_javac_works=yes
+ else
+   { { echo "$as_me:$LINENO: error: The Java compiler $JAVAC failed (see config.log, check the CLASSPATH?)" >&5
+ echo "$as_me: error: The Java compiler $JAVAC failed (see config.log, check the CLASSPATH?)" >&2;}
+@@ -20876,6 +20900,7 @@ if test "$_JTOPDIR" != "/usr"; then
  	aix*)		_JNI_INC_SUBDIRS="aix";;
  	bsdi*)		_JNI_INC_SUBDIRS="bsdos";;
  	freebsd*)	_JNI_INC_SUBDIRS="freebsd";;
@@ -72,7 +96,7 @@ $OpenBSD: patch-dist_configure,v 1.7 2006/11/01 22:26:28 kurt Exp $
  	hp*)		_JNI_INC_SUBDIRS="hp-ux";;
  	linux*)		_JNI_INC_SUBDIRS="linux genunix";;
  	osf*)		_JNI_INC_SUBDIRS="alpha";;
-@@ -21441,7 +21457,7 @@ fi
+@@ -21441,7 +21466,7 @@ fi
  
  # Optional utilities.
  if test "$db_cv_dump185" = "yes"; then
@@ -81,7 +105,7 @@ $OpenBSD: patch-dist_configure,v 1.7 2006/11/01 22:26:28 kurt Exp $
  fi
  
  # Checks for include files, structures, C types.
-@@ -28525,7 +28541,7 @@ int
+@@ -28525,7 +28550,7 @@ int
  main ()
  {
  
@@ -90,7 +114,7 @@ $OpenBSD: patch-dist_configure,v 1.7 2006/11/01 22:26:28 kurt Exp $
  	exit(0);
  #else
  	FAIL TO COMPILE/LINK
-@@ -31043,7 +31059,9 @@ s,@MAKEFILE_CC@,$MAKEFILE_CC,;t t
+@@ -31043,7 +31068,9 @@ s,@MAKEFILE_CC@,$MAKEFILE_CC,;t t
  s,@MAKEFILE_CCLINK@,$MAKEFILE_CCLINK,;t t
  s,@MAKEFILE_CXX@,$MAKEFILE_CXX,;t t
  s,@MAKEFILE_CXXLINK@,$MAKEFILE_CXXLINK,;t t
