update games/0ad to alpha 26
Changelog:
https://play0ad.com/new-release-0-a-d-alpha-26-zhuangzi/

Top new features:
 - A new civilization: The Han
 - New campaign maps: Tarim basin and Yangtze.
 - Now units have acceleration.
 - Twenty-six new music tracks.
 - New and updated art.

tested also by Florian Viehweger, thanks!

ok kirby@

diff --git a/games/0ad/base/patches/patch-build_workspaces_update-workspaces_sh b/games/0ad/base/patches/patch-build_workspaces_update-workspaces_sh
--- a/games/0ad/base/patches/patch-build_workspaces_update-workspaces_sh
+++ b/games/0ad/base/patches/patch-build_workspaces_update-workspaces_sh
@@ -2,7 +2,7 @@ Don't build bundled libraries during configure.
 Index: build/workspaces/update-workspaces.sh
 --- build/workspaces/update-workspaces.sh.orig
 +++ build/workspaces/update-workspaces.sh
-@@ -86,7 +86,7 @@ if [ "`uname -s`" != "Darwin" ]; then
+@@ -90,7 +90,7 @@ if [ "`uname -s`" != "Darwin" ]; then
    echo
  
    # Build/update bundled external libraries
@@ -10,4 +10,4 @@ Index: build/workspaces/update-workspaces.sh
 +  # (cd ../../libraries/source/fcollada && MAKE=${MAKE} JOBS=${JOBS} ./build.sh) || die "FCollada build failed"
    echo
    if [ "$with_system_mozjs" = "false" ]; then
-     (cd ../../libraries/source/spidermonkey && MAKE=${MAKE} JOBS=${JOBS} ./build.sh) || die "SpiderMonkey build failed"
+     (cd ../../libraries/source/spidermonkey && MAKE=${MAKE} JOBS=${JOBS} PYTHONNOUSERSITE=true ./build.sh) || die "SpiderMonkey build failed"
