update games/0ad to 0.0.25b
thanks solene@ for help noticing the py2->py3 switch.  OK brynet@ sthen@

diff --git a/games/0ad/base/patches/patch-build_workspaces_update-workspaces_sh b/games/0ad/base/patches/patch-build_workspaces_update-workspaces_sh
--- a/games/0ad/base/patches/patch-build_workspaces_update-workspaces_sh
+++ b/games/0ad/base/patches/patch-build_workspaces_update-workspaces_sh
@@ -1,14 +1,14 @@
-$OpenBSD: patch-build_workspaces_update-workspaces_sh,v 1.6 2018/12/25 00:32:56 bentley Exp $
+$OpenBSD: patch-build_workspaces_update-workspaces_sh,v 1.7 2021/11/22 16:00:31 op Exp $
 Don't build bundled libraries during configure.
 Index: build/workspaces/update-workspaces.sh
 --- build/workspaces/update-workspaces.sh.orig
 +++ build/workspaces/update-workspaces.sh
-@@ -85,7 +85,7 @@ if [ "`uname -s`" != "Darwin" ]; then
+@@ -86,7 +86,7 @@ if [ "`uname -s`" != "Darwin" ]; then
    echo
  
    # Build/update bundled external libraries
--  (cd ../../libraries/source/fcollada/src && ${MAKE} ${JOBS}) || die "FCollada build failed"
-+#  (cd ../../libraries/source/fcollada/src && ${MAKE} ${JOBS}) || die "FCollada build failed"
+-  (cd ../../libraries/source/fcollada && MAKE=${MAKE} JOBS=${JOBS} ./build.sh) || die "FCollada build failed"
++  # (cd ../../libraries/source/fcollada && MAKE=${MAKE} JOBS=${JOBS} ./build.sh) || die "FCollada build failed"
    echo
-   if [ "$with_system_mozjs38" = "false" ]; then
+   if [ "$with_system_mozjs" = "false" ]; then
      (cd ../../libraries/source/spidermonkey && MAKE=${MAKE} JOBS=${JOBS} ./build.sh) || die "SpiderMonkey build failed"
