3.3.2 is out, rejoice. minor update.

diff --git a/x11/kde/arts3/Makefile b/x11/kde/arts3/Makefile
--- a/x11/kde/arts3/Makefile
+++ b/x11/kde/arts3/Makefile
@@ -1,9 +1,9 @@
-# $OpenBSD: Makefile,v 1.34 2004/10/19 00:25:24 espie Exp $
+# $OpenBSD: Makefile,v 1.35 2004/12/12 11:33:24 espie Exp $
 
 COMMENT=		"K Desktop Environment, aRTs"
 CATEGORIES=		x11 x11/kde
-VERSION=		3.3.1
-DISTNAME=		arts-1.3.1
+VERSION=		3.3.2
+DISTNAME=		arts-1.3.2
 MODKDE_VERSION?=	3.3.0
 
 SHARED_ONLY=		No
@@ -22,14 +22,14 @@ CONFIGURE_ENV=LDFLAGS=-L${LOCALBASE}/lib CPPFLAGS=-I${LOCALBASE}/include
 PATCH_LIST=patch-*
 
 		
-pre-build:
-	@if pkg dependencies check kdelibs-\*; then \
-		if pkg dependencies check ${DISTNAME}; then \
-			:; \
-		else \
-			echo 1>&2 "Error: you must remove your old kdelibs first"; \
-			exit 1; \
-		fi; \
-    	fi
+#pre-build:
+#	@if pkg dependencies check kdelibs-\*; then \
+#		if pkg dependencies check ${DISTNAME}; then \
+#			:; \
+#		else \
+#			echo 1>&2 "Error: you must remove your old kdelibs first"; \
+#			exit 1; \
+#		fi; \
+#    	fi
 
 .include <bsd.port.mk>
