* Use variables instead of hardcoded prefixes. * Take care to set a sane PATH. * Add set -e * Copy example files into ${PREFIX}/share/examples/PORTNAME. * Replace PKGNAME with P_NAME in INSTALL/DEINSTALL scripts, unclear   since it already exists in the Makefile with a different value. * Change output of INSTALL/DEINSTALL to be more like other scripts   found in the tree(suggested by heko@).
From maintainer Nils Nordman <nino@nforced.com>.

diff --git a/devel/gconf/pkg/INSTALL b/devel/gconf/pkg/INSTALL
--- a/devel/gconf/pkg/INSTALL
+++ b/devel/gconf/pkg/INSTALL
@@ -1,19 +1,22 @@
 #!/bin/sh
 #
-# $OpenBSD: INSTALL,v 1.1.1.1 2001/09/13 20:52:08 todd Exp $
+# $OpenBSD: INSTALL,v 1.2 2001/09/20 19:23:32 naddy Exp $
 
+set -e
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
 PREFIX=${PKG_PREFIX:-/usr/local}
-PKGNAME=gconf
-DEST_PFX=/etc
-SOURCE_PFX=${PREFIX}/share/${PKGNAME}
+P_NAME=gconf
+DEST_PFX=${SYSCONFDIR}
+SOURCE_PFX=${PREFIX}/share/examples/${P_NAME}
 
 
 do_post() {
     echo 
-    echo "*=================[ ${PKGNAME}"
+    echo "+--------------- ${P_NAME}"
 
-    install -d /etc/gconf/1
-    install -d /etc/gconf/schemas
+    install -d ${DEST_PFX}/gconf/1
+    install -d ${DEST_PFX}/gconf/schemas
+
     # install or take note of existing config files
     for f in \
 	gconf/1/path \
@@ -23,7 +26,7 @@ do_post() {
 	    OLD_CONFS="${OLD_CONFS} $f"
 	else
 	    if ! install -m 644 ${SOURCE_PFX}/$f ${DEST_PFX}/$f; then
-		echo "* ERROR: The following file could not be installed, exiting: ${DEST_PFX}/$f"
+		echo "| ERROR: The following file could not be installed, exiting: ${DEST_PFX}/$f"
 		exit 1
 	    fi
 	    NEW_CONFS="${NEW_CONFS} $f"
@@ -32,85 +35,26 @@ do_post() {
     
     # print status report
     if [ -n "${NEW_CONFS}" ]; then
-	echo "* The following NEW configuration files have been installed:"
-	echo "*"
+	echo "| The following NEW configuration files have been installed:"
+	echo "|"
 	for f in ${NEW_CONFS}; do
-	    echo "* ${DEST_PFX}/$f"
+	    echo "| ${DEST_PFX}/$f"
 	done 
     fi
     
     if [ -n "${OLD_CONFS}" ]; then
 	if [ -n "${NEW_CONFS}" ]; then
-	    echo "*"
+	    echo "|"
 	fi
-	echo "* The following OLD configuration files was found and have NOT been overwritten:"
-	echo "* You should however manually compare it to it's equivalent in ${SOURCE_PFX}"
-	echo "* and update your configuration if needed." 
-	echo "*"
+	echo "| The following OLD configuration files was found and have NOT been overwritten:"
+	echo "| You should however manually compare it to it's equivalent in ${SOURCE_PFX}"
+	echo "| and update your configuration if needed." 
+	echo "|"
 	for f in ${OLD_CONFS}; do
-	    echo "* ${DEST_PFX}/$f"
+	    echo "| ${DEST_PFX}/$f"
 	done 
     fi
-    echo "*================= ${PKGNAME} ]"
-    echo 
-}
-
-# verify proper execution
-#
-if [ $# -ne 2 ]; then
-    echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
-    exit 1
-fi
-
-# Verify/process the command
-#
-case $2 in
-    PRE-INSTALL)
-        ;;
-    POST-INSTALL)
-        do_post
-        ;;
-    *)
-        echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
-        exit 1
-        ;;
-esac
-
-exit 0
-
-
-
-
-#!/bin/sh
-#
-# $OpenBSD: INSTALL,v 1.1.1.1 2001/09/13 20:52:08 todd Exp $
-#
-
-PREFIX=${PKG_PREFIX:-/usr/local}
-
-# $1 real file
-# $2 example file
-# $3 real path
-install_conf() {
-    if [ -f $1 ]; then
-	    echo "| Your existing configuration file $1 has not been modified."
-	    echo "| You should however compare it to it's equivalent in ${PREFIX}/share/gconf"
-	    echo "| and update it if neccessary."
-		echo "|"
-	else
-	    install -d $3
-	    install -m 644 $2 $1
-	    echo "| Installed new configfile $1"
-	fi
-}
-
-do_post() {
-    echo 
-    echo "+----------------"
-    install_conf "/etc/gconf/1/path" "${PREFIX}/share/gconf/1/path.example" "/etc/gconf/1"
-    install_conf "/etc/gconf/schemas/desktop.schemas" "${PREFIX}/share/gconf/schemas/desktop.schemas" \
-		  "/etc/gconf/schemas"
-    echo "+----------------"
+    echo "+--------------- ${P_NAME}"
     echo 
 }
 
