update to gnuplot-5.4.8, modified from a diff by gonzalo@, maintainer timeout

diff --git a/math/gnuplot/patches/patch-configure b/math/gnuplot/patches/patch-configure
--- a/math/gnuplot/patches/patch-configure
+++ b/math/gnuplot/patches/patch-configure
@@ -3,39 +3,39 @@ readline -> ereadline
 Index: configure
 --- configure.orig
 +++ configure
-@@ -10168,7 +10168,7 @@ fi
+@@ -11738,7 +11738,7 @@ fi
        if test -d $with_readline/lib; then
          LDFLAGS="$LDFLAGS -L$with_readline/lib"
        fi
 -            if test ! -d $with_readline/include/readline; then
 +            if test ! -d $with_readline/include/ereadline; then
          if test -d $with_readline/include/editline; then
-           { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: $with_readline contains libedit, not readline!" >&5
- $as_echo "$as_me: WARNING: $with_readline contains libedit, not readline!" >&2;}
-@@ -10261,7 +10261,7 @@ if ${ac_cv_lib_readline_remove_history+:} false; then 
-   $as_echo_n "(cached) " >&6
- else
+           { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: $with_readline contains libedit, not readline!" >&5
+ printf "%s\n" "$as_me: WARNING: $with_readline contains libedit, not readline!" >&2;}
+@@ -11830,7 +11830,7 @@ then :
+   printf %s "(cached) " >&6
+ else $as_nop
    ac_check_lib_save_LIBS=$LIBS
 -LIBS="-lreadline ${gp_tcap} $LIBS"
 +LIBS="-lereadline ${gp_tcap} $LIBS"
  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
  /* end confdefs.h.  */
  
-@@ -10292,7 +10292,7 @@ fi
- { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_readline_remove_history" >&5
- $as_echo "$ac_cv_lib_readline_remove_history" >&6; }
- if test "x$ac_cv_lib_readline_remove_history" = xyes; then :
+@@ -11860,7 +11860,7 @@ fi
+ printf "%s\n" "$ac_cv_lib_readline_remove_history" >&6; }
+ if test "x$ac_cv_lib_readline_remove_history" = xyes
+ then :
 -  TERMLIBS="-lreadline $gp_tcap $TERMLIBS"
 +  TERMLIBS="-lereadline $gp_tcap $TERMLIBS"
  fi
  
      if test "$ac_cv_lib_readline_remove_history" = no; then
-@@ -10333,7 +10333,7 @@ fi
- { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_history_remove_history" >&5
- $as_echo "$ac_cv_lib_history_remove_history" >&6; }
- if test "x$ac_cv_lib_history_remove_history" = xyes; then :
+@@ -11901,7 +11901,7 @@ fi
+ printf "%s\n" "$ac_cv_lib_history_remove_history" >&6; }
+ if test "x$ac_cv_lib_history_remove_history" = xyes
+ then :
 -  TERMLIBS="-lreadline -lhistory $gp_tcap $TERMLIBS"
 +  TERMLIBS="-lereadline -lhistory $gp_tcap $TERMLIBS"
- else
-    { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: GNU readline not found - falling back to builtin readline" >&5
- $as_echo "$as_me: WARNING: GNU readline not found - falling back to builtin readline" >&2;}
+ else $as_nop
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: GNU readline not found - falling back to builtin readline" >&5
+ printf "%s\n" "$as_me: WARNING: GNU readline not found - falling back to builtin readline" >&2;}
