Update to new Tcl layout. While there, make use of the tcl/tk modules.
OK landry@, stu@

diff --git a/net/ns/patches/patch-configure b/net/ns/patches/patch-configure
--- a/net/ns/patches/patch-configure
+++ b/net/ns/patches/patch-configure
@@ -1,6 +1,42 @@
-$OpenBSD: patch-configure,v 1.2 2007/10/24 15:01:09 steven Exp $
+$OpenBSD: patch-configure,v 1.3 2011/01/05 19:06:06 sebastia Exp $
 --- configure.orig	Mon Feb 19 00:50:28 2007
-+++ configure	Sat Oct 13 22:22:22 2007
++++ configure	Thu Dec 23 14:01:23 2010
+@@ -4562,7 +4562,7 @@ else
+ echo "$as_me: error: $d is not a directory" >&2;}
+    { (exit 1); exit 1; }; }
+ 		fi
+-		places="$TCL_H_PLACES_D"
++		places="$TCL_H_PLACES_D $TCL_H_PLACES"
+ 	fi
+ 
+ 	V_INCLUDE_TCL=""
+@@ -4621,7 +4621,7 @@ else
+ echo "$as_me: error: $d is not a directory" >&2;}
+    { (exit 1); exit 1; }; }
+ 		fi
+-		places="$TCL_LIB_PLACES_D"
++		places="$TCL_LIB_PLACES_D $TCL_LIB_PLACES"
+ 	fi
+ 
+ 	V_LIB_TCL=""
+@@ -5008,7 +5008,7 @@ else
+ echo "$as_me: error: $d is not a directory" >&2;}
+    { (exit 1); exit 1; }; }
+ 		fi
+-		places="$TK_H_PLACES_D"
++		places="$TK_H_PLACES_D $TK_H_PLACES"
+ 	fi
+ 
+ 	V_INCLUDE_TK=""
+@@ -5067,7 +5067,7 @@ else
+ echo "$as_me: error: $d is not a directory" >&2;}
+    { (exit 1); exit 1; }; }
+ 		fi
+-		places="$TK_LIB_PLACES_D"
++		places="$TK_LIB_PLACES_D $TK_LIB_PLACES"
+ 	fi
+ 
+ 	V_LIB_TK=""
 @@ -5457,7 +5457,7 @@ TCLCL_H_PLACES="\
                  /usr/src/local/Tcl \
                  /usr/src/local/Tcl-1.0 \
