Fix INSTALL scripts so that the principal action is not executed twice at install time.  Also remove yet another instance of that action from the package list.

diff --git a/security/cyrus-sasl/pkg/INSTALL b/security/cyrus-sasl/pkg/INSTALL
--- a/security/cyrus-sasl/pkg/INSTALL
+++ b/security/cyrus-sasl/pkg/INSTALL
@@ -1,12 +1,35 @@
 #!/bin/sh
 #
-# $OpenBSD: INSTALL,v 1.2 2003/02/04 22:59:48 naddy Exp $
+# $OpenBSD: INSTALL,v 1.3 2003/06/17 23:09:00 naddy Exp $
 
+# exit on errors, use a sane path and install prefix
+#
+set -e
 PATH=/bin:/usr/bin:/sbin:/usr/sbin
 PREFIX=${PKG_PREFIX:-/usr/local}
 
-if [ ! -e /usr/lib/sasl ]; then 
-	ln -s ${PREFIX}/lib/sasl /usr/lib/sasl
+# verify proper execution
+#
+if [ $# -ne 2 ]; then
+    echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
+    exit 1
 fi
+
+# Verify/process the command
+#
+case $2 in
+    PRE-INSTALL)
+	: nothing to pre-install for this port
+	;;
+    POST-INSTALL)
+	if [ ! -e /usr/lib/sasl ]; then
+		ln -s ${PREFIX}/lib/sasl /usr/lib/sasl
+	fi
+	;;
+    *)
+	echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
+	exit 1
+	;;
+esac
 
 exit 0
