Update to 1.2.9; from Sigfred Haversen <bsdlist@mumak.com>

diff --git a/net/rsnapshot/patches/patch-configure b/net/rsnapshot/patches/patch-configure
--- a/net/rsnapshot/patches/patch-configure
+++ b/net/rsnapshot/patches/patch-configure
@@ -1,19 +1,29 @@
-$OpenBSD: patch-configure,v 1.1.1.1 2005/02/21 16:08:06 alek Exp $
---- configure.orig	Wed Feb  2 05:17:47 2005
-+++ configure	Tue Feb 15 19:38:14 2005
-@@ -3090,7 +3090,7 @@ fi
- RSNAPSHOT_SYSCONFDIR=`eval echo ${sysconfdir}`
+$OpenBSD: patch-configure,v 1.2 2006/08/01 12:32:36 alek Exp $
+--- configure.orig	Fri Jul 14 18:19:33 2006
++++ configure	Fri Jul 14 18:22:58 2006
+@@ -3295,58 +3295,3 @@ if test "$no_create" != yes; then
+ fi
  
- if test -e "$RSNAPSHOT_SYSCONFDIR/rsnapshot.conf"; then
+ 
+-# this is kludgy, but it works
+-RSNAPSHOT_SYSCONFDIR=`eval echo ${sysconfdir}`
+-
+-if test -e "$RSNAPSHOT_SYSCONFDIR/rsnapshot.conf"; then
 -	RSNAPSHOT_OLD_VERSION=`$PERL rsnapshot-program.pl -c $RSNAPSHOT_SYSCONFDIR/rsnapshot.conf check-config-version`
-+	RSNAPSHOT_OLD_VERSION=`$PERL rsnapshot -c $RSNAPSHOT_SYSCONFDIR/rsnapshot.conf check-config-version`
- 
- 	# figure out if this is a fresh install or an upgrade
- 	# advise the user accordingly
-@@ -3105,15 +3105,6 @@ if test -e "$RSNAPSHOT_SYSCONFDIR/rsnaps
- 		echo "| If you don't upgrade your config file, rsnapshot will appear to work, but  |"
- 		echo "| rearrange the relative paths to your backup files when you aren't looking. |"
- 		echo "| It would be a nasty surprise, which is why we're telling you about it now. |"
+-
+-	# figure out if this is a fresh install or an upgrade
+-	# advise the user accordingly
+-	if test "$RSNAPSHOT_OLD_VERSION" = "unknown"; then
+-		echo ""
+-		echo "+----------------------------------------------------------------------------+"
+-		echo "| A previous version of rsnapshot was detected.                              |"
+-		echo "|                                                                            |"
+-		echo "| If you have not already done so, it is HIGHLY recommended that you upgrade |"
+-		echo "| your config file for compatibility with this release.                      |"
+-		echo "|                                                                            |"
+-		echo "| If you don't upgrade your config file, rsnapshot will appear to work, but  |"
+-		echo "| rearrange the relative paths to your backup files when you aren't looking. |"
+-		echo "| It would be a nasty surprise, which is why we're telling you about it now. |"
 -		echo "|                                                                            |"
 -		echo "| If you would like to automatically upgrade your config file, just type:    |"
 -		echo "|                                                                            |"
@@ -23,15 +33,25 @@ $OpenBSD: patch-configure,v 1.1.1.1 2005/02/21 16:08:06 alek Exp $
 -		echo "|                                                                            |"
 -		echo "| For more information on the upgrade, read the INSTALL file that came with  |"
 -		echo "| the program.                                                               |"
- 		echo "+----------------------------------------------------------------------------+"
- 		exit 0
- 	fi
-@@ -3130,13 +3121,4 @@ if test -e "$RSNAPSHOT_SYSCONFDIR/rsnaps
- 	fi
- fi
- 
+-		echo "+----------------------------------------------------------------------------+"
+-		exit 0
+-	fi
+-
+-	# this is already the latest version.
+-	if test "$RSNAPSHOT_OLD_VERSION" = "1.2"; then
+-		echo "$RSNAPSHOT_SYSCONFDIR/rsnapshot.conf found, and is up to date."
+-	else
+-		echo ""
+-		echo "ERROR: $RSNAPSHOT_SYSCONFDIR/rsnapshot.conf is an unknown version."
+-		echo "Upgrading is not recommended until you figure out what's wrong."
+-		echo ""
+-		exit 1
+-	fi
+-fi
+-
 -echo ""
--echo "Now type \"make install\" to install the program."
+-echo "Now type  \"make test\"    to run the regression test suite."
+-echo "Then type \"make install\" to install the program."
 -echo ""
 -
 -if test ! -e "$RSNAPSHOT_SYSCONFDIR/rsnapshot.conf"; then
@@ -39,4 +59,4 @@ $OpenBSD: patch-configure,v 1.1.1.1 2005/02/21 16:08:06 alek Exp $
 -	echo "$RSNAPSHOT_SYSCONFDIR/rsnapshot.conf.default to $RSNAPSHOT_SYSCONFDIR/rsnapshot.conf"
 -	echo ""
 -fi
- 
+-
