upgrade to ORBit-0.4.3

diff --git a/devel/ORBit/Makefile b/devel/ORBit/Makefile
--- a/devel/ORBit/Makefile
+++ b/devel/ORBit/Makefile
@@ -1,29 +1,43 @@
-# $OpenBSD: Makefile,v 1.4 1999/04/08 22:41:21 brad Exp $
+# $OpenBSD: Makefile,v 1.5 1999/05/06 17:17:37 brad Exp $
 
-DISTNAME=		ORBit-0.4.0
-CATEGORIES=		devel
+DISTNAME=	ORBit-0.4.3
+CATEGORIES=	devel
 MASTER_SITES=	${MASTER_SITE_GNOME}
 MASTER_SITE_SUBDIR=	ORBit
 
-NEED_VERSION=		1.79
+NEED_VERSION=	1.73
 
-MAINTAINER=		rohee@OpenBSD.ORG
+MAINTAINER=	rohee@openbsd.org
 
-BUILD_DEPENDS=	libtool:${PORTSDIR}/devel/libtool \
-		gindent:${PORTSDIR}/devel/gindent
 LIB_DEPENDS+=	glib.1.2:${PORTSDIR}/devel/glib
 
-USE_GMAKE=		yes
-
+USE_GMAKE=	yes
 GNU_CONFIGURE=	yes
 CONFIGURE_ARGS+= ${CONFIGURE_SHARED}
-CONFIGURE_ARGS+= --enable-static
-CONFIGURE_ENV=	LIBTOOL=/usr/local/bin/libtool
+CONFIGURE_ARGS+= --enable-static --disable-indent
+CONFIGURE_ENV=	GLIB_CONFIG="${LOCALBASE}/bin/glib-config"
+
+# People that installed an older version of ORBit 0.4.x wound up with
+# shared libs with a major/minor of 4.0 ... these files
+# MUST be removed as the version was incorrect (it came from 1.1.x
+# sources). Check that out here (and bitch if necessary).
+pre-extract:
+        @if [ -f ${LOCALBASE}/lib/libORBit.so.4.0 ]; then \
+           echo "+-------------------"; \
+           echo "| ERROR: you MUST remove the existing ORBit installation"; \
+           echo "| before installing this version. To fully remove run"; \
+           echo "| these commands as user root"; \
+           echo "|"; \
+           echo "|      pkg_delete -f `pkg_info -e 'ORBit-*'`"; \
+           echo "|      ldconfig ${LOCALBASE}/lib"; \
+           echo "|"; \
+           echo "+-------------------"; \
+           exit 1; \
+        fi
 
 post-install:
-	@test -f ${PREFIX}/info/dir || \
-		sed -ne '1,/Menu:/p' /usr/share/info/dir > ${PREFIX}/info/dir
-	@install-info ${PREFIX}/info/libIDL.info ${PREFIX}/info/dir
-	${LDCONFIG} -m ${PREFIX}/lib
+	@if [ -d ${PREFIX}/info -a ! -f ${PREFIX}/info/dir -a -f /usr/share/info/dir ]; then \
+	  ${SED} -ne '1,/Menu:/p' /usr/share/info/dir > ${PREFIX}/info/dir; \
+	fi
 
 .include <bsd.port.mk>
