- add HOMEPAGE - remove FAKE=Yes and license type - remove configure script and integrate it into the Makefile - add #!/bin/sh to DEINSTALL - re-arrange INSTALL script a bit and remove bogus PIDFILE variable

diff --git a/mail/pine/pkg/INSTALL b/mail/pine/pkg/INSTALL
--- a/mail/pine/pkg/INSTALL
+++ b/mail/pine/pkg/INSTALL
@@ -1,7 +1,13 @@
 #!/bin/sh
-# $OpenBSD: INSTALL,v 1.1 1999/04/08 17:36:49 marc Exp $
+# $OpenBSD: INSTALL,v 1.2 2000/07/10 22:54:33 brad Exp $
 #
 # Pre/post-installation setup of pine
+
+# exit on errors, use a sane path and install prefix
+#
+set -e
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+PREFIX=${PKG_PREFIX:-/usr/local}
 
 # Function: tell the user what s/he needs to do to use the port just installed
 #
@@ -17,13 +23,6 @@ do_notice()
     echo "+---------------"
     echo
 }
-
-# exit on errors, use a sane path and install prefix
-#
-set -e
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
-PREFIX=${PKG_PREFIX:-/usr/local}
-PIDFILE=/var/run/sshd.pid
 
 # verify proper execution
 #
