- use correct major/minor version for shared libs - add message to warn if previous version of gimp 1.1.x is installed and   remind user to remove it - lack of needed include directory in new gtk's gtk-config broke   compiling, add patches to fix compiling

diff --git a/graphics/gimp/Makefile b/graphics/gimp/Makefile
--- a/graphics/gimp/Makefile
+++ b/graphics/gimp/Makefile
@@ -1,4 +1,4 @@
-# $OpenBSD: Makefile,v 1.16 1999/03/31 08:00:24 marc Exp $
+# $OpenBSD: Makefile,v 1.17 1999/04/08 04:21:52 brad Exp $
 
 DISTNAME=	gimp-1.1.4
 CATEGORIES=	graphics
@@ -28,6 +28,24 @@ CONFIGURE_ARGS+= --enable-static --disable-perl
 CONFIGURE_ENV=	CPPFLAGS="-I${LOCALBASE}/include" \
 		LDFLAGS="-L${LOCALBASE}/lib" \
 		GTK_CONFIG="${X11BASE}/bin/gtk-config"
+
+# People that installed an older version of gimp 1.1.x wound up with
+# shared libs with a major/minor of 1.3 or 1.4 ... these files
+# MUST be removed as the version was incorrect (it came from 1.1.x
+# sources). Check that out here (and bitch if necessary).
+pre-extract:
+	@if [ -f ${X11BASE}/lib/libgimp.so.1.3 -o -f ${X11BASE}/lib/libgimp.so.1.4 ]; then \
+	   echo "+-------------------"; \
+	   echo "| ERROR: you MUST remove the existing gimp installation"; \
+	   echo "| before installing this version. To fully remove run"; \
+	   echo "| these commands as user root"; \
+	   echo "|"; \
+	   echo "|      pkg_delete -f `pkg_info -e 'gimp-*'`"; \
+	   echo "|      ldconfig ${X11BASE}/lib"; \
+	   echo "|"; \
+	   echo "+-------------------"; \
+	   exit 1; \
+	fi
 
 post-install:
 	@${MKDIR} ${LOCALBASE}/share/aclocal
