Cope with the new location of audio/soundtouch's pkg-config file.

diff --git a/audio/audacity/patches/patch-configure b/audio/audacity/patches/patch-configure
--- a/audio/audacity/patches/patch-configure
+++ b/audio/audacity/patches/patch-configure
@@ -1,6 +1,5 @@
-$OpenBSD: patch-configure,v 1.13 2010/06/13 15:49:10 jakemsr Exp $
 --- configure.orig	Mon Aug 31 03:45:37 2009
-+++ configure	Sun Jun  6 19:19:44 2010
++++ configure	Sat Apr 11 22:02:36 2015
 @@ -822,7 +822,6 @@ JACK_CFLAGS
  JACK_LIBS'
  ac_subdirs_all='"lib-src/FileDialog"
@@ -27,6 +26,50 @@ $OpenBSD: patch-configure,v 1.13 2010/06/13 15:49:10 jakemsr Exp $
        LIBFLAC_SYSTEM_CPPSYMBOLS="USE_LIBFLAC"
        { $as_echo "$as_me:$LINENO: FLAC libraries are available as system libraries" >&5
  $as_echo "$as_me: FLAC libraries are available as system libraries" >&6;}
+@@ -7684,12 +7683,12 @@ if test -n "$SOUNDTOUCH_CFLAGS"; then
+     pkg_cv_SOUNDTOUCH_CFLAGS="$SOUNDTOUCH_CFLAGS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"soundtouch-1.0 >= 1.3.0\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "soundtouch-1.0 >= 1.3.0") 2>&5
++    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"soundtouch >= 1.3.0\"") >&5
++  ($PKG_CONFIG --exists --print-errors "soundtouch >= 1.3.0") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_SOUNDTOUCH_CFLAGS=`$PKG_CONFIG --cflags "soundtouch-1.0 >= 1.3.0" 2>/dev/null`
++  pkg_cv_SOUNDTOUCH_CFLAGS=`$PKG_CONFIG --cflags "soundtouch >= 1.3.0" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -7700,12 +7699,12 @@ if test -n "$SOUNDTOUCH_LIBS"; then
+     pkg_cv_SOUNDTOUCH_LIBS="$SOUNDTOUCH_LIBS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"soundtouch-1.0 >= 1.3.0\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "soundtouch-1.0 >= 1.3.0") 2>&5
++    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"soundtouch >= 1.3.0\"") >&5
++  ($PKG_CONFIG --exists --print-errors "soundtouch >= 1.3.0") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_SOUNDTOUCH_LIBS=`$PKG_CONFIG --libs "soundtouch-1.0 >= 1.3.0" 2>/dev/null`
++  pkg_cv_SOUNDTOUCH_LIBS=`$PKG_CONFIG --libs "soundtouch >= 1.3.0" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -7723,9 +7722,9 @@ else
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        SOUNDTOUCH_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "soundtouch-1.0 >= 1.3.0" 2>&1`
++	        SOUNDTOUCH_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "soundtouch >= 1.3.0" 2>&1`
+         else
+-	        SOUNDTOUCH_PKG_ERRORS=`$PKG_CONFIG --print-errors "soundtouch-1.0 >= 1.3.0" 2>&1`
++	        SOUNDTOUCH_PKG_ERRORS=`$PKG_CONFIG --print-errors "soundtouch >= 1.3.0" 2>&1`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$SOUNDTOUCH_PKG_ERRORS" >&5
 @@ -9215,13 +9214,8 @@ _ACEOF
  esac
  
