Update to abcde-2.7.1, from Marc Peters.
Tested by and ok chrisz@

diff --git a/audio/abcde/patches/patch-abcde b/audio/abcde/patches/patch-abcde
--- a/audio/abcde/patches/patch-abcde
+++ b/audio/abcde/patches/patch-abcde
@@ -1,14 +1,13 @@
-$OpenBSD: patch-abcde,v 1.7 2012/11/21 20:38:48 sthen Exp $
---- abcde.orig	Tue Sep 18 15:09:31 2012
-+++ abcde	Sat Nov 17 16:09:52 2012
+--- abcde.orig	Sun Oct  4 11:30:28 2015
++++ abcde	Thu Oct 22 15:51:49 2015
 @@ -1,4 +1,4 @@
 -#!/bin/bash
 +#!${LOCALBASE}/bin/bash
  # Copyright (c) 1998-2001 Robert Woodcock <rcw@debian.org>
  # Copyright (c) 2003-2006 Jesus Climent <jesus.climent@hispalinux.es>
  # Copyright (c) 2009-2012 Colin Tuckley <colint@debian.org>
-@@ -833,6 +833,16 @@ do_tag ()
- 						${TPE2:+--set-text-frame=TPE2:"$TPE2"} \
+@@ -839,6 +839,16 @@
+ 						${TPE2:+--TPE2 "$TPE2"} \
  						"$ABCDETEMPDIR/track$1.$OUTPUT"
  					;;
 +				id3tag)
@@ -21,56 +20,55 @@ $OpenBSD: patch-abcde,v 1.7 2012/11/21 20:38:48 sthen Exp $
 +						${TRACKNUM:+-T "$TRACKS"} \
 +						"$ABCDETEMPDIR/track$1.$OUTPUT"
 +					;;
- 				# FIXME # Still not activated...
- 				id3ed)
- 					run_command tagtrack-$OUTPUT-$1 nice $ENCNICE \
-@@ -3165,7 +3175,7 @@ VAPLAYLISTFORMAT='${ARTISTFILE}-${ALBUMFILE}.${OUTPUT}
+ 				eyed3*)
+ 					# FIXME # track numbers in mp3 come with 1/10, so we cannot
+ 					# happily substitute them with $TRACKNUM
+@@ -3471,7 +3481,7 @@
  VAPLAYLISTDATAPREFIX=''
  DOSPLAYLIST=n
  COMMENT=''
--ID3TAGV=2
+-ID3TAGV=id3v2.4
 +ID3TAGV=id3tag
  ENCNICE=10
  READNICE=10
  DISTMP3NICE=10
-@@ -3207,6 +3217,7 @@ AACENC=faac
- 
+@@ -3537,6 +3547,7 @@
  ID3=id3
  ID3V2=id3v2
+ MID3V2=mid3v2
 +ID3TAG=id3tag
  EYED3=eyeD3
  VORBISCOMMENT=vorbiscomment
  METAFLAC=metaflac
-@@ -3259,6 +3270,7 @@ AACENCOPTS=
+@@ -3621,6 +3632,7 @@
+ FFMPEGENCOPTS=
  
  ID3OPTS=
- ID3V2OPTS=
 +ID3TAGOPTS=
+ EYED3OPTS=""
+ ATOMICPARSLEYOPTS=
  CDPARANOIAOPTS=
- CDDA2WAVOPTS=
- DAGRABOPTS=
-@@ -3310,7 +3322,7 @@ elif [ X$(uname) = "XDarwin" ] ; then
- 	NEEDDISKUTIL=y
- 	CDROMREADERSYNTAX=cddafs
+@@ -3683,7 +3695,7 @@
+ 	# We won't find the eject program in OSX, and doing checkexec will fail further below...
+ 	unset EJECT
  elif [ X$(uname) = "XOpenBSD" ] ; then
 -	HTTPGET=wget
 +	HTTPGET=ftp
  	MD5SUM=md5
  	OSFLAVOUR=OBSD
  elif [ X$(uname) = "XNetBSD" ] ; then
-@@ -3875,11 +3887,15 @@ esac
- if [ "$ID3TAGV" = "1" ]; then
- 	TAGGER="$ID3"
- 	TAGGEROPTS="$ID3OPTS"
-+else if [ "$ID3TAGV" = "id3tag" ]; then
-+	TAGGER="$ID3TAG"
-+	TAGGEROPTS="$ID3TAGOPTS"
- else
- 	TAGGER="$EYED3"
- 	TAGGEROPTS="$ID3V2OPTS"
- 	ID3SYNTAX=eyed3
- 	TAGGEROPTS="--set-encoding=utf16-LE $ID3V2OPTS"
-+fi
- fi
- 
- # NOGAP is specific to lame. Other encoders fail ...
+@@ -4427,8 +4439,13 @@
+ 			TAGGEROPTS="--encoding utf16 $EYED3OPTS"
+ 		fi
+ 		;;
++	id3tag)
++		TAGGER="$ID3TAG"
++		ID3SYNTAX=id3tag
++		TAGGEROPTS="$ID3TAGOPTS"
++		;;
+ 	*)
+-		log error "Error: ID3TAGV must be either \"id3v1\", \"id3v2.3\" or \"id3v2.4\""
++		log error "Error: ID3TAGV must be either \"id3v1\", \"id3v2.3\", \"id3v2.4\" or \"id3tag\""
+ 		exit 1
+ 		;;
+ esac
