separate linking of executables into its own class

diff --git a/infrastructure/build/libtool b/infrastructure/build/libtool
--- a/infrastructure/build/libtool
+++ b/infrastructure/build/libtool
@@ -1,5 +1,5 @@
 #!/usr/bin/perl
-# $OpenBSD: libtool,v 1.66 2008/11/16 21:58:17 steven Exp $
+# $OpenBSD: libtool,v 1.67 2008/11/18 22:16:44 steven Exp $
 
 # Copyright (c) 2007-2008 Steven Mestdagh <steven@openbsd.org>
 #
@@ -362,6 +362,148 @@ sub compile
 	}
 }
 
+package Program;
+use File::Basename;
+
+sub new
+{
+	my $class = shift;
+	bless {}, $class;
+}
+
+# write a wrapper script for an executable so it can be executed within
+# the build directory
+sub write_wrapper
+{
+	my $self = shift;
+	my $program = shift;
+
+	my $ltdir = $main::ltdir;
+	my $version = $main::version;
+	open(my $pw, '>', $program) or die "cannot write $program: $!\n";
+	print $pw <<EOF
+#!/bin/sh
+
+# $program - wrapper for $ltdir/$program
+# Generated by libtool $version
+
+argdir=`dirname \$0`
+if test -f "\$argdir/$ltdir/$program"; then
+    # Add our own library path to LD_LIBRARY_PATH
+    LD_LIBRARY_PATH=\$argdir/$ltdir
+    export LD_LIBRARY_PATH
+
+    # Run the actual program with our arguments.
+    exec "\$argdir/$ltdir/$program" \${1+"\$\@"}
+
+    echo "\$0: cannot exec $program \${1+"\$\@"}"
+    exit 1
+else
+    echo "\$0: error: \\\`\$argdir/$ltdir/$program' does not exist." 1>&2
+    exit 1
+fi
+EOF
+;
+}
+
+sub is_wrapper
+{
+#	my $self = shift;
+	my $program = shift;
+
+	open(my $pw, '<', $program) or die "cannot open $program: $!\n";
+	return eval(grep { m/wrapper\sfor/ } <$pw>);
+}
+
+sub link
+{
+	my $self = shift;
+	my $prog = shift;
+	my $la = shift;
+	my $fname = shift;
+	my $odir = shift;
+	my $shared = shift;
+	my $objs = shift;
+	my $libs = shift;
+	my $libstofind = shift;
+	my $opts = shift;
+	my $RPdirs = shift;
+
+	my $ltdir = $main::ltdir;
+	Trace::debug {"linking program (",
+		($shared) ? "dynam" : "stat", "ically)\n"};
+	
+	my @libflags;
+	my @cmd;
+	my $dst = ($odir eq '.') ? "$ltdir/$fname" : "$odir/$ltdir/$fname";
+	mkdir "$odir/$ltdir" if (! -d "$odir/$ltdir");
+
+	Trace::debug {"argvstring (pre resolve_la): @ARGV\n"};
+	my $argv = main::resolve_la_list(\@ARGV);
+	Trace::debug {"argvstring (post resolve_la): @$argv\n"};
+	my $orderedlibs = [];
+	$argv = main::parse_linkargs_list($argv, 0, $orderedlibs);
+	Trace::debug {"orderedlibs = @$orderedlibs\n"};
+	my $finalorderedlibs = main::reverse_zap_duplicates_ref($orderedlibs);
+	Trace::debug {"final orderedlibs = @$finalorderedlibs\n"};
+
+	# static linking
+	if (!$shared) {
+		die "static linking of programs not supported yet\n";
+	}
+
+	# dynamic linking
+	my $symbolsfile;
+	if ($opts->{'export-symbols'}) {
+		$symbolsfile = $opts->{'export-symbols'};
+	} elsif ($opts->{'export-symbols-regex'}) {
+		$symbolsfile = "$odir/$ltdir/$la";
+		$symbolsfile =~ s/\.la$/.exp/;
+		main::get_symbollist($symbolsfile, $opts->{'export-symbols-regex'}, $objs);
+	}
+	$RPdirs = main::reverse_zap_duplicates_ref($RPdirs);
+	map { $_ = "-Wl,-rpath,$_" } @$RPdirs;
+	foreach my $l (keys %$libstofind) {
+		my $libpath = main::find_lib($l);
+		$libs->{$l} = $libpath if ($libpath);
+	}
+
+	my @libfiles = values %$libs;
+	Trace::debug {"libs:\n", join("\n", (keys %$libs)), "\n"};
+	Trace::debug {"libfiles:\n", join("\n", @libfiles), "\n"};
+
+	main::create_symlinks($ltdir, \@libfiles);
+	map { $_ = "$ltdir/". basename $_ } @libfiles;
+	Trace::debug {"symlinks to libfiles used for linking:\n", join("\n", @libfiles), "\n"};
+	my $libcounter = 0;
+	foreach my $k (@$finalorderedlibs) {
+		my $a = $libs->{$k} || die "ERROR: $k not found in \$libs";
+		if ($a =~ m/\.a$/) {
+			# don't make a -lfoo out of a static library
+			push @libflags, $a;
+		} else {
+			my $lib = basename $a;
+			if ($lib =~ m/^lib(.*)\.so(\.\d+){2}/) {
+				$lib = $1;
+			} else {
+				say "warning: cannot derive -l flag from library filename, assuming hash key";
+				$lib = $k;
+			}
+			push @libflags, "-l$lib";
+		}
+		$libcounter++;
+	}
+
+	@cmd = ($prog);
+	push @cmd, '-o', $dst;
+	push @cmd, @$argv;
+	push @cmd, @$objs if (@$objs);
+	push @cmd, "-L$ltdir", @libflags if (@libflags);
+	push @cmd, @$RPdirs if (@$RPdirs);
+	push @cmd, "-Wl,-retain-symbols-file,$symbolsfile" if ($symbolsfile);
+	Exec->command(@cmd);
+}
+
 package main;
 
 use constant {
@@ -379,7 +521,7 @@ my $machine_arch = 'amd64';
 my @valid_modes = qw(clean compile execute finish install link uninstall);
 my @valid_src = qw(asm c cc cpp cxx f s);
 my $cwd = getcwd();
-my $ltdir = '.libs';
+our $ltdir = '.libs';
 our @picflags = ('-fPIC', '-DPIC');
 my $sharedflag = '-shared';
 my $instlibdir = '/usr/local/lib';
@@ -398,7 +540,7 @@ my @tags;		# list of --tag options passed to libtool
 my $deplibs = [];	# list of dependent libraries (both -L and -l flags)
 my $libs = {};		# libraries
 my $libstofind = {};
-my $orderedlibs = [];	# ordered library keys (may contain duplicates)
+#my $orderedlibs = [];	# ordered library keys (may contain duplicates)
 my $dirs = {};		# paths to find libraries
 
 # just to be clear:
@@ -591,7 +733,7 @@ if ($mode eq 'compile') {
 			foreach my $n (@libnames) {
 				$tosymlink->{$n} = $sharedlib if ($n ne $sharedlib);
 			}
-		} elsif (-f "$srcdir/$ltdir/$srcfile" && is_prog_wrapper($s)) {
+		} elsif (-f "$srcdir/$ltdir/$srcfile" && Program::is_wrapper($s)) {
 			$toinstall->{"$srcdir/$ltdir/$srcfile"} = $dst;
 		} else {
 			$toinstall->{$s} = $dst;
@@ -670,7 +812,8 @@ if ($mode eq 'compile') {
 	}
 	Trace::debug {"linkmode: $linkmode\n"};
 
-	my $args = parse_linkargs_list(\@ARGV, 1);
+	my $orderedlibs = [];
+	my $args = parse_linkargs_list(\@ARGV, 1, $orderedlibs);
 	@ARGV = @$args;
 	Trace::debug {"deplibs = @$deplibs\n"};
 
@@ -693,6 +836,7 @@ if ($mode eq 'compile') {
 	Trace::debug {"sobjs = @sobjs\n"};
 
 	if ($linkmode == PROGRAM) {
+		my $program = Program->new;
 		# XXX give higher priority to dirs of not installed libs
 		# XXX no static linking yet here
 		if ($opts{'export-dynamic'}) {
@@ -708,8 +852,10 @@ if ($mode eq 'compile') {
 				Trace::debug {"hoping for real objects in ARGV...\n"};
 			}
 		}
-		do_link($ofile, $ofile, $odir, PROGRAM, 1, $objlist);
-		write_prog_wrapper($outfile);
+		my $RPdirs = [];
+		@$RPdirs = (@Ropts, @RPopts, @Rresolved);
+		$program->link($ltprog, $ofile, $ofile, $odir, 1, $objlist, $libs, $libstofind, \%opts, $RPdirs);
+		$program->write_wrapper($outfile);
 		chmod 0755, $outfile;
 	} elsif ($linkmode == LIBRARY) {
 		(my $libname = $ofile) =~ s/\.la$//;	# remove extension
@@ -881,46 +1027,6 @@ sub create_symlinks
 			symlink abs_path($f), "$dir/$libfile" or die "cannot create symlink: $!\n";
 		}
 	}
-}
-
-# write a wrapper script for an executable so it can be executed within
-# the build directory
-sub write_prog_wrapper
-{
-	my $program = shift;
-
-	open(my $pw, '>', $program) or die "cannot write $program: $!\n";
-	print $pw <<EOF
-#!/bin/sh
-
-# $program - wrapper for $ltdir/$program
-# Generated by libtool $version
-
-argdir=`dirname \$0`
-if test -f "\$argdir/$ltdir/$program"; then
-    # Add our own library path to LD_LIBRARY_PATH
-    LD_LIBRARY_PATH=\$argdir/$ltdir
-    export LD_LIBRARY_PATH
-
-    # Run the actual program with our arguments.
-    exec "\$argdir/$ltdir/$program" \${1+"\$\@"}
-
-    echo "\$0: cannot exec $program \${1+"\$\@"}"
-    exit 1
-else
-    echo "\$0: error: \\\`\$argdir/$ltdir/$program' does not exist." 1>&2
-    exit 1
-fi
-EOF
-;
-}
-
-sub is_prog_wrapper
-{
-	my $program = shift;
-
-	open(my $pw, '<', $program) or die "cannot open $program: $!\n";
-	return eval(grep { m/wrapper\sfor/ } <$pw>);
 }
 
 sub internal_resolve_la
@@ -1117,7 +1223,7 @@ sub internal_parse_linkargs
 
 sub parse_linkargs_list
 {
-	my ($args, $la) = @_;
+	my ($args, $la, $orderedlibs) = @_;
 
 	my $result = [];
 	internal_parse_linkargs($result, $deplibs, \@Rresolved, \@libsearchdirs, $orderedlibs, $dirs, $libs,
@@ -1249,8 +1355,8 @@ sub do_link
 	Trace::debug {"argvstring (pre resolve_la): @ARGV\n"};
 	my $argv = resolve_la_list(\@ARGV);
 	Trace::debug {"argvstring (post resolve_la): @$argv\n"};
-	$orderedlibs = [];
-	$argv = parse_linkargs_list($argv, 0);
+	my $orderedlibs = [];
+	$argv = parse_linkargs_list($argv, 0, $orderedlibs);
 	Trace::debug {"deplibs = @$deplibs\n"};
 	Trace::debug {"orderedlibs = @$orderedlibs\n"};
 	my $finalorderedlibs = reverse_zap_duplicates_ref($orderedlibs);
@@ -1283,13 +1389,10 @@ sub do_link
 			Exec->command(@cmd);
 			Exec->command('ranlib', $dst);
 			return;
-		} elsif ($lmode == PROGRAM) {
-			die "static linking of programs not supported yet\n";
 		}
 	}
 
 	# dynamic linking
-	my $RPdirs = [];
 	my $symbolsfile;
 	if ($opts{'export-symbols'}) {
 		$symbolsfile = $opts{'export-symbols'};
@@ -1297,11 +1400,6 @@ sub do_link
 		$symbolsfile = "$odir/$ltdir/$la";
 		$symbolsfile =~ s/\.la$/.exp/;
 		get_symbollist($symbolsfile, $opts{'export-symbols-regex'}, $objs);
-	}
-	if ($lmode == PROGRAM) {
-		@$RPdirs = (@Ropts, @RPopts, @Rresolved);
-		$RPdirs = reverse_zap_duplicates_ref($RPdirs);
-		map { $_ = "-Wl,-rpath,$_" } @$RPdirs;
 	}
 	foreach my $l (keys %$libstofind) {
 		my $libpath = find_lib($l);
@@ -1359,7 +1457,6 @@ sub do_link
 	push @cmd, @$argv;
 	push @cmd, @$objs if (@$objs);
 	push @cmd, "-L$ltdir", @libflags if (@libflags);
-	push @cmd, @$RPdirs if (@$RPdirs);
 	push @cmd, "-Wl,-retain-symbols-file,$symbolsfile" if ($symbolsfile);
 	Exec->command(@cmd);
 }
