Update to 1.9.26.  This fixes numerous bugs (security and otherwise) since version 1.9.19 as mentioned by the developer on ports@.
Also brought the port itself up to date and added myself as maintainer.

ok pvalchev@ naddy@

diff --git a/news/leafnode/pkg/INSTALL b/news/leafnode/pkg/INSTALL
--- a/news/leafnode/pkg/INSTALL
+++ b/news/leafnode/pkg/INSTALL
@@ -1,8 +1,26 @@
-#! /bin/sh
-# $OpenBSD: INSTALL,v 1.3 2001/03/07 06:33:32 fgsch Exp $
+#!/bin/sh
 #
-# Pre/post-installation setup of leafnode - based on majordomo INSTALL
-# script from daniel@reichardt.ch
+# $OpenBSD: INSTALL,v 1.4 2002/09/24 00:24:19 marcm Exp $
+
+P_NAME=leafnode
+
+DIRS='
+.
+'
+
+FILES='
+config
+'
+
+SPOOLDIR=/var/spool/news
+SPOOL_DIRS='
+leaf.node
+failed.postings
+interesting.groups
+out.going
+message.id
+temp.files
+'
 
 set -e
 PATH=/bin:/usr/bin:/sbin:/usr/sbin
@@ -10,84 +28,115 @@ PREFIX=${PKG_PREFIX:-/usr/local}
 
 do_create_user()
 {
-  echo "Leafnode requires a user news to run properly."
-  echo -n "Let's see if there already is a user news... "
-  if id -u news >/dev/null 2>/dev/null
-  then
-    echo "yes"
-  else
-    echo "no"
-    user add -d /var/spool/news -g news -c 'NNTP server' -s /sbin/nologin news
-  fi
+	if id -u news >/dev/null 2>/dev/null
+	then
+		echo "User news already exists... ok"
+	else
+		echo -n "Adding user news..."
+		user add -d /var/spool/news -g news -c 'NNTP server' -s /sbin/nologin news
+		echo "ok"
+	fi
 }
 
-do_create_local_dirs()
+do_create_spool_dirs()
 {
-  echo -n "Creating local directories... "
-  if [ ! -d /var/spool/news ]; then
-    install -d -o news -g news -m 2775 /var/spool/news
-    install -d -o news -g news /var/spool/news/leaf.node
-    install -d -o news -g news /var/spool/news/failed.postings
-    install -d -o news -g news /var/spool/news/message.id
-    install -d -o news -g news /var/spool/news/interesting.groups
-    install -d -o news -g news /var/spool/news/out.going
-    cd /var/spool/news/message.id; for a in 0 1 2 3 4 5 6 7 8 9; do
-      for b in 0 1 2 3 4 5 6 7 8 9; do
-        for c in 0 1 2 3 4 5 6 7 8 9; do
-          install -d -o news -g news $a$b$c
-    done; done; done
-  fi
-  echo "ok"
+	echo -n "Creating spool directories... "
+	for d in ${SPOOL_DIRS}; do
+		if [ ! -d "${SPOOLDIR}/$d" ]; then
+			install -d -o news -g news ${SPOOLDIR}/$d
+		fi
+	done
+
+	cd ${SPOOLDIR}/message.id
+	for a in 0 1 2 3 4 5 6 7 8 9; do
+		for b in 0 1 2 3 4 5 6 7 8 9; do
+			for c in 0 1 2 3 4 5 6 7 8 9; do
+				install -d -o news -g news $a$b$c
+			done
+		done
+	done
+	echo "ok"
 }
 
-do_set_file_permissions()
+do_post()
 {
-  echo -n "Changing ownership of leafnode files... "
-  chown news:news ${PREFIX}/bin/newsq
-  chown news:news ${PREFIX}/sbin/applyfilter
-  chown news:news ${PREFIX}/sbin/checkgroups
-  chown news:news ${PREFIX}/sbin/fetchnews
-  chown news:news ${PREFIX}/sbin/leafnode
-  chown news:news ${PREFIX}/sbin/texpire
-  echo "ok"
+	DEST_PFX=${SYSCONFDIR}
+	SOURCE_PFX=${PREFIX}/share/examples/${P_NAME}
+
+	echo 
+	echo "+--------------- ${P_NAME}"
+
+	# install dirs if neccessary
+	for d in ${DIRS}; do
+		if [ ! -d "${DEST_PFX}/$d" ]; then
+			install -d ${DEST_PFX}/$d
+		fi
+	done
+
+	# install or take note of existing config files
+	for f in ${FILES}; do
+		if [ -f "${DEST_PFX}/$f" ]; then
+			OLD_CONFS="${OLD_CONFS} $f"
+		else
+			if ! install -m 644 ${SOURCE_PFX}/$f ${DEST_PFX}/$f; then
+				echo "| ERROR: The following file could not be installed, exiting: ${DEST_PFX}/$f"
+				exit 1
+			fi
+			NEW_CONFS="${NEW_CONFS} $f"
+		fi
+	done
+
+	# print status report
+	if [ -n "${NEW_CONFS}" ]; then
+		echo "| The following NEW configuration files have been installed:"
+		echo "|"
+		for f in ${NEW_CONFS}; do
+			echo "| ${DEST_PFX}/$f"
+		done 
+	fi
+	
+	if [ -n "${OLD_CONFS}" ]; then
+		if [ -n "${NEW_CONFS}" ]; then
+			echo "|"
+		fi
+		echo "| The following OLD configuration files were found and have NOT been"
+		echo "| overwritten:"
+		echo "|"
+		for f in ${OLD_CONFS}; do
+			echo "| ${DEST_PFX}/$f"
+		done
+		echo "|"
+		echo "| You should however manually compare them to their equivalents in"
+		echo "|"
+		echo "| ${SOURCE_PFX}"
+		echo "|"
+		echo "| and update your configuration as needed." 
+	fi
+	echo "+--------------- ${P_NAME}"
+	echo 
 }
 
-do_install_configuration()
-{
-  echo -n "Let's see if there is already a configuration file... "
-  if [ -d /etc/leafnode -a -f /etc/leafnode/config ]; then
-    echo "yes"
-    echo "Please compare your existing configuration with"
-    echo "${PREFIX}/share/doc/config.example"
-  else
-    echo "no"
-    echo -n "Copying sample configuration file... "
-    install -d -o news -g news /etc/leafnode
-    install -o root -g news -m 640 \
-      ${PREFIX}/share/doc/leafnode/config.example /etc/leafnode/config
-    echo "ok"
-    echo "Please review new configuration /etc/leafnode/config"
-  fi
-}
-
+# verify proper execution
+#
 if [ $# -ne 2 ]; then
-    echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
-    exit 1
-fi
-
-case $2 in
-    PRE-INSTALL)
-	do_create_user
-	;;
-    POST-INSTALL)
-	do_create_local_dirs
-	do_set_file_permissions
-	do_install_configuration
-	;;
-    *)
 	echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
 	exit 1
-	;;
+fi
+
+# Verify/process the command
+#
+case $2 in
+	PRE-INSTALL)
+		do_create_user
+		;;
+	POST-INSTALL)
+		do_create_spool_dirs
+		do_post
+		;;
+	*)
+		echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
+		exit 1
+		;;
 esac
 
 exit 0
