SECURITY update to password-store-1.7.2.
This release fixes CVE-2018-12356:
https://lists.zx2c4.com/pipermail/password-store/2018-June/003309.html

From David Dahlberg (MAINTAINER). Thanks!

diff --git a/security/password-store/patches/patch-src_password-store_sh b/security/password-store/patches/patch-src_password-store_sh
--- a/security/password-store/patches/patch-src_password-store_sh
+++ b/security/password-store/patches/patch-src_password-store_sh
@@ -1,4 +1,4 @@
-$OpenBSD: patch-src_password-store_sh,v 1.3 2017/06/28 13:16:49 ajacoutot Exp $
+$OpenBSD: patch-src_password-store_sh,v 1.4 2018/06/19 09:39:18 bentley Exp $
 Index: src/password-store.sh
 --- src/password-store.sh.orig
 +++ src/password-store.sh
@@ -11,7 +11,7 @@ Index: src/password-store.sh
  		printf "%s\n" "$@" > "$gpg_id"
  		local id_print="$(printf "%s, " "$@")"
  		echo "Password store initialized for ${id_print%, }${id_path:+ ($id_path)}"
-@@ -379,7 +379,10 @@ cmd_show() {
+@@ -381,7 +381,10 @@ cmd_show() {
  		else
  			echo "${path%\/}"
  		fi
@@ -23,7 +23,7 @@ Index: src/password-store.sh
  	elif [[ -z $path ]]; then
  		die "Error: password store is empty. Try \"pass init\"."
  	else
-@@ -391,14 +394,16 @@ cmd_find() {
+@@ -393,14 +396,16 @@ cmd_find() {
  	[[ $# -eq 0 ]] && die "Usage: $PROGRAM $COMMAND pass-names..."
  	IFS="," eval 'echo "Search Terms: $*"'
  	local terms="*$(printf '%s*|*' "$@")"
@@ -34,42 +34,42 @@ Index: src/password-store.sh
  }
  
  cmd_grep() {
- 	[[ $# -ne 1 ]] && die "Usage: $PROGRAM $COMMAND search-string"
- 	local search="$1" passfile grepresults
+ 	[[ $# -lt 1 ]] && die "Usage: $PROGRAM $COMMAND [GREPOPTIONS] search-string"
+ 	local passfile grepresults
  	while read -r -d "" passfile; do
--		grepresults="$($GPG -d "${GPG_OPTS[@]}" "$passfile" | grep --color=always "$search")"
-+		grepresults="$($GPG -d "${GPG_OPTS[@]}" "$passfile" | grep "$search")"
+-		grepresults="$($GPG -d "${GPG_OPTS[@]}" "$passfile" | grep --color=always "$@")"
++		grepresults="$($GPG -d "${GPG_OPTS[@]}" "$passfile" | grep "$@")"
  		[[ $? -ne 0 ]] && continue
  		passfile="${passfile%.gpg}"
  		passfile="${passfile#$PREFIX/}"
-@@ -430,7 +435,7 @@ cmd_insert() {
+@@ -432,7 +437,7 @@ cmd_insert() {
  
  	[[ $force -eq 0 && -e $passfile ]] && yesno "An entry already exists for $path. Overwrite it?"
  
--	mkdir -p -v "$PREFIX/$(dirname "$path")"
-+	mkdir -p "$PREFIX/$(dirname "$path")"
- 	set_gpg_recipients "$(dirname "$path")"
+-	mkdir -p -v "$PREFIX/$(dirname -- "$path")"
++	mkdir -p "$PREFIX/$(dirname -- "$path")"
+ 	set_gpg_recipients "$(dirname -- "$path")"
  
  	if [[ $multiline -eq 1 ]]; then
-@@ -464,7 +469,7 @@ cmd_edit() {
+@@ -466,7 +471,7 @@ cmd_edit() {
  
  	local path="${1%/}"
  	check_sneaky_paths "$path"
--	mkdir -p -v "$PREFIX/$(dirname "$path")"
-+	mkdir -p "$PREFIX/$(dirname "$path")"
- 	set_gpg_recipients "$(dirname "$path")"
+-	mkdir -p -v "$PREFIX/$(dirname -- "$path")"
++	mkdir -p "$PREFIX/$(dirname -- "$path")"
+ 	set_gpg_recipients "$(dirname -- "$path")"
  	local passfile="$PREFIX/$path.gpg"
  	set_git "$passfile"
-@@ -506,7 +511,7 @@ cmd_generate() {
- 	local length="${2:-$GENERATED_LENGTH}"
+@@ -509,7 +514,7 @@ cmd_generate() {
  	check_sneaky_paths "$path"
- 	[[ ! $length =~ ^[0-9]+$ ]] && die "Error: pass-length \"$length\" must be a number."
--	mkdir -p -v "$PREFIX/$(dirname "$path")"
-+	mkdir -p "$PREFIX/$(dirname "$path")"
- 	set_gpg_recipients "$(dirname "$path")"
+ 	[[ $length =~ ^[0-9]+$ ]] || die "Error: pass-length \"$length\" must be a number."
+ 	[[ $length -gt 0 ]] || die "Error: pass-length must be greater than zero."
+-	mkdir -p -v "$PREFIX/$(dirname -- "$path")"
++	mkdir -p "$PREFIX/$(dirname -- "$path")"
+ 	set_gpg_recipients "$(dirname -- "$path")"
  	local passfile="$PREFIX/$path.gpg"
  	set_git "$passfile"
-@@ -595,7 +600,7 @@ cmd_copy_move() {
+@@ -598,7 +603,7 @@ cmd_copy_move() {
  	echo "$old_path"
  	[[ -e $old_path ]] || die "Error: $1 is not in the password store."
  
@@ -78,21 +78,3 @@ Index: src/password-store.sh
  	[[ -d $old_path || -d $new_path || $new_path == */ ]] || new_path="${new_path}.gpg"
  
  	local interactive="-i"
-@@ -603,7 +608,7 @@ cmd_copy_move() {
- 
- 	set_git "$new_path"
- 	if [[ $move -eq 1 ]]; then
--		mv $interactive -v "$old_path" "$new_path" || exit 1
-+		mv $interactive "$old_path" "$new_path" || exit 1
- 		[[ -e "$new_path" ]] && reencrypt_path "$new_path"
- 
- 		set_git "$new_path"
-@@ -620,7 +625,7 @@ cmd_copy_move() {
- 		fi
- 		rmdir -p "$old_dir" 2>/dev/null
- 	else
--		cp $interactive -r -v "$old_path" "$new_path" || exit 1
-+		cp $interactive -r "$old_path" "$new_path" || exit 1
- 		[[ -e "$new_path" ]] && reencrypt_path "$new_path"
- 		git_add_file "$new_path" "Copy ${1} to ${2}."
- 	fi
