Update to password-store-1.7.
From David Dalhlberg (maintainer). Thanks!

diff --git a/security/password-store/patches/patch-src_password-store_sh b/security/password-store/patches/patch-src_password-store_sh
--- a/security/password-store/patches/patch-src_password-store_sh
+++ b/security/password-store/patches/patch-src_password-store_sh
@@ -1,15 +1,15 @@
-$OpenBSD: patch-src_password-store_sh,v 1.1.1.1 2016/01/21 10:52:57 bentley Exp $
---- src/password-store.sh.orig	Wed Jan 28 17:43:02 2015
-+++ src/password-store.sh	Mon Dec 28 13:07:08 2015
-@@ -275,14 +275,14 @@ cmd_init() {
+$OpenBSD: patch-src_password-store_sh,v 1.2 2017/03/07 08:53:17 bentley Exp $
+--- src/password-store.sh.orig	Sun Feb 26 18:52:16 2017
++++ src/password-store.sh	Tue Feb 28 14:17:12 2017
+@@ -316,14 +316,14 @@ cmd_init() {
  
  	if [[ $# -eq 1 && -z $1 ]]; then
  		[[ ! -f "$gpg_id" ]] && die "Error: $gpg_id does not exist and so cannot be removed."
 -		rm -v -f "$gpg_id" || exit 1
 +		rm -f "$gpg_id" || exit 1
- 		if [[ -d $GIT_DIR ]]; then
- 			git rm -qr "$gpg_id"
- 			git_commit "Deinitialize ${gpg_id}."
+ 		if [[ -n $INNER_GIT_DIR ]]; then
+ 			git -C "$INNER_GIT_DIR" rm -qr "$gpg_id"
+ 			git_commit "Deinitialize ${gpg_id}${id_path:+ ($id_path)}."
  		fi
  		rmdir -p "${gpg_id%/*}" 2>/dev/null
  	else
@@ -17,29 +17,27 @@ $OpenBSD: patch-src_password-store_sh,v 1.1.1.1 2016/01/21 10:52:57 bentley Exp 
 +		mkdir -p "$PREFIX/$id_path"
  		printf "%s\n" "$@" > "$gpg_id"
  		local id_print="$(printf "%s, " "$@")"
- 		echo "Password store initialized for ${id_print%, }"
-@@ -322,7 +322,11 @@ cmd_show() {
+ 		echo "Password store initialized for ${id_print%, }${id_path:+ ($id_path)}"
+@@ -379,7 +379,10 @@ cmd_show() {
  		else
  			echo "${path%\/}"
  		fi
--		tree -C -l --noreport "$PREFIX/$path" | tail -n +2 | sed 's/\.gpg\(\x1B\[[0-9]\+m\)\{0,1\}\( ->\|$\)/\1\2/g' # remove .gpg at end of line, but keep colors
+-		tree -C -l --noreport "$PREFIX/$path" | tail -n +2 | sed -E 's/\.gpg(\x1B\[[0-9]+m)?( ->|$)/\1\2/g' # remove .gpg at end of line, but keep colors
 +		# remove .gpg at end of line, but keep colors
 +		colortree -C -l --noreport "$PREFIX/$path" \
 +			| tail -n +2 \
-+			| sed -e 's/\.gpg\(\x1B\[[0-9]\+m\)\{0,1\}\( ->\)/\1\2/g' \
-+				-e 's/\.gpg\(\x1B\[[0-9]\+m\)\{0,1\}\($\)/\1\2/g'
++			| sed -E 's/\.gpg(\x1B\[[0-9]+m)?( ->|$)/\1\2/g'
  	elif [[ -z $path ]]; then
  		die "Error: password store is empty. Try \"pass init\"."
  	else
-@@ -334,14 +338,17 @@ cmd_find() {
- 	[[ -z "$@" ]] && die "Usage: $PROGRAM $COMMAND pass-names..."
+@@ -391,14 +394,16 @@ cmd_find() {
+ 	[[ $# -eq 0 ]] && die "Usage: $PROGRAM $COMMAND pass-names..."
  	IFS="," eval 'echo "Search Terms: $*"'
  	local terms="*$(printf '%s*|*' "$@")"
--	tree -C -l --noreport -P "${terms%|*}" --prune --matchdirs --ignore-case "$PREFIX" | tail -n +2 | sed 's/\.gpg\(\x1B\[[0-9]\+m\)\{0,1\}\( ->\|$\)/\1\2/g'
+-	tree -C -l --noreport -P "${terms%|*}" --prune --matchdirs --ignore-case "$PREFIX" | tail -n +2 | sed -E 's/\.gpg(\x1B\[[0-9]+m)?( ->|$)/\1\2/g'
 +	colortree -C -l --noreport -P "${terms%|*}" --prune --matchdirs --ignore-case "$PREFIX" \
 +		| tail -n +2 \
-+		| sed -e 's/\.gpg\(\x1B\[[0-9]\+m\)\{0,1\}\( ->\)/\1\2/g' \
-+			-e 's/\.gpg\(\x1B\[[0-9]\+m\)\{0,1\}\($\)/\1\2/g'
++		| sed -E 's/\.gpg(\x1B\[[0-9]+m)?( ->|$)/\1\2/g'
  }
  
  cmd_grep() {
@@ -48,10 +46,10 @@ $OpenBSD: patch-src_password-store_sh,v 1.1.1.1 2016/01/21 10:52:57 bentley Exp 
  	while read -r -d "" passfile; do
 -		grepresults="$($GPG -d "${GPG_OPTS[@]}" "$passfile" | grep --color=always "$search")"
 +		grepresults="$($GPG -d "${GPG_OPTS[@]}" "$passfile" | grep "$search")"
- 		[ $? -ne 0 ] && continue
+ 		[[ $? -ne 0 ]] && continue
  		passfile="${passfile%.gpg}"
  		passfile="${passfile#$PREFIX/}"
-@@ -372,7 +379,7 @@ cmd_insert() {
+@@ -430,7 +435,7 @@ cmd_insert() {
  
  	[[ $force -eq 0 && -e $passfile ]] && yesno "An entry already exists for $path. Overwrite it?"
  
@@ -60,57 +58,52 @@ $OpenBSD: patch-src_password-store_sh,v 1.1.1.1 2016/01/21 10:52:57 bentley Exp 
  	set_gpg_recipients "$(dirname "$path")"
  
  	if [[ $multiline -eq 1 ]]; then
-@@ -406,12 +413,12 @@ cmd_edit() {
+@@ -464,7 +469,7 @@ cmd_edit() {
  
- 	local path="$1"
+ 	local path="${1%/}"
  	check_sneaky_paths "$path"
 -	mkdir -p -v "$PREFIX/$(dirname "$path")"
 +	mkdir -p "$PREFIX/$(dirname "$path")"
  	set_gpg_recipients "$(dirname "$path")"
  	local passfile="$PREFIX/$path.gpg"
- 
- 	tmpdir #Defines $SECURE_TMPDIR
--	local tmp_file="$(mktemp -u "$SECURE_TMPDIR/XXXXX")-${path//\//-}.txt"
-+	local tmp_file="$(mktemp -u "$SECURE_TMPDIR/XXXXXX")-${path//\//-}.txt"
- 
- 
- 	local action="Add"
-@@ -446,7 +453,7 @@ cmd_generate() {
- 	local length="$2"
+ 	set_git "$passfile"
+@@ -506,7 +511,7 @@ cmd_generate() {
+ 	local length="${2:-$GENERATED_LENGTH}"
  	check_sneaky_paths "$path"
  	[[ ! $length =~ ^[0-9]+$ ]] && die "Error: pass-length \"$length\" must be a number."
 -	mkdir -p -v "$PREFIX/$(dirname "$path")"
 +	mkdir -p "$PREFIX/$(dirname "$path")"
  	set_gpg_recipients "$(dirname "$path")"
  	local passfile="$PREFIX/$path.gpg"
- 
-@@ -498,7 +505,7 @@ cmd_delete() {
+ 	set_git "$passfile"
+@@ -561,7 +566,7 @@ cmd_delete() {
  
  	[[ $force -eq 1 ]] || yesno "Are you sure you would like to delete $path?"
  
 -	rm $recursive -f -v "$passfile"
 +	rm $recursive -f "$passfile"
- 	if [[ -d $GIT_DIR && ! -e $passfile ]]; then
- 		git rm -qr "$passfile"
- 		git_commit "Remove $path from store."
-@@ -529,14 +536,14 @@ cmd_copy_move() {
- 		[[ ! -f $old_path ]] && die "Error: $1 is not in the password store."
- 	fi
+ 	set_git "$passfile"
+ 	if [[ -n $INNER_GIT_DIR && ! -e $passfile ]]; then
+ 		git -C "$INNER_GIT_DIR" rm -qr "$passfile"
+@@ -595,7 +600,7 @@ cmd_copy_move() {
+ 	echo "$old_path"
+ 	[[ -e $old_path ]] || die "Error: $1 is not in the password store."
  
 -	mkdir -p -v "${new_path%/*}"
 +	mkdir -p "${new_path%/*}"
- 	[[ -d $old_path || -d $new_path || $new_path =~ /$ ]] || new_path="${new_path}.gpg"
+ 	[[ -d $old_path || -d $new_path || $new_path == */ ]] || new_path="${new_path}.gpg"
  
  	local interactive="-i"
- 	[[ ! -t 0 || $force -eq 1 ]] && interactive="-f"
+@@ -603,7 +608,7 @@ cmd_copy_move() {
  
+ 	set_git "$new_path"
  	if [[ $move -eq 1 ]]; then
 -		mv $interactive -v "$old_path" "$new_path" || exit 1
 +		mv $interactive "$old_path" "$new_path" || exit 1
  		[[ -e "$new_path" ]] && reencrypt_path "$new_path"
  
- 		if [[ -d $GIT_DIR && ! -e $old_path ]]; then
-@@ -545,7 +552,7 @@ cmd_copy_move() {
+ 		set_git "$new_path"
+@@ -620,7 +625,7 @@ cmd_copy_move() {
  		fi
  		rmdir -p "$old_dir" 2>/dev/null
  	else
