update to subversion snapshot from 2008-06-20.
added since last update:

- AVM2 (Flash 9) SWF muxer
- QT variant of IMA ADPCM encoder
- VFW grabber
- Ipod/Iphone compatible mp4 muxer
- Mimic decoder
- MSN TCP Webcam stream demuxer
- RL2 demuxer / decoder
- IFF demuxer
- 8SVX audio decoder
- BFI demuxer
- MAXIS EA XA (.xa) demuxer / decoder
- BFI video decoder
- OMA demuxer

also:
* headers have been moved to library specific subdirectories instead
  of all under ffmpeg.
* libswscale is now enabled in the build.


feedback/ok brad@

diff --git a/graphics/ffmpeg/patches/patch-configure b/graphics/ffmpeg/patches/patch-configure
--- a/graphics/ffmpeg/patches/patch-configure
+++ b/graphics/ffmpeg/patches/patch-configure
@@ -1,7 +1,101 @@
-$OpenBSD: patch-configure,v 1.18 2008/01/26 01:56:02 jakemsr Exp $
---- configure.orig	Fri Jan 18 01:21:47 2008
-+++ configure	Sun Jan 20 00:36:03 2008
-@@ -1785,7 +1785,7 @@ enabled extra_warnings && check_cflags -Winline
+$OpenBSD: patch-configure,v 1.19 2008/07/09 01:57:44 jakemsr Exp $
+--- configure.orig	Fri Jun 20 19:40:11 2008
++++ configure	Sat Jul  5 03:08:34 2008
+@@ -953,9 +953,9 @@ enable stripping
+ vhook="default"
+ 
+ # build settings
+-SHFLAGS='-shared -Wl,-soname,$$(@F)'
++SHFLAGS='-shared'
+ VHOOKSHFLAGS='$(SHFLAGS)'
+-LDLATEFLAGS='-Wl,-rpath-link,\$(BUILD_ROOT)/libpostproc -Wl,-rpath-link,\$(BUILD_ROOT)/libswscale -Wl,-rpath-link,\$(BUILD_ROOT)/libavfilter -Wl,-rpath-link,\$(BUILD_ROOT)/libavdevice -Wl,-rpath-link,\$(BUILD_ROOT)/libavformat -Wl,-rpath-link,\$(BUILD_ROOT)/libavcodec -Wl,-rpath-link,\$(BUILD_ROOT)/libavutil'
++LDLATEFLAGS=''
+ FFSERVERLDFLAGS=-Wl,-E
+ LIBPREF="lib"
+ LIBSUF=".a"
+@@ -965,7 +965,7 @@ SLIBPREF="lib"
+ SLIBSUF=".so"
+ SLIBNAME='$(SLIBPREF)$(FULLNAME)$(SLIBSUF)'
+ SLIBNAME_WITH_VERSION='$(SLIBNAME).$(LIBVERSION)'
+-SLIBNAME_WITH_MAJOR='$(SLIBNAME).$(LIBMAJOR)'
++SLIBNAME_WITH_MAJOR='$(SLIBNAME).$(LIBVERSION)'
+ LIB_INSTALL_EXTRA_CMD='$(RANLIB) "$(LIBDIR)/$(LIBNAME)"'
+ 
+ # gcc stupidly only outputs the basename of targets with -MM
+@@ -1213,9 +1213,9 @@ case $target_os in
+         disable need_memalign
+         LIBOBJFLAGS='$(PIC)'
+         SHFLAGS='-shared'
+-        SLIBNAME='$(SLIBPREF)$(FULLNAME)$(SLIBSUF).$(LIBVERSION)'
+-        SLIBNAME_WITH_VERSION='$(SLIBNAME)'
+-        SLIBNAME_WITH_MAJOR='$(SLIBNAME)'
++        #SLIBNAME='$(SLIBPREF)$(FULLNAME)$(SLIBSUF).$(LIBVERSION)'
++        #SLIBNAME_WITH_VERSION='$(SLIBNAME)'
++        #SLIBNAME_WITH_MAJOR='$(SLIBNAME)'
+         oss_demuxer_extralibs="-lossaudio"
+         oss_muxer_extralibs="-lossaudio"
+         ;;
+@@ -1501,7 +1501,7 @@ fi
+ check_cc <<EOF || die "Symbol mangling check failed."
+ int ff_extern;
+ EOF
+-sym=$($nm -P -g $TMPO | grep ff_extern)
++sym=$($nm -g $TMPO | grep ff_extern | cut -d ' ' -f 3)
+ extern_prefix=${sym%%ff_extern*}
+ 
+ check_asm inline_asm '""'
+@@ -1582,10 +1582,14 @@ enabled vis && add_cflags "-mcpu=ultrasparc -mtune=ult
+ 
+ # ---
+ # big/little-endian test
+-check_cc <<EOF || die "endian test failed"
+-unsigned int endian = 'B' << 24 | 'I' << 16 | 'G' << 8 | 'E';
++check_exec <<EOF || enable bigendian
++#include <sys/types.h>
++int main(void) {
++	if (_BYTE_ORDER == _BIG_ENDIAN)
++		return 1;
++	return 0;
++}
+ EOF
+-od -A n -t x1 $TMPO | grep -q '42 *49 *47 *45' && enable bigendian
+ 
+ # ---
+ # check availability of some header files
+@@ -1607,7 +1611,7 @@ check_func2 windows.h GetProcessTimes
+ check_header byteswap.h
+ check_header conio.h
+ check_header dlfcn.h
+-check_header malloc.h
++#check_header malloc.h
+ check_header sys/mman.h
+ check_header sys/resource.h
+ check_header termios.h
+@@ -1717,10 +1721,10 @@ if test "$target_os" = cygwin -o "$target_os" = mingw3
+     echo
+ fi
+ 
+-if enabled vhook; then
+-    check_ldflags -rdynamic
+-    check_ldflags -export-dynamic
+-fi
++#if enabled vhook; then
++#    check_ldflags -rdynamic
++#    check_ldflags -export-dynamic
++#fi
+ 
+ check_foo_config imlib2 imlib2 Imlib2.h imlib_load_font
+ check_foo_config freetype2 freetype ft2build.h FT_Init_FreeType
+@@ -1756,7 +1760,7 @@ fi
+ 
+ texi2html -version > /dev/null 2>&1 && enable texi2html || disable texi2html
+ 
+-check_type sys/socket.h socklen_t
++check_type sys/types.h socklen_t
+ 
+ ##########################################
+ # Network check
+@@ -1831,7 +1835,7 @@ enabled extra_warnings && check_cflags -Winline
  # add some linker flags
  check_ldflags -Wl,--warn-common
  check_ldflags $LDLATEFLAGS
@@ -10,43 +104,38 @@ $OpenBSD: patch-configure,v 1.18 2008/01/26 01:56:02 jakemsr Exp $
  
  if enabled small; then
      check_cflags -Os            # not all compilers support -Os
-@@ -2158,28 +2158,28 @@ Cflags: -I\${includedir}
+@@ -2204,8 +2208,7 @@ Version: $version
+ Requires: $(disabled shared && echo $requires)
+ Requires.private: $(enabled shared && echo $requires)
+ Conflicts:
+-Libs: -L\${libdir} -l${shortname} $(disabled shared && echo $libs)
+-Libs.private: $(enabled shared && echo $libs)
++Libs: -L\${libdir} -l${shortname} $libs
+ Cflags: -I\${includedir}
+ EOF
+ cat <<EOF > $name/$name-uninstalled.pc
+@@ -2224,17 +2227,17 @@ Cflags: -I\${includedir}
  EOF
  }
  
--pkgconfig_generate libavutil "FFmpeg utility library" "$lavu_version" -lavutil "" ffmpeg
-+pkgconfig_generate libavutil "FFmpeg utility library" "$lavu_version" "-lavutil $LIBavutil_EXTRALIBS" "" ffmpeg
- pkgconfig_generate_uninstalled libavutil "FFmpeg utility library" "$lavu_version"
- 
--pkgconfig_generate libavcodec "FFmpeg codec library" "$lavc_version" "-lavcodec $extralibs" "$pkg_requires libavutil = $lavu_version" ffmpeg
--pkgconfig_generate_uninstalled libavcodec "FFmpeg codec library" "$lavc_version" "$extralibs" "$pkg_requires libavutil = $lavu_version"
-+pkgconfig_generate libavcodec "FFmpeg codec library" "$lavc_version" "-lavcodec $LIBavcodec_EXTRALIBS" "libavutil = $lavu_version" ffmpeg
-+pkgconfig_generate_uninstalled libavcodec "FFmpeg codec library" "$lavc_version" "-pthread"
- 
--pkgconfig_generate libavformat "FFmpeg container format library" "$lavf_version" "-lavformat $extralibs" "$pkg_requires libavcodec = $lavc_version" ffmpeg
--pkgconfig_generate_uninstalled libavformat "FFmpeg container format library" "$lavf_version" "$extralibs" "$pkg_requires libavcodec = $lavc_version"
-+pkgconfig_generate libavformat "FFmpeg container format library" "$lavf_version" "-lavformat $LIBavformat_EXTRALIBS" "libavutil = $lavu_version libavcodec = $lavc_version" ffmpeg
-+pkgconfig_generate_uninstalled libavformat "FFmpeg container format library" "$lavf_version"
- 
--pkgconfig_generate libavdevice "FFmpeg device handling library" "$lavd_version" "-lavdevice $extralibs" "$pkg_requires libavformat = $lavf_version" ffmpeg
--pkgconfig_generate_uninstalled libavdevice "FFmpeg device handling library" "$lavd_version" "$extralibs" "$pkg_requires libavformat = $lavf_version"
-+pkgconfig_generate libavdevice "FFmpeg device handling library" "$lavd_version" "-lavdevice $LIBavdevice_EXTRALIBS" "libavutil = $lavu_version libavformat = $lavf_version" ffmpeg
-+pkgconfig_generate_uninstalled libavdevice "FFmpeg device handling library" "$lavd_version"
- if enabled pp; then
--    pkgconfig_generate libpostproc "FFmpeg post processing library" "$pp_version" -lpostproc "" postproc
-+    pkgconfig_generate libpostproc "FFmpeg post processing library" "$pp_version" "-lpostproc $LIBpostproc_EXTRALIBS" "libavutil = $lavu_version " postproc
-     pkgconfig_generate_uninstalled libpostproc "FFmpeg post processing library" "$pp_version"
- fi
- 
- if enabled swscaler; then
-     pkgconfig_generate libswscale "FFmpeg image rescaling library" "$sws_version" -lswscale "libavutil = $lavu_version" ffmpeg
--    pkgconfig_generate_uninstalled libswscale "FFmpeg image rescaling library" "$sws_version" "" "libavutil = $lavu_version"
-+    pkgconfig_generate_uninstalled libswscale "FFmpeg image rescaling library" "$sws_version"
+-pkgconfig_generate libavutil "FFmpeg utility library" "$LIBAVUTIL_VERSION"
+-pkgconfig_generate libavcodec "FFmpeg codec library" "$LIBAVCODEC_VERSION" "$extralibs" "$pkg_requires libavutil = $LIBAVUTIL_VERSION"
+-pkgconfig_generate libavformat "FFmpeg container format library" "$LIBAVFORMAT_VERSION" "$extralibs" "$pkg_requires libavcodec = $LIBAVCODEC_VERSION"
+-pkgconfig_generate libavdevice "FFmpeg device handling library" "$LIBAVDEVICE_VERSION" "$extralibs" "$pkg_requires libavformat = $LIBAVFORMAT_VERSION"
++pkgconfig_generate libavutil "FFmpeg utility library" "$LIBAVUTIL_VERSION" "$LIBavutil_EXTRALIBS"
++pkgconfig_generate libavcodec "FFmpeg codec library" "$LIBAVCODEC_VERSION" "$LIBavcodec_EXTRALIBS" "libavutil"
++pkgconfig_generate libavformat "FFmpeg container format library" "$LIBAVFORMAT_VERSION" "$LIBavformat_EXTRALIBS" "libavutil libavcodec"
++pkgconfig_generate libavdevice "FFmpeg device handling library" "$LIBAVDEVICE_VERSION" "$LIBavdevice_EXTRALIBS" "libavutil libavformat"
+ enabled avfilter &&
+     pkgconfig_generate libavfilter "FFmpeg video filtering library" "$LIBAVFILTER_VERSION" "$extralibs" "$pkg_requires libavutil = $LIBAVUTIL_VERSION"
+ enabled postproc &&
+-    pkgconfig_generate libpostproc "FFmpeg post processing library" "$LIBPOSTPROC_VERSION"
++    pkgconfig_generate libpostproc "FFmpeg post processing library" "$LIBPOSTPROC_VERSION" "$LIBpostproc_EXTRALIBS" "libavutil"
+ if enabled swscale; then
+-    pkgconfig_generate libswscale "FFmpeg image rescaling library" "$LIBSWSCALE_VERSION" "" "libavutil = $LIBAVUTIL_VERSION"
++    pkgconfig_generate libswscale "FFmpeg image rescaling library" "$LIBSWSCALE_VERSION" "$LIBswscale_EXTRALIBS" "libavutil"
  else
--    pkgconfig_generate libswscale "FFmpeg image rescaling library" "$sws_version" "" "$pkg_requires libavcodec = $lavc_version" ffmpeg
--    pkgconfig_generate_uninstalled libswscale "FFmpeg image rescaling library" "$sws_version" "" "$pkg_requires libavcodec = $lavc_version"
-+    pkgconfig_generate libswscale "FFmpeg image rescaling library" "$sws_version" "" "libavcodec = $lavc_version" ffmpeg
-+    pkgconfig_generate_uninstalled libswscale "FFmpeg image rescaling library" "$sws_version"
-     apply libswscale.pc sed s/^Libs:.*$/Libs:/
-     apply libswscale-uninstalled.pc sed s/^Libs:.*$/Libs:/
+-    pkgconfig_generate libswscale "FFmpeg image rescaling library" "$LIBSWSCALE_VERSION" "" "$pkg_requires libavcodec = $LIBAVCODEC_VERSION"
++    pkgconfig_generate libswscale "FFmpeg image rescaling library" "$LIBSWSCALE_VERSION" "$LIBswscale_EXTRALIBS"
+     apply libswscale/libswscale.pc sed s/^Libs:.*$/Libs:/
  fi
