update to 1.2.10
tested and ok merdely@, simon@

diff --git a/devel/apr-util/patches/patch-test_Makefile_in b/devel/apr-util/patches/patch-test_Makefile_in
--- a/devel/apr-util/patches/patch-test_Makefile_in
+++ b/devel/apr-util/patches/patch-test_Makefile_in
@@ -1,6 +1,6 @@
-$OpenBSD: patch-test_Makefile_in,v 1.2 2007/03/24 13:45:13 todd Exp $
---- test/Makefile.in.orig	Tue Jun 14 06:03:51 2005
-+++ test/Makefile.in	Fri Feb  9 17:21:57 2007
+$OpenBSD: patch-test_Makefile_in,v 1.3 2007/09/20 10:18:37 steven Exp $
+--- test/Makefile.in.orig	Sat Sep  1 11:45:39 2007
++++ test/Makefile.in	Tue Sep 18 15:12:55 2007
 @@ -8,7 +8,7 @@ TARGETS = $(PROGRAMS)
  
  APRUTIL_DOTTED_VERSION=@APRUTIL_DOTTED_VERSION@
@@ -10,16 +10,16 @@ $OpenBSD: patch-test_Makefile_in,v 1.2 2007/03/24 13:45:13 todd Exp $
  
  CLEAN_TARGETS = manyfile.bin testfile.txt data/sqlite*.db
  
-@@ -21,7 +21,11 @@ all: $(PROGRAMS)
- 
- check: $(PROGRAMS)
- 	for prog in $(PROGRAMS); do \
--		./$$prog ;\
-+		if test $$prog = "testdbm"; then \
-+			./$$prog auto db;  \
-+		else \
-+			./$$prog ;\
-+		fi; \
- 		if test $$? = 255; then \
- 			echo "$$prog failed"; \
- 			break; \
+@@ -30,7 +30,11 @@ check: $(PROGRAMS)
+ 				fi; \
+ 			done; \
+ 	        else \
+-			./$$prog; \
++			if test $$prog = "testdbm"; then \
++				./$$prog auto db;  \
++			else \
++				./$$prog ;\
++			fi; \
+ 			if test $$? = 255; then \
+ 				echo "$$prog failed"; \
+ 				break; \
