OpenBSD does not require -lcrypt, DES encryption is part of the standard libc.

diff --git a/editors/ldapvi/patches/patch-configure b/editors/ldapvi/patches/patch-configure
--- a/editors/ldapvi/patches/patch-configure
+++ b/editors/ldapvi/patches/patch-configure
@@ -1,29 +1,76 @@
-$OpenBSD: patch-configure,v 1.3 2007/06/28 14:39:14 ajacoutot Exp $
---- configure.orig	Thu Jun 28 16:34:08 2007
-+++ configure	Thu Jun 28 16:34:57 2007
-@@ -5032,13 +5032,13 @@ done
+$OpenBSD: patch-configure,v 1.4 2012/01/12 13:59:29 ajacoutot Exp $
+
+OpenBSD does NOT require -lcrypt, DES encryption is part of the standard libc.
+
+--- configure.orig	Sat May  5 12:17:40 2007
++++ configure	Thu Jan 12 14:41:38 2012
+@@ -5032,69 +5032,6 @@ done
  
  
  
 -{ echo "$as_me:$LINENO: checking for main in -lcrypt" >&5
 -echo $ECHO_N "checking for main in -lcrypt... $ECHO_C" >&6; }
-+{ echo "$as_me:$LINENO: checking for main in -lcrypto" >&5
-+echo $ECHO_N "checking for main in -lcrypto... $ECHO_C" >&6; }
- if test "${ac_cv_lib_crypt_main+set}" = set; then
-   echo $ECHO_N "(cached) $ECHO_C" >&6
- else
-   ac_check_lib_save_LIBS=$LIBS
+-if test "${ac_cv_lib_crypt_main+set}" = set; then
+-  echo $ECHO_N "(cached) $ECHO_C" >&6
+-else
+-  ac_check_lib_save_LIBS=$LIBS
 -LIBS="-lcrypt  $LIBS"
-+LIBS="-lcrypto  $LIBS"
- cat >conftest.$ac_ext <<_ACEOF
- /* confdefs.h.  */
- _ACEOF
-@@ -5092,7 +5092,7 @@ if test $ac_cv_lib_crypt_main = yes; then
- #define HAVE_LIBCRYPT 1
- _ACEOF
- 
+-cat >conftest.$ac_ext <<_ACEOF
+-/* confdefs.h.  */
+-_ACEOF
+-cat confdefs.h >>conftest.$ac_ext
+-cat >>conftest.$ac_ext <<_ACEOF
+-/* end confdefs.h.  */
+-
+-
+-int
+-main ()
+-{
+-return main ();
+-  ;
+-  return 0;
+-}
+-_ACEOF
+-rm -f conftest.$ac_objext conftest$ac_exeext
+-if { (ac_try="$ac_link"
+-case "(($ac_try" in
+-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+-  *) ac_try_echo=$ac_try;;
+-esac
+-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+-  (eval "$ac_link") 2>conftest.er1
+-  ac_status=$?
+-  grep -v '^ *+' conftest.er1 >conftest.err
+-  rm -f conftest.er1
+-  cat conftest.err >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); } && {
+-	 test -z "$ac_c_werror_flag" ||
+-	 test ! -s conftest.err
+-       } && test -s conftest$ac_exeext &&
+-       $as_test_x conftest$ac_exeext; then
+-  ac_cv_lib_crypt_main=yes
+-else
+-  echo "$as_me: failed program was:" >&5
+-sed 's/^/| /' conftest.$ac_ext >&5
+-
+-	ac_cv_lib_crypt_main=no
+-fi
+-
+-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+-      conftest$ac_exeext conftest.$ac_ext
+-LIBS=$ac_check_lib_save_LIBS
+-fi
+-{ echo "$as_me:$LINENO: result: $ac_cv_lib_crypt_main" >&5
+-echo "${ECHO_T}$ac_cv_lib_crypt_main" >&6; }
+-if test $ac_cv_lib_crypt_main = yes; then
+-  cat >>confdefs.h <<_ACEOF
+-#define HAVE_LIBCRYPT 1
+-_ACEOF
+-
 -  LIBS="-lcrypt $LIBS"
-+  LIBS="-lcrypto $LIBS"
+-
+-fi
  
- fi
+ 
  
