Update to 1.7.3. UVM support.

diff --git a/sysutils/xosview/patches/patch-ac b/sysutils/xosview/patches/patch-ac
--- a/sysutils/xosview/patches/patch-ac
+++ b/sysutils/xosview/patches/patch-ac
@@ -1,8 +1,6 @@
-# $OpenBSD: patch-ac,v 1.3 1999/09/15 03:17:23 brad Exp $
-
---- configure.orig	Fri Jul  2 04:36:11 1999
-+++ configure	Fri Jul  2 04:41:31 1999
-@@ -1658,6 +1658,19 @@
+--- configure.orig	Wed Nov 17 13:16:57 1999
++++ configure	Sat Dec  4 23:05:24 1999
+@@ -1635,6 +1635,19 @@
    
  	  host_dir=linux
            host_os=linux ;;
@@ -20,13 +18,66 @@
 +	host_os=openbsd ;;
 +
  ##  Check for known versions of NetBSD...
- netbsd1.[0123]*)  
+ netbsd1.[012345]*)  
  	host_os=netbsd
-@@ -1761,6 +1774,7 @@
+@@ -1752,11 +1765,58 @@
          INSTALL_ARGS='-s -g kmem -m 02555'
  	cat >> confdefs.h <<\EOF
  #define XOSVIEW_OPENBSD 1
 +#define HAVE_SWAPCTL 1
  EOF
  
++  ## Also check for the existence of UVM.  This is a nasty,
++  ## complicated check.  This could be avoided by having the *BSD
++  ## platform-specific Makefiles include <bsd.own.mk> on their own.
++  cat > confmkfile <<\EOF
++.include <bsd.own.mk>
++all:
++.if defined(UVM)
++	@echo UVMyes
++.endif
++EOF
++  uvmstring=`make -f confmkfile`
++  rm confmkfile
++  if test x$uvmstring != x ; then
++    cat >> confdefs.h <<\EOF
++#define UVM 1
++EOF
  
+-			host_dir=bsd
+-	host_os=openbsd ;;
++    echo "configure: warning: 
++
++  *Enabling* UVM -- 'UVM=' found in /etc/mk.conf.
++  If this is in error, remove the define of UVM=1 from CXXFLAGS
++  in Makefile.config, and mail bgrayson@ece.utexas.edu that
++  the autoconf script didn't work properly.
++    " 1>&2
++  else
++            echo "configure: warning: 'UVM=' not found in /etc/mk.conf.  Checking /netbsd for uvm symbols..." 1>&2
++    if test x`nm /netbsd | grep uvm_sysctl` != x ; then
++      cat >> confdefs.h <<\EOF
++#define UVM 1
++EOF
++
++      echo "configure: warning: *Enabling* UVM -- 'uvm_sysctl' symbol found in /netbsd.
++  If this is in error, remove the define of UVM=1 from CXXFLAGS
++  in Makefile.config, and mail bgrayson@ece.utexas.edu that
++  the autoconf script didn't work properly.
++  " 1>&2
++    else
++      echo "configure: warning: 
++
++    *Disabling* UVM -- 'UVM=' not found in /etc/mk.conf.
++    If this is in error, add -DUVM=1 to CXXFLAGS in
++    Makefile.config, and please mail bgrayson@ece.utexas.edu that
++    the autoconf script did not work properly.
++    " 1>&2
++    fi
++  fi
++  host_dir=bsd
++  host_os=openbsd
++;;
+ bsdi*) 
+ 	EXTRALIBS="-lkvm $XPMLIB"
+ 	INSTALL_ARGS='-s -g kmem -m 02555'
