Update to new Tcl layout. While there, make use of the Tcl/Tk modules.
OK landry@, stu@

diff --git a/lang/otcl/patches/patch-configure b/lang/otcl/patches/patch-configure
--- a/lang/otcl/patches/patch-configure
+++ b/lang/otcl/patches/patch-configure
@@ -1,6 +1,6 @@
-$OpenBSD: patch-configure,v 1.5 2007/10/24 14:58:16 steven Exp $
+$OpenBSD: patch-configure,v 1.6 2011/01/05 18:49:20 sebastia Exp $
 --- configure.orig	Sun Feb 18 23:19:10 2007
-+++ configure	Sat Oct 13 15:48:01 2007
++++ configure	Thu Dec 23 11:24:03 2010
 @@ -4163,6 +4163,7 @@ TCL_H_PLACES=" \
  		/usr/local/lib/tcl$TCL_HI_VERS \
  		/usr/local/lib/tcl$TCL_ALT_VERS \
@@ -9,6 +9,51 @@ $OpenBSD: patch-configure,v 1.5 2007/10/24 14:58:16 steven Exp $
  		/usr/local/include/tcl$TCL_HI_VERS \
  		/usr/local/include/tcl$TCL_ALT_VERS \
  		/usr/local/include \
+@@ -4257,7 +4258,7 @@ else
+ echo "$as_me: error: $d is not a directory" >&2;}
+    { (exit 1); exit 1; }; }
+ 		fi
+-		places="$TCL_H_PLACES_D"
++		places="$TCL_H_PLACES_D $TCL_H_PLACES"
+ 	fi
+ 
+ 	V_INCLUDE_TCL=""
+@@ -4311,7 +4312,7 @@ else
+ echo "$as_me: error: $d is not a directory" >&2;}
+    { (exit 1); exit 1; }; }
+ 		fi
+-		places="$TCL_H_PLACES_D"
++		places="$TCL_H_PLACES_D $TCL_H_PLACES"
+ 	fi
+ 
+ 	V_INCLUDE_TCL=""
+@@ -4365,7 +4366,7 @@ else
+ echo "$as_me: error: $d is not a directory" >&2;}
+    { (exit 1); exit 1; }; }
+ 		fi
+-		places="$TCL_LIB_PLACES_D"
++		places="$TCL_LIB_PLACES_D $TCL_LIB_PLACES"
+ 	fi
+ 
+ 	V_LIB_TCL=""
+@@ -4824,7 +4825,7 @@ else
+ echo "$as_me: error: $d is not a directory" >&2;}
+    { (exit 1); exit 1; }; }
+ 		fi
+-		places="$TK_H_PLACES_D"
++		places="$TK_H_PLACES_D $TK_H_PLACES"
+ 	fi
+ 
+ 	V_INCLUDE_TK=""
+@@ -4878,7 +4879,7 @@ else
+ echo "$as_me: error: $d is not a directory" >&2;}
+    { (exit 1); exit 1; }; }
+ 		fi
+-		places="$TK_LIB_PLACES_D"
++		places="$TK_LIB_PLACES_D $TK_LIB_PLACES"
+ 	fi
+ 
+ 	V_LIB_TK=""
 @@ -5532,16 +5533,16 @@ case $system in
          DL_LIBS="-ldl"
          SHLD_FLAGS="-Wl,-Bexport"
