Apply same fix as in thunar-archive to fix build on a box where thunar-vfs is not installed. Remove the check in configure. Update patch-thunar-plugin_audio-tags-page_c while here. ok ajacoutot@.

diff --git a/x11/xfce4/thunar-media-tags/patches/patch-configure b/x11/xfce4/thunar-media-tags/patches/patch-configure
--- a/x11/xfce4/thunar-media-tags/patches/patch-configure
+++ b/x11/xfce4/thunar-media-tags/patches/patch-configure
@@ -1,6 +1,6 @@
-$OpenBSD: patch-configure,v 1.1 2011/01/18 20:53:58 landry Exp $
---- configure.orig	Sat Jan 15 23:13:49 2011
-+++ configure	Sat Jan 15 23:14:53 2011
+$OpenBSD: patch-configure,v 1.2 2011/02/02 08:41:30 landry Exp $
+--- configure.orig	Sat Jan 20 16:29:52 2007
++++ configure	Tue Feb  1 22:38:19 2011
 @@ -22462,22 +22462,22 @@ echo "${ECHO_T}$xdt_cv_PKG_CONFIG_VERSION" >&6; }
    fi
  
@@ -97,3 +97,67 @@ $OpenBSD: patch-configure,v 1.1 2011/01/18 20:53:58 landry Exp $
      { echo "$as_me:$LINENO: result: found, but $xdt_cv_version" >&5
  echo "${ECHO_T}found, but $xdt_cv_version" >&6; }
  
+@@ -22736,63 +22736,6 @@ echo "${ECHO_T}$xdt_cv_PKG_CONFIG_VERSION" >&6; }
+       exit 1
+     fi
+   fi
+-
+-
+-  { echo "$as_me:$LINENO: checking for thunar-vfs-1 >= 0.2.3svn-r20526" >&5
+-echo $ECHO_N "checking for thunar-vfs-1 >= 0.2.3svn-r20526... $ECHO_C" >&6; }
+-  if $PKG_CONFIG "--atleast-version=0.2.3svn-r20526" "thunar-vfs-1" >/dev/null 2>&1; then
+-    THUNARVFS_VERSION=`$PKG_CONFIG --modversion "thunar-vfs-1"`
+-    { echo "$as_me:$LINENO: result: $THUNARVFS_VERSION" >&5
+-echo "${ECHO_T}$THUNARVFS_VERSION" >&6; }
+-
+-    { echo "$as_me:$LINENO: checking THUNARVFS_CFLAGS" >&5
+-echo $ECHO_N "checking THUNARVFS_CFLAGS... $ECHO_C" >&6; }
+-    THUNARVFS_CFLAGS=`$PKG_CONFIG --cflags "thunar-vfs-1"`
+-    { echo "$as_me:$LINENO: result: $THUNARVFS_CFLAGS" >&5
+-echo "${ECHO_T}$THUNARVFS_CFLAGS" >&6; }
+-
+-    { echo "$as_me:$LINENO: checking THUNARVFS_LIBS" >&5
+-echo $ECHO_N "checking THUNARVFS_LIBS... $ECHO_C" >&6; }
+-    THUNARVFS_LIBS=`$PKG_CONFIG --libs "thunar-vfs-1"`
+-    { echo "$as_me:$LINENO: result: $THUNARVFS_LIBS" >&5
+-echo "${ECHO_T}$THUNARVFS_LIBS" >&6; }
+-
+-    THUNARVFS_REQUIRED_VERSION=0.2.3svn-r20526
+-
+-
+-
+-
+-
+-
+-
+-  elif $PKG_CONFIG --exists "thunar-vfs-1" >/dev/null 2>&1; then
+-    xdt_cv_version=`$PKG_CONFIG --modversion "thunar-vfs-1"`
+-    { echo "$as_me:$LINENO: result: found, but $xdt_cv_version" >&5
+-echo "${ECHO_T}found, but $xdt_cv_version" >&6; }
+-
+-
+-      echo "*** The required package thunar-vfs-1 was found on your system,"
+-      echo "*** but the installed version ($xdt_cv_version) is too old."
+-      echo "*** Please upgrade thunar-vfs-1 to atleast version 0.2.3svn-r20526, or adjust"
+-      echo "*** the PKG_CONFIG_PATH environment variable if you installed"
+-      echo "*** the new version of the package in a nonstandard prefix so"
+-      echo "*** pkg-config is able to find it."
+-      exit 1
+-
+-  else
+-    { echo "$as_me:$LINENO: result: not found" >&5
+-echo "${ECHO_T}not found" >&6; }
+-
+-
+-      echo "*** The required package thunar-vfs-1 was not found on your system."
+-      echo "*** Please install thunar-vfs-1 (atleast version 0.2.3svn-r20526) or adjust"
+-      echo "*** the PKG_CONFIG_PATH environment variable if you"
+-      echo "*** installed the package in a nonstandard prefix so that"
+-      echo "*** pkg-config is able to find it."
+-      exit 1
+-
+-  fi
+-
+ 
+ 
+   # minimum supported version of pkg-config
