update to nap-1.4.4-ps-2
The nap isn't really maintained by the real author anymore.  Instead,
there is another project which aims to continue the original author's
idea.  The new version is A LOT more stable, with various new fixes and
improvements.
The homepage is http://theory.stanford.edu/~selinger/nap/

Quick changelog with the main things:
- fixed a security bug (string format attack)
  ( http://www.shmoo.com/mail/bugtraq/sep00/msg00942.shtml )
- added --user, --pass, --email, --upload, --download, --dataport,
  --connection, --maxusers options to override settings in config file.
- look for config and library files in user's home directory, rather
  than current directory. Also, renamed these files more discreetly as
  .napconf and .nap_shared.
- fixed several memory leaks and null pointer bugs.

from maintainer

diff --git a/audio/nap/patches/patch-configure b/audio/nap/patches/patch-configure
--- a/audio/nap/patches/patch-configure
+++ b/audio/nap/patches/patch-configure
@@ -1,47 +1,48 @@
-$OpenBSD: patch-configure,v 1.1.1.1 2001/02/04 18:55:33 reinhard Exp $
---- configure.orig	Tue Jan 23 19:36:29 2001
-+++ configure	Tue Jan 23 19:36:56 2001
-@@ -1155,14 +1155,14 @@ else
-   echo "$ac_t""no" 1>&6
- fi
+$OpenBSD: patch-configure,v 1.2 2001/04/04 10:53:47 reinhard Exp $
+--- configure.orig	Wed Mar 28 10:50:06 2001
++++ configure	Wed Mar 28 10:50:26 2001
+@@ -604,44 +604,6 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCR
  
--echo $ac_n "checking for initscr in -lncurses""... $ac_c" 1>&6
--echo "configure:1160: checking for initscr in -lncurses" >&5
--ac_lib_var=`echo ncurses'_'initscr | sed 'y%./+-%__p_%'`
-+echo $ac_n "checking for initscr in -lcurses""... $ac_c" 1>&6
-+echo "configure:1160: checking for initscr in -lcurses" >&5
-+ac_lib_var=`echo curses'_'initscr | sed 'y%./+-%__p_%'`
- if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
-   echo $ac_n "(cached) $ac_c" 1>&6
+ test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
+ 
+-echo $ac_n "checking whether build environment is sane""... $ac_c" 1>&6
+-echo "configure:609: checking whether build environment is sane" >&5
+-# Just in case
+-sleep 1
+-echo timestamp > conftestfile
+-# Do `set' in a subshell so we don't clobber the current shell's
+-# arguments.  Must try -L first in case configure is actually a
+-# symlink; some systems play weird games with the mod time of symlinks
+-# (eg FreeBSD returns the mod time of the symlink's containing
+-# directory).
+-if (
+-   set X `ls -Lt $srcdir/configure conftestfile 2> /dev/null`
+-   if test "$*" = "X"; then
+-      # -L didn't work.
+-      set X `ls -t $srcdir/configure conftestfile`
+-   fi
+-   if test "$*" != "X $srcdir/configure conftestfile" \
+-      && test "$*" != "X conftestfile $srcdir/configure"; then
+-
+-      # If neither matched, then we have a broken ls.  This can happen
+-      # if, for instance, CONFIG_SHELL is bash and it inherits a
+-      # broken ls alias from the environment.  This has actually
+-      # happened.  Such a system could not be considered "sane".
+-      { echo "configure: error: ls -t appears to fail.  Make sure there is not a broken
+-alias in your environment" 1>&2; exit 1; }
+-   fi
+-
+-   test "$2" = conftestfile
+-   )
+-then
+-   # Ok.
+-   :
+-else
+-   { echo "configure: error: newly created file is older than distributed files!
+-Check your system clock" 1>&2; exit 1; }
+-fi
+-rm -f conftest*
+-echo "$ac_t""yes" 1>&6
+ if test "$program_transform_name" = s,x,x,; then
+   program_transform_name=
  else
-   ac_save_LIBS="$LIBS"
--LIBS="-lncurses  $LIBS"
-+LIBS="-lcurses  $LIBS"
- cat > conftest.$ac_ext <<EOF
- #line 1168 "configure"
- #include "confdefs.h"
-@@ -1190,13 +1190,13 @@ LIBS="$ac_save_LIBS"
- fi
- if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
-   echo "$ac_t""yes" 1>&6
--    ac_tr_lib=HAVE_LIB`echo ncurses | sed -e 's/[^a-zA-Z0-9_]/_/g' \
-+    ac_tr_lib=HAVE_LIB`echo curses | sed -e 's/[^a-zA-Z0-9_]/_/g' \
-     -e 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'`
-   cat >> confdefs.h <<EOF
- #define $ac_tr_lib 1
- EOF
- 
--  LIBS="-lncurses $LIBS"
-+  LIBS="-lcurses $LIBS"
- 
- else
-   echo "$ac_t""no" 1>&6
-@@ -1387,7 +1387,7 @@ EOF
- 
- fi
- 
--for ac_hdr in ncurses.h
-+for ac_hdr in curses.h
- do
- ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
- echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
