update to notmuch 0.30, adjust how shlib versioning is done to maintain the original version numbers in headers as there's a macro used to check this which fails with previous patch. from Olivier Taïbi.
add quirks/@pkgpath to merge py-notmuch -> py3-notmuch, from me

diff --git a/mail/notmuch/notmuch/patches/patch-configure b/mail/notmuch/notmuch/patches/patch-configure
--- a/mail/notmuch/notmuch/patches/patch-configure
+++ b/mail/notmuch/notmuch/patches/patch-configure
@@ -1,18 +1,27 @@
-$OpenBSD: patch-configure,v 1.2 2020/05/16 11:43:51 sthen Exp $
+$OpenBSD: patch-configure,v 1.3 2020/08/13 18:21:18 sthen Exp $
 
 Index: configure
 --- configure.orig
 +++ configure
-@@ -533,7 +533,7 @@ EOF
+@@ -518,7 +518,7 @@ EOF
          printf 'No.\nCould not make tempdir for testing session-key support.\n'
          errors=$((errors + 1))
      elif ${CC} ${CFLAGS} ${gmime_cflags} _check_session_keys.c ${gmime_ldflags} -o _check_session_keys \
--           && GNUPGHOME=${TEMP_GPG} gpg --batch --quiet --import < test/gnupg-secret-key.asc \
-+           && GNUPGHOME=${TEMP_GPG} gpg2 --batch --quiet --import < test/gnupg-secret-key.asc \
+-           && GNUPGHOME=${TEMP_GPG} gpg --batch --quiet --import < "$srcdir"/test/gnupg-secret-key.asc \
++           && GNUPGHOME=${TEMP_GPG} gpg2 --batch --quiet --import < "$srcdir"/test/gnupg-secret-key.asc \
             && SESSION_KEY=$(GNUPGHOME=${TEMP_GPG} ./_check_session_keys) \
             && [ $SESSION_KEY = 9:0BACD64099D1468AB07C796F0C0AC4851948A658A15B34E803865E9FC635F2F5 ]
      then
-@@ -588,9 +588,9 @@ if ! pkg-config --exists zlib; then
+@@ -669,7 +669,7 @@ EOF
+         printf 'No.\nCould not make tempdir for testing signature verification when decrypting with session keys.\n'
+         errors=$((errors + 1))
+     elif ${CC} ${CFLAGS} ${gmime_cflags} _verify_sig_with_session_key.c ${gmime_ldflags} -o _verify_sig_with_session_key \
+-            && GNUPGHOME=${TEMP_GPG} gpg --batch --quiet --import < "$srcdir"/test/gnupg-secret-key.asc \
++            && GNUPGHOME=${TEMP_GPG} gpg2 --batch --quiet --import < "$srcdir"/test/gnupg-secret-key.asc \
+             && rm -f ${TEMP_GPG}/private-keys-v1.d/*.key
+     then
+         if GNUPGHOME=${TEMP_GPG} ./_verify_sig_with_session_key; then
+@@ -721,9 +721,9 @@ if ! pkg-config --exists zlib; then
    rm -f compat/gen_zlib_pc
  fi
  
