Kill a large set of deprecated variables. Thoroughly unsubtle, most mkdir -p should probably be INSTALL* at *install stage, and echo/ECHO_MSG is somewhat unsorted.
It's quite possible I missed a few automated changes...

diff --git a/lang/egcs/stable/Makefile b/lang/egcs/stable/Makefile
--- a/lang/egcs/stable/Makefile
+++ b/lang/egcs/stable/Makefile
@@ -1,4 +1,4 @@
-# $OpenBSD: Makefile,v 1.25 2000/02/02 17:02:39 espie Exp $
+# $OpenBSD: Makefile,v 1.26 2000/02/11 01:10:04 espie Exp $
 
 # This is a configuration file for egcs, stable release.
 
@@ -127,7 +127,7 @@ MASTER_SITES+= ftp://linux.cis.nctu.edu.tw/pub/packages/pcg/${DIRECTORY}
 pre-fetch:
 .if (${MACHINE_ARCH} == "i386")
 	@(cd /tmp && /usr/bin/as -k ${FILESDIR}/gas-bug/test-i386-gas.s) || \
-	(${ECHO} "Your gas has a bug, see ${FILESDIR}/gas-bug for details"; ${FALSE})
+	(echo "Your gas has a bug, see ${FILESDIR}/gas-bug for details"; exit 1)
 .endif
 
 #### 
@@ -153,9 +153,9 @@ PATCH_LIST+=patch-java-*
 # get openbsd configuration files where they should be
 post-patch:
 		# avoid packaging include copies along...
-	find ${WRKSRC} -name \*.orig|xargs ${RM}
-	${CP} -R ${FILESDIR}/config/* ${WRKSRC}
-	${RM} -rf ${WRKSRC}/texinfo 
+	find ${WRKSRC} -name \*.orig|xargs rm
+	cp -R ${FILESDIR}/config/* ${WRKSRC}
+	rm -rf ${WRKSRC}/texinfo 
 # rebuild configure files after patching, then move source around !!!
 # XXX: don't try to autoconf the main configure file, it's not autoconf.
 	cd ${WRKSRC}/gcc && PATH=${PORTPATH} autoreconf
@@ -222,7 +222,7 @@ do-build:
 	@(cd ${WRKBUILD}; \
 	${MAKE_ENV} ${MAKE_PROGRAM} ${MAKE_FLAGS} ${MAKEFILE} ${ALL_TARGET} 2>warnings) || \
 	(echo "*** Make bootstrap failed."; \
-	echo "*** Look at ${WRKBUILD}/warnings for errors"; ${FALSE})
+	echo "*** Look at ${WRKBUILD}/warnings for errors"; exit 1)
 
 ####
 # Install & tests section 
@@ -236,8 +236,8 @@ post-build:
 	@(cd ${WRKBUILD}; ulimit -c 0; \
 	${MAKE_ENV} ${MAKE_PROGRAM} ${MAKE_FLAGS} ${MAKEFILE} check && \
 	${WRKSRC}/contrib/test_summary >${TEST_RESULT})
-	@${ECHO} "Please send the tests results to the egcs project"
-	@${ECHO} "By invoking make send-results"
+	@echo "Please send the tests results to the egcs project"
+	@echo "By invoking make send-results"
 
 send-results: 
 	[ -f ${TEST_RESULT} ] && sh ${TEST_RESULT}
diff --git a/math/maple/Makefile b/math/maple/Makefile
--- a/math/maple/Makefile
+++ b/math/maple/Makefile
@@ -1,4 +1,4 @@
-# $OpenBSD: Makefile,v 1.5 2000/02/10 09:38:03 espie Exp $
+# $OpenBSD: Makefile,v 1.6 2000/02/11 01:10:06 espie Exp $
 # Original from: Marc Espie
 # XXX This port installs in a somewhat unusual way.
 
@@ -55,14 +55,14 @@ do-fetch:
 			mkdir -p ${FULLDISTDIR}/`dirname $$file`;\
 			ln -sf ${CDROM}/$$file ${FULLDISTDIR}/$$file;\
 		else\
-			${ECHO} "File $$file not found. Is your cdrom mounted as ${CDROM} ?";\
+			echo "File $$file not found. Is your cdrom mounted as ${CDROM} ?";\
 		fi\
 	done
 
 MAPLE_SCRIPTS=maple march mint updtsrc xmaple
 
 do-install:
-	@mkdir -p ${MAPLE_DIR} || ${ECHO} "${MAPLE_DIR} already exists"
+	@mkdir -p ${MAPLE_DIR} || echo "${MAPLE_DIR} already exists"
 	@cd ${MAPLE_DIR} && yes | ${FULLDISTDIR}/install
 	@echo "But this installation script does it for you"
 	@for file in ${MAPLE_SCRIPTS}; do\
