Fail on URLs without scheme, add missing RCS id
Otherwise ftp(1) drops into the "ftp> " prompt
(I fixed that bug myself in sysupgrade.sh r1.42 but forgot about it here.)

wget(1) and curl(1) always exit either way instead of blocking, *but*:

- cURL does not URL encode unsafe characters (just like ftp).
- Wget cannot be quiet except for error messages AND write files to stdout:
1. --quiet drops *every* message (incl. warnings/errors),
2. --no-verbose is silent but not quiet (still progress/stats on stdout),
3. --output-file redirects *every* message (progress *and* errors);
So no way to tell it "quiet, errors on stderr, content on stdout)...

So three different tools of which none of them gets all three things right:
- ftp fails on URLs without schema
- cURL does not URL encode its input (on purpose according to manual)
- Wget fails to provide basic stdio primitives

Stick to ftp(1), "validate" the URL with glob patterns and encode it with
jq(1) (as done before) to keep RUN_DEPENDS down at one (jq).

diff --git a/sysutils/portroach-cli/files/portroach-cli b/sysutils/portroach-cli/files/portroach-cli
--- a/sysutils/portroach-cli/files/portroach-cli
+++ b/sysutils/portroach-cli/files/portroach-cli
@@ -1,5 +1,7 @@
 #!/bin/ksh
 #
+# $OpenBSD: portroach-cli,v 1.2 2021/01/12 08:34:58 kn Exp $
+#
 # Copyright (c) 2021 Klemens Nanni <kn@openbsd.org>
 #
 # Permission to use, copy, modify, and distribute this software for any
@@ -16,9 +18,16 @@
 
 set -Cefu -o pipefail
 
+readonly self=${0##*/}
+
+err() {
+	printf '%s: %s\n' "$self" "$*" 1>&2
+	exit 1
+}
+
 usage() {
 	printf 'usage:\t%s [-o] [-m maintainer [-p pkgpath]] [-u url]\n' \
-	    "${0##*/}" 1>&2
+	    "$self" 1>&2
 	exit 1
 }
 
@@ -46,7 +55,7 @@ show_ports() {
 mflag=false maintainer=
 oflag=false
 pflag=false pkgpath=
-url=https://portroach.openbsd.org
+uflag=false url=https://portroach.openbsd.org
 
 while getopts m:op:u: opt
 do
@@ -54,12 +63,13 @@ do
 	m)	mflag=true maintainer=$OPTARG ;;
 	o)	oflag=true ;;
 	p)	pflag=true pkgpath=$OPTARG ;;
-	u)	url=$OPTARG ;;
+	u)	uflag=true url=$OPTARG ;;
 	*)	usage
 	esac
 done
 shift $((OPTIND - 1))
 $pflag && ! $mflag && usage
+$uflag && [[ $url != @(file|ftp|http|https)://* ]] && err 'invalid url'
 [ $# -eq 0 ] || usage
 
 if $mflag
