o update openafs to 1.4.7 o add README.OpenBSD (includes heimdal setup instructions) o rework openafs-setup to use arla's afsd in base, and heimdal o fix a bug since 4.1 to not blow the thread stack on 64bit time functions in libc

diff --git a/net/openafs/Makefile b/net/openafs/Makefile
--- a/net/openafs/Makefile
+++ b/net/openafs/Makefile
@@ -1,50 +1,114 @@
-# $OpenBSD: Makefile,v 1.17 2008/07/06 15:26:14 naddy Exp $
+# $OpenBSD: Makefile,v 1.18 2008/07/21 03:13:01 todd Exp $
 
-ONLY_FOR_ARCHS= 	i386
+ONLY_FOR_ARCHS=		i386
 
-COMMENT=		distributed filesystem OpenAFS
+COMMENT=		OpenAFS distributed filesystem
 
-V=			1.4.0
-DISTNAME=		openafs-${V}-src
-PKGNAME=		openafs-${V}p9
-CATEGORIES=		net
+VERSION=		1.4.7
+DISTNAME=		openafs-${VERSION}
+
+CATEGORIES=		net wipstuff/net
 
 HOMEPAGE=		http://www.openafs.org
 
 MAINTAINER=		Todd T. Fries <todd@openbsd.org>
 
-# IPL
 PERMIT_PACKAGE_CDROM=	Yes
 PERMIT_PACKAGE_FTP=	Yes
-PERMIT_DISTFILES_CDROM= Yes
+PERMIT_DISTFILES_CDROM=	Yes
 PERMIT_DISTFILES_FTP=	Yes
 
-WANTLIB=		c pthread
+WANTLIB=		c
 
-MASTER_SITES=		http://www.openafs.org/dl/openafs/${V}/
-EXTRACT_SUFX=		.tar.bz2
+SHARED_LIBS=	afssetpag 1.0
 
-CONFIGURE_STYLE=	autoconf
-AUTOCONF_VERSION=	2.13
+MASTER_SITES=		http://www.openafs.org/dl/openafs/${VERSION}/
+
+EXTRACT_SUFX=		-src.tar.bz2
+
+NO_REGRESS=		Yes
+
+CONFIGURE_STYLE=	GNU
+
+CONFIGURE_ENV+=		KRB5CFLAGS="-I/usr/include/kerberosV -DUSING_HEIMDAL" \
+			KRB5LIBS="-lkrb5"
 CONFIGURE_ARGS+=	${CONFIGURE_SHARED} \
+			--localstatedir=/var \
+			--disable-transarc-paths \
 			--enable-namei-fileserver \
 			--enable-largefile-fileserver \
-			--enable-supergroups \
 			--with-afs-sysname=${ARCH}_obsd${OSrev} \
-			--disable-kernel-module
+			--enable-fast-restart \
+			--disable-kernel-module \
+			--enable-supergroups
 
-WRKDIST=		${WRKDIR}/${DISTNAME:S/-src$//}
+
+AUTOCONF_VERSION=	2.60
+BUILD_DEPENDS=		::devel/autoconf/${AUTOCONF_VERSION}
+
+FLAVORS=	debug
+FLAVOR?=
+
+pre-configure:	patch
+	@if [ ! -d /usr/src/sys ] ; then \
+		echo ; \
+		echo "*** Error: Building this package requires the kernel sources" ; \
+		echo "***        to be available in directory /usr/src/sys" ; \
+		echo ; \
+		exit 1 ; \
+	fi
+	@( \
+		cd ${WRKBUILD} ; \
+		cp -p configure configure.orig ; \
+		cp -p configure-libafs configure-libafs.orig ; \
+		env AUTOCONF_VERSION=${AUTOCONF_VERSION} autoconf ; \
+		env AUTOCONF_VERSION=${AUTOCONF_VERSION} \
+			autoconf configure-libafs.in > configure-libafs ; \
+		chmod +x configure-libafs ; \
+		rm -r autom4te.cache \
+	)
 
 post-patch:
-	@sed 's/%OSrev%/'${OSrev}'/g' ${FILESDIR}/param.i386_obsd.h \
+	@sed 's/%OSrev%/'${OSrev}'/g;s/i386/'${ARCH}'/g' \
+		${FILESDIR}/param.i386_obsd.h \
 		> ${WRKSRC}/src/config/param.${ARCH}_obsd${OSrev}.h
 
 post-install:
-	@${INSTALL_DATA_DIR} ${PREFIX}/share/
-.for file in openafs-setup
-	@sed -e s,%PREFIX%,${PREFIX},g -e s,%SYSCONFDIR%,${SYSCONFDIR},g \
-		< ${FILESDIR}/${file} > ${PREFIX}/sbin/${file}
-	@chmod u+x ${PREFIX}/sbin/${file}
+	@${INSTALL_DATA_DIR} ${PREFIX}/share/openafs
+.for file in README.OpenBSD
+	sed -e s,%LOCALBASE%,${LOCALBASE},g \
+		-e s,%SYSCONFDIR%,${SYSCONFDIR},g \
+		< ${FILESDIR}/${file} > ${PREFIX}/share/openafs/${file}
 .endfor
- 
+	@${INSTALL_DATA_DIR} ${PREFIX}/share/examples/openafs
+.for file in krb5.conf
+	sed -e s,%LOCALBASE%,${LOCALBASE},g \
+		-e s,%SYSCONFDIR%,${SYSCONFDIR},g \
+		< ${FILESDIR}/${file} > \
+		${PREFIX}/share/examples/openafs/${file}
+.endfor
+.for file in openafs-setup
+	sed -e s,%LOCALBASE%,${LOCALBASE},g \
+		-e s,%SYSCONFDIR%,${SYSCONFDIR},g \
+		< ${FILESDIR}/${file} > ${PREFIX}/sbin/${file}
+	chmod u+x ${PREFIX}/sbin/${file}
+.endfor
+
+.if ${FLAVOR:L:Mdebug}
+CONFIGURE_ARGS+=	--enable-debug
+CONFIGURE_ARGS+=	--enable-debug-lwp
+.endif
+
+.if ${MACHINE} == "alpha" || \
+	${MACHINE} == "amd64" || \
+	${MACHINE} == "arm" || \
+	${MACHINE} == "i386" || \
+	${MACHINE} == "mips64" || \
+	${MACHINE} == "sh" || \
+	${MACHINE} == "vax"
+CONFIGURE_ARGS+=	--enable-littleendian
+.else
+CONFIGURE_ARGS+=	--enable-bigendian
+.endif
+
 .include <bsd.port.mk>
