Update to 8.54.
Some help by steven@ and espie@.

"commit" espie@

diff --git a/print/ghostscript/gnu/patches/patch-lib_ps2epsi b/print/ghostscript/gnu/patches/patch-lib_ps2epsi
--- a/print/ghostscript/gnu/patches/patch-lib_ps2epsi
+++ b/print/ghostscript/gnu/patches/patch-lib_ps2epsi
@@ -1,12 +1,26 @@
-$OpenBSD: patch-lib_ps2epsi,v 1.4 2006/01/02 22:44:50 sturm Exp $
---- lib/ps2epsi.orig	Mon Apr 22 22:18:24 2002
-+++ lib/ps2epsi	Mon Jan  2 22:14:16 2006
-@@ -1,7 +1,7 @@
- #!/bin/sh
- # $Id: patch-lib_ps2epsi,v 1.4 2006/01/02 22:44:50 sturm Exp $
+$OpenBSD: patch-lib_ps2epsi,v 1.5 2006/10/19 13:12:37 kili Exp $
+--- lib/ps2epsi.orig	Fri Jan 27 22:58:27 2006
++++ lib/ps2epsi	Sat Sep 30 22:49:46 2006
+@@ -6,13 +6,7 @@
+ GS_EXECUTABLE=gs
  
--tmpfile=/tmp/ps2epsi$$
+ # try to create a temporary file securely
+-tmpdir=/tmp/ps2epsi.$$
+-(umask 077 && mkdir $tmpdir)
+-if ! test -d $tmpdir; then
+-	echo "failed: could not create temporary file"
+-	exit 1
+-fi
+-tmpfile=$tmpdir/ps2epsi$$
 +tmpfile=`mktemp -t ps2epsiXXXXXXXXXX` || exit 1
  
  export outfile
  
+@@ -64,7 +58,6 @@ awk 'F==1	{
+ 
+ $GS_EXECUTABLE -q -dNOPAUSE -dSAFER -dDELAYSAFER -r72 -sDEVICE=bit -sOutputFile=/dev/null $tmpfile ps2epsi.ps $tmpfile <"${infile}" 1>&2
+ rm -f $tmpfile
+-rm -rf $tmpdir
+ 
+ (
+ cat << BEGINEPS
