Some cleanup:  - lowercase COMMENT  - add a $V variable for version number to ease upgrades  - s/$LOCALBASE/$PREFIX in files/openafs-setup  - use $SYSCONFDIR instead of /etc for files/openafs-setup  (where appropriate)
"go fot it" todd@

diff --git a/net/openafs/files/openafs-setup b/net/openafs/files/openafs-setup
--- a/net/openafs/files/openafs-setup
+++ b/net/openafs/files/openafs-setup
@@ -13,7 +13,7 @@ then
     exit
 fi
 export PATH=/bin:/usr/bin:/sbin:/usr/sbin:%LOCALBASE%/bin:%LOCALBASE%/sbin
-SERVBIN=%LOCALBASE%/libexec/openafs
+SERVBIN=%PREFIX%/libexec/openafs
 
 
 # Ask for a password, saving the input in $resp.
@@ -75,13 +75,13 @@ else
 	echo "afs=NO" > /etc/rc.conf.local
 fi
 
-if [[ `/usr/bin/grep %LOCALBASE%/lib/openafs/libafs.o /etc/rc.securelevel` = "" ]]
+if [[ `/usr/bin/grep %PREFIX%/lib/openafs/libafs.o /etc/rc.securelevel` = "" ]]
 then
 /bin/cat <<EOF>> /etc/rc.securelevel
 
-if [[ -f %LOCALBASE%/lib/openafs/libafs.o ]]
+if [[ -f %PREFIX%/lib/openafs/libafs.o ]]
 then
-        /sbin/modload %LOCALBASE%/lib/openafs/libafs.o
+        /sbin/modload %PREFIX%/lib/openafs/libafs.o
 fi
 EOF
 fi
@@ -113,7 +113,7 @@ else # not running in secure level >= 1
 
         if [[ `modstat|grep afs` == "" ]]
         then
-                /sbin/modload %LOCALBASE%/lib/openafs/libafs.o
+                /sbin/modload %PREFIX%/lib/openafs/libafs.o
         fi
 fi
 
@@ -171,12 +171,12 @@ then
 	echo "		Process ID ${PG} did not die, so we can not continue."
 
 
-	if [[ `/usr/bin/grep %LOCALBASE%/bin/bos /etc/rc.local` = "" ]]
+	if [[ `/usr/bin/grep %PREFIX%/bin/bos /etc/rc.local` = "" ]]
 	then
 		echo "		Please edit /etc/rc.local and remove the following lines"
 		echo "		---------------cut here---------------------------------"
-		echo "		if [ -x %LOCALBASE%/sbin/bosserver ]; then"
-        	echo "		%LOCALBASE%/sbin/bosserver"
+		echo "		if [ -x %PREFIX%/sbin/bosserver ]; then"
+        	echo "		%PREFIX%/sbin/bosserver"
 		echo "		fi"
 		echo "		---------------cut here---------------------------------"
 	fi
@@ -185,16 +185,16 @@ then
 	exit 
 fi
 
-rm -rf /var/openafs /etc/openafs
+rm -rf /var/openafs %SYSCONFDIR%/openafs
 mkdir -m 700 /var/openafs /var/openafs/db
-mkdir -m 755  /etc/openafs /etc/openafs/server /var/openafs/server /var/openafs/cache
-/bin/echo "/afs:/var/openafs/cache:${CACHESIZE:?}" > /etc/openafs/cacheinfo
+mkdir -m 755  %SYSCONFDIR%/openafs %SYSCONFDIR%/openafs/server /var/openafs/server /var/openafs/cache
+/bin/echo "/afs:/var/openafs/cache:${CACHESIZE:?}" > %SYSCONFDIR%/openafs/cacheinfo
 
-KAS=%LOCALBASE%/sbin/kas
-BOS=%LOCALBASE%/bin/bos
-FS=%LOCALBASE%/bin/fs
-VOS=%LOCALBASE%/sbin/vos
-PTS=%LOCALBASE%/bin/pts
+KAS=%PREFIX%/sbin/kas
+BOS=%PREFIX%/bin/bos
+FS=%PREFIX%/bin/fs
+VOS=%PREFIX%/sbin/vos
+PTS=%PREFIX%/bin/pts
 
 while :; do 
 	askpass "Please enter the initial password you wish to use with the 'admin' user -->"
@@ -226,11 +226,11 @@ echo "${CELLNAME:?}" > /etc/afs/ThisCell
 echo ">${CELLNAME:?}    #Cell name
 ${IP:?}    #${SERVER:?}" >> /etc/afs/CellServDB
 
-ln -s /etc/afs/CellServDB /etc/openafs/CellServDB
-ln -s /etc/afs/ThisCell /etc/openafs/ThisCell
-ln -s /etc/afs/CellServDB /etc/openafs/server/CellServDB
-ln -s /etc/afs/ThisCell /etc/openafs/server/ThisCell
-ln -s /etc/openafs/server/KeyFile /etc/openafs/KeyFile
+ln -s /etc/afs/CellServDB %SYSCONFDIR%/openafs/CellServDB
+ln -s /etc/afs/ThisCell %SYSCONFDIR%/openafs/ThisCell
+ln -s /etc/afs/CellServDB %SYSCONFDIR%/openafs/server/CellServDB
+ln -s /etc/afs/ThisCell %SYSCONFDIR%/openafs/server/ThisCell
+ln -s /etc/openafs/server/KeyFile %SYSCONFDIR%/openafs/KeyFile
 
 #make sure arla is not mounted, and afsd is killed.
 if [[ `/sbin/mount|/usr/bin/awk '($3 ~ "^/afs") {print $0}'` != "" ]]
@@ -246,29 +246,29 @@ move_file /usr/sbin/vos
 move_file /usr/sbin/pts
 move_file /usr/sbin/pts
 
-if [[ `/usr/bin/grep %LOCALBASE%/lib/openafs/libafs.o /etc/rc.securelevel` = "" ]]
+if [[ `/usr/bin/grep %PREFIX%/lib/openafs/libafs.o /etc/rc.securelevel` = "" ]]
 then
 /bin/cat <<EOF>> /etc/rc.securelevel
-if [[ -f %LOCALBASE%/lib/openafs/libafs.o ]]
+if [[ -f %PREFIX%/lib/openafs/libafs.o ]]
 then
-        /sbin/modload %LOCALBASE%/lib/openafs/libafs.o
+        /sbin/modload %PREFIX%/lib/openafs/libafs.o
 fi
 EOF
 fi
 
-if [[ `/usr/bin/grep %LOCALBASE%/sbin/afsd /etc/rc.local` = "" ]]
+if [[ `/usr/bin/grep %PREFIX%/sbin/afsd /etc/rc.local` = "" ]]
 then
 /bin/cat <<EOF>> /etc/rc.local
-if [[ -f %LOCALBASE%/sbin/afsd ]]
+if [[ -f %PREFIX%/sbin/afsd ]]
 then
-        %LOCALBASE%/sbin/afsd -stat 4000 -dcache 4000 -daemons 6 -volumes 256 -files 5000
+        %PREFIX%/sbin/afsd -stat 4000 -dcache 4000 -daemons 6 -volumes 256 -files 5000
 fi
 EOF
 fi
 
 #begin server setup.
-echo "!%LOCALBASE%/sbin/bosserver -noauth &"
-%LOCALBASE%/sbin/bosserver -noauth &
+echo "!%PREFIX%/sbin/bosserver -noauth &"
+%PREFIX%/sbin/bosserver -noauth &
 
 echo "!$BOS setcellname $SERVER $CELLNAME -noauth"
 $BOS setcellname $SERVER  $CELLNAME -noauth 
@@ -354,8 +354,8 @@ echo "!$VOS syncserv $SERVER -cell $CELLNAME -verbose -noauth"
 $VOS syncserv $SERVER -cell $CELLNAME -verbose -noauth
 sleep 4
 
-echo "!$BOS create  $SERVER upserver simple "$SERVBIN/upserver -crypt /etc/openafs  -clear %LOCALBASE%/bin" -cell $CELLNAME  -noauth"
-$BOS create  $SERVER upserver simple "$SERVBIN/upserver -crypt /etc/openafs -clear %LOCALBASE%/bin" -cell $CELLNAME  -noauth
+echo "!$BOS create  $SERVER upserver simple "$SERVBIN/upserver -crypt %SYSCONFDIR%/openafs  -clear %PREFIX%/bin" -cell $CELLNAME  -noauth"
+$BOS create  $SERVER upserver simple "$SERVBIN/upserver -crypt %SYSCONFDIR%/openafs -clear %PREFIX%/bin" -cell $CELLNAME  -noauth
 
 if ! pgrep ntpd>/dev/null; then
     echo "ntpd is not running, consider running it to keep your time in sync!"
@@ -364,15 +364,15 @@ fi
 pkill -9 -x kaserver buserver ptserver vlserver bosserver fileserver
 
 #begin server configuration
-echo "!%LOCALBASE%/sbin/bosserver"
-%LOCALBASE%/sbin/bosserver
-echo "!%LOCALBASE%/sbin/afsd -stat 4000 -dcache 4000 -daemons 6 -volumes 256 -files 5000"
-%LOCALBASE%/sbin/afsd -stat 4000 -dcache 4000 -daemons 6 -volumes 256 -files 5000|| err "Failed to launch afsd.";
+echo "!%PREFIX%/sbin/bosserver"
+%PREFIX%/sbin/bosserver
+echo "!%PREFIX%/sbin/afsd -stat 4000 -dcache 4000 -daemons 6 -volumes 256 -files 5000"
+%PREFIX%/sbin/afsd -stat 4000 -dcache 4000 -daemons 6 -volumes 256 -files 5000|| err "Failed to launch afsd.";
 sleep 4
 
 echo "!klogging as admin"
-echo "!%LOCALBASE%/bin/klog  -principal admin -password PASSWD"
-%LOCALBASE%/bin/klog  -principal admin -password $passwd1
+echo "!%PREFIX%/bin/klog  -principal admin -password PASSWD"
+%PREFIX%/bin/klog  -principal admin -password $passwd1
 
 echo "!$VOS addsite $SERVER /vicepa root.afs -cell $CELLNAME"
 $VOS addsite $SERVER /vicepa root.afs -cell $CELLNAME
@@ -401,21 +401,21 @@ $FS setacl /afs/$CELLNAME system:anyuser rl
 $VOS release root.afs
 $VOS release root.cell
 
-if [[ `grep %LOCALBASE%/sbin/bosserver /etc/rc.local` = "" ]]
+if [[ `grep %PREFIX%/sbin/bosserver /etc/rc.local` = "" ]]
 then
 cat <<EOF>>/etc/rc.local
-if [ -x %LOCALBASE%/sbin/bosserver ]; then
-        %LOCALBASE%/sbin/bosserver 
+if [ -x %PREFIX%/sbin/bosserver ]; then
+        %PREFIX%/sbin/bosserver 
 fi
 EOF
 fi
 
-if [[ `grep %LOCALBASE%/bin/bos /etc/rc.shutdown` = "" ]]
+if [[ `grep %PREFIX%/bin/bos /etc/rc.shutdown` = "" ]]
 then
 cat <<EOF>>/etc/rc.shutdown
-if [ -x %LOCALBASE%/bin/bos ]; then
+if [ -x %PREFIX%/bin/bos ]; then
 	/usr/bin/pgrep -x bosserver 1>/dev/null && \
-       %LOCALBASE%/bin/bos shutdown localhost -wait -localauth
+       %PREFIX%/bin/bos shutdown localhost -wait -localauth
 fi
 EOF
 fi
