update to freeradius-3.2.3

diff --git a/net/freeradius/patches/patch-configure b/net/freeradius/patches/patch-configure
--- a/net/freeradius/patches/patch-configure
+++ b/net/freeradius/patches/patch-configure
@@ -4,12 +4,12 @@ library detection doesn't offer a nice way to do it.
 Index: configure
 --- configure.orig
 +++ configure
-@@ -7368,7 +7368,7 @@ if test "x$smart_lib" != "x"; then
+@@ -8432,7 +8432,7 @@ if test "x$smart_lib" != "x"; then
    SMART_LIBS="$smart_ldflags $smart_lib $SMART_LIBS"
  fi
  
 -if test "x$ac_cv_lib_collectdclient_lcc_connect" != "xyes"; then
 +if true || test "x$ac_cv_lib_collectdclient_lcc_connect" != "xyes"; then
-   { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: collectdclient library not found. Use --with-collectdclient-lib-dir=<path>." >&5
- $as_echo "$as_me: WARNING: collectdclient library not found. Use --with-collectdclient-lib-dir=<path>." >&2;}
+   { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: collectdclient library not found. Use --with-collectdclient-lib-dir=<path>." >&5
+ printf "%s\n" "$as_me: WARNING: collectdclient library not found. Use --with-collectdclient-lib-dir=<path>." >&2;}
  else
