- update nautilus to 2.20.0 - re-word DESCR - install .desktop file
ok martynas@

diff --git a/x11/gnome/nautilus/patches/patch-configure b/x11/gnome/nautilus/patches/patch-configure
--- a/x11/gnome/nautilus/patches/patch-configure
+++ b/x11/gnome/nautilus/patches/patch-configure
@@ -1,21 +1,139 @@
-$OpenBSD: patch-configure,v 1.7 2007/05/12 16:15:12 jasper Exp $
---- configure.orig	Tue Apr 10 14:57:54 2007
-+++ configure	Fri Apr 20 20:48:51 2007
-@@ -24899,7 +24899,7 @@ fi
+$OpenBSD: patch-configure,v 1.8 2007/11/10 15:48:01 jasper Exp $
+--- configure.orig	Tue Sep 18 09:01:42 2007
++++ configure	Fri Oct 26 02:45:45 2007
+@@ -24123,135 +24123,12 @@ done
+ if test "$ac_cv_func_statfs" = yes ; then
+   { echo "$as_me:$LINENO: checking number of arguments to statfs()" >&5
+ echo $ECHO_N "checking number of arguments to statfs()... $ECHO_C" >&6; }
+-  cat >conftest.$ac_ext <<_ACEOF
+-/* confdefs.h.  */
+-_ACEOF
+-cat confdefs.h >>conftest.$ac_ext
+-cat >>conftest.$ac_ext <<_ACEOF
+-/* end confdefs.h.  */
+-#include <unistd.h>
+-  #ifdef HAVE_SYS_PARAM_H
+-  #include <sys/param.h>
+-  #endif
+-  #ifdef HAVE_SYS_VFS_H
+-  #include <sys/vfs.h>
+-  #endif
+-  #ifdef HAVE_SYS_MOUNT_H
+-  #include <sys/mount.h>
+-  #endif
+-  #ifdef HAVE_SYS_STATFS_H
+-  #include <sys/statfs.h>
+-  #endif
+-int
+-main ()
+-{
+-struct statfs st;
+-  statfs(NULL, &st);
+-  ;
+-  return 0;
+-}
+-_ACEOF
+-rm -f conftest.$ac_objext
+-if { (ac_try="$ac_compile"
+-case "(($ac_try" in
+-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+-  *) ac_try_echo=$ac_try;;
+-esac
+-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+-  (eval "$ac_compile") 2>conftest.er1
+-  ac_status=$?
+-  grep -v '^ *+' conftest.er1 >conftest.err
+-  rm -f conftest.er1
+-  cat conftest.err >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); } && {
+-	 test -z "$ac_c_werror_flag" ||
+-	 test ! -s conftest.err
+-       } && test -s conftest.$ac_objext; then
  
- 
- 
+-    { echo "$as_me:$LINENO: result: 2" >&5
+-echo "${ECHO_T}2" >&6; }
 -
-+if 0; then
- echo "$as_me:$LINENO: checking for libExif" >&5
- echo $ECHO_N "checking for libExif... $ECHO_C" >&6
+ cat >>confdefs.h <<\_ACEOF
+ #define STATFS_ARGS 2
+ _ACEOF
  
-@@ -25228,7 +25228,7 @@ _ACEOF
- 
- 
+-else
+-  echo "$as_me: failed program was:" >&5
+-sed 's/^/| /' conftest.$ac_ext >&5
+-
+-
+-    cat >conftest.$ac_ext <<_ACEOF
+-/* confdefs.h.  */
+-_ACEOF
+-cat confdefs.h >>conftest.$ac_ext
+-cat >>conftest.$ac_ext <<_ACEOF
+-/* end confdefs.h.  */
+-#include <unistd.h>
+-  #ifdef HAVE_SYS_PARAM_H
+-  #include <sys/param.h>
+-  #endif
+-  #ifdef HAVE_SYS_VFS_H
+-  #include <sys/vfs.h>
+-  #endif
+-  #ifdef HAVE_SYS_MOUNT_H
+-  #include <sys/mount.h>
+-  #endif
+-  #ifdef HAVE_SYS_STATFS_H
+-  #include <sys/statfs.h>
+-  #endif
+-int
+-main ()
+-{
+-struct statfs st;
+-  statfs(NULL, &st, sizeof (st), 0);
+-  ;
+-  return 0;
+-}
+-_ACEOF
+-rm -f conftest.$ac_objext
+-if { (ac_try="$ac_compile"
+-case "(($ac_try" in
+-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+-  *) ac_try_echo=$ac_try;;
+-esac
+-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+-  (eval "$ac_compile") 2>conftest.er1
+-  ac_status=$?
+-  grep -v '^ *+' conftest.er1 >conftest.err
+-  rm -f conftest.er1
+-  cat conftest.err >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); } && {
+-	 test -z "$ac_c_werror_flag" ||
+-	 test ! -s conftest.err
+-       } && test -s conftest.$ac_objext; then
+-
+-      { echo "$as_me:$LINENO: result: 4" >&5
+-echo "${ECHO_T}4" >&6; }
+-
+-cat >>confdefs.h <<\_ACEOF
+-#define STATFS_ARGS 4
+-_ACEOF
+-
+-else
+-  echo "$as_me: failed program was:" >&5
+-sed 's/^/| /' conftest.$ac_ext >&5
+-
+-
+-      { echo "$as_me:$LINENO: result: unknown" >&5
+-echo "${ECHO_T}unknown" >&6; }
+-      { { echo "$as_me:$LINENO: error: unable to determine number of arguments to statfs()" >&5
+-echo "$as_me: error: unable to determine number of arguments to statfs()" >&2;}
+-   { (exit 1); exit 1; }; }
  fi
 -
-+fi
+-rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+-fi
+-
+-rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+-fi
+-
  
- 
- 
+ x_libs="`$PKG_CONFIG --libs pangox`"
+ case x_libs in
