update to whisper.cpp-1.8.2

diff --git a/audio/whisper.cpp/patches/patch-models_download-ggml-model_sh b/audio/whisper.cpp/patches/patch-models_download-ggml-model_sh
--- a/audio/whisper.cpp/patches/patch-models_download-ggml-model_sh
+++ b/audio/whisper.cpp/patches/patch-models_download-ggml-model_sh
@@ -12,21 +12,13 @@ Index: models/download-ggml-model.sh
  
  # get the path of this script
  get_script_path() {
-@@ -117,16 +117,7 @@ if [ -f "ggml-$model.bin" ]; then
-     exit 0
+@@ -124,8 +124,7 @@ elif [ -x "$(command -v curl)" ]; then
+ elif [ -x "$(command -v wget)" ]; then
+     wget --no-config --quiet --show-progress -O ggml-"$model".bin $src/$pfx-"$model".bin
+ else
+-    printf "Either wget2, curl, or wget is required to download models.\n"
+-    exit 1
++    ftp -mV -o ggml-"$model".bin $src/$pfx-"$model".bin
  fi
  
--if [ -x "$(command -v wget2)" ]; then
--    wget2 --no-config --progress bar -O ggml-"$model".bin $src/$pfx-"$model".bin
--elif [ -x "$(command -v wget)" ]; then
--    wget --no-config --quiet --show-progress -O ggml-"$model".bin $src/$pfx-"$model".bin
--elif [ -x "$(command -v curl)" ]; then
--    curl -L --output ggml-"$model".bin $src/$pfx-"$model".bin
--else
--    printf "Either wget or curl is required to download models.\n"
--    exit 1
--fi
-+ftp -o ggml-"$model".bin $src/$pfx-"$model".bin
- 
  if [ $? -ne 0 ]; then
-     printf "Failed to download ggml model %s \n" "$model"
