Use customary framework for INSTALL/DEINSTALL scripts; fixes INSTALL. ok jakob@

diff --git a/www/php3/pkg/INSTALL b/www/php3/pkg/INSTALL
--- a/www/php3/pkg/INSTALL
+++ b/www/php3/pkg/INSTALL
@@ -1,18 +1,47 @@
 #!/bin/sh
 #
-# $OpenBSD: INSTALL,v 1.1 2000/04/17 19:29:48 jakob Exp $
+# $OpenBSD: INSTALL,v 1.2 2000/12/15 13:29:33 naddy Exp $
 #
 # php3 installation
 
+# exit on errors, use a sane path and install prefix
+#
 set -e
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+PREFIX=${PKG_PREFIX:-/usr/local}
 
-echo
-echo "+---------------"
-echo "| To finish the install, you need to enable the php3"
-echo "| module using the following command"
-echo "|"
-echo "|   ${PKG_PREFIX}/sbin/php3-enable"
-echo "+---------------"
-echo
+do_notice()
+{
+    echo
+    echo "+---------------"
+    echo "| To finish the install, you need to enable the php3"
+    echo "| module using the following command"
+    echo "|"
+    echo "|       $PREFIX/sbin/php3-enable"
+    echo "+---------------"
+    echo
+}
+
+# verify proper execution
+#
+if [ $# -ne 2 ]; then
+    echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
+    exit 1
+fi
+
+# Verify/process the command
+#
+case $2 in
+    PRE-INSTALL)
+	: nothing to pre-install for this port
+	;;
+    POST-INSTALL)
+	do_notice $1
+	;;
+    *)
+	echo "usage: $0 distname { PRE-INSTALL | POST-INSTALL }" >&2
+	exit 1
+	;;
+esac
 
 exit 0
