Maintenance update to foo2zjs-20111020.

diff --git a/print/foo2zjs/patches/patch-Makefile b/print/foo2zjs/patches/patch-Makefile
--- a/print/foo2zjs/patches/patch-Makefile
+++ b/print/foo2zjs/patches/patch-Makefile
@@ -1,6 +1,6 @@
-$OpenBSD: patch-Makefile,v 1.13 2011/07/09 00:36:11 ajacoutot Exp $
---- Makefile.orig	Thu Jun  9 16:07:08 2011
-+++ Makefile	Sat Jul  9 02:27:50 2011
+$OpenBSD: patch-Makefile,v 1.14 2011/10/22 23:00:31 ajacoutot Exp $
+--- Makefile.orig	Sun Jul 31 15:28:43 2011
++++ Makefile	Sun Oct 23 00:55:25 2011
 @@ -16,11 +16,6 @@ SYSNAME := $(shell uname -n)
  # No version number yet...
  VERSION=0.0
@@ -47,7 +47,20 @@ $OpenBSD: patch-Makefile,v 1.13 2011/07/09 00:36:11 ajacoutot Exp $
  #CFLAGS +=	-g
  
  #
-@@ -548,7 +543,7 @@ zjsdecode: zjsdecode.o $(LIBJBG)
+@@ -406,12 +401,6 @@ all-test:
+ 	    echo "      ***"; \
+ 	    exit 1; \
+ 	fi
+-	@if ! dc -V >/dev/null 2>&1; then \
+-	    echo "      ***"; \
+-	    echo "      *** Error: must install GNU dc with the -e option!"; \
+-	    echo "      ***"; \
+-	    exit 1; \
+-	fi
+ ifeq ($(UNAME),Darwin)
+ 	@if ! type gsed >/dev/null 2>&1; then \
+ 	    echo "      ***"; \
+@@ -564,7 +553,7 @@ zjsdecode: zjsdecode.o $(LIBJBG)
  	$(CC) $(CFLAGS) zjsdecode.o $(LIBJBG) -o $@
  
  command2foo2lava-pjl: command2foo2lava-pjl.o
@@ -56,7 +69,7 @@ $OpenBSD: patch-Makefile,v 1.13 2011/07/09 00:36:11 ajacoutot Exp $
  
  command2foo2lava-pjl.o: command2foo2lava-pjl.c
  	$(CC) $(CFLAGS) -I/usr/local/include -c command2foo2lava-pjl.c
-@@ -556,9 +551,8 @@ command2foo2lava-pjl.o: command2foo2lava-pjl.c
+@@ -572,9 +561,8 @@ command2foo2lava-pjl.o: command2foo2lava-pjl.c
  #
  # Installation rules
  #
@@ -67,7 +80,7 @@ $OpenBSD: patch-Makefile,v 1.13 2011/07/09 00:36:11 ajacoutot Exp $
  	    install-man install-doc
  	#
  	# If you use CUPS, then restart the spooler:
-@@ -615,11 +609,6 @@ install-prog:
+@@ -631,11 +619,6 @@ install-prog:
  	$(INSTALL) -d $(SHAREZJS)/
  	$(INSTALL) -c -m 644 gamma.ps $(SHAREZJS)/
  	$(INSTALL) -c -m 644 gamma-lookup.ps $(SHAREZJS)/
@@ -79,7 +92,7 @@ $OpenBSD: patch-Makefile,v 1.13 2011/07/09 00:36:11 ajacoutot Exp $
  
  install-foo:
  	#
-@@ -637,24 +626,14 @@ install-foo:
+@@ -653,24 +636,14 @@ install-foo:
  	#
  	# Install current database files
  	#
@@ -106,7 +119,7 @@ $OpenBSD: patch-Makefile,v 1.13 2011/07/09 00:36:11 ajacoutot Exp $
  	#
  	# Clear foomatic cache and rebuild database if needed
  	#
-@@ -783,50 +762,16 @@ install-extra:
+@@ -799,50 +772,16 @@ install-extra:
  	    fi; \
  	done
  
@@ -161,7 +174,7 @@ $OpenBSD: patch-Makefile,v 1.13 2011/07/09 00:36:11 ajacoutot Exp $
  	    rm -f $(LOCALMODEL)/KonicaMinolta*; \
  	    cd PPD; \
  	    for ppd in *.ppd; do \
-@@ -1389,11 +1334,8 @@ install-doc: doc
+@@ -1405,11 +1344,8 @@ install-doc: doc
  	#
  	$(INSTALL) -d -m 755 $(DOCDIR)
  	$(INSTALL) -c -m 644 manual.pdf $(DOCDIR)
