MAJOR update to zarafa-7.0.0 (RC1). Committing now because this version performs _much_ better than what we currently have in tree (see HOMEPAGE for details).
Quick&dirty upgrade steps (but you should follow the README):
------------------------------------------------------------------------
# /etc/rc.d/zarafa stop
===> Make sure _all_ zarafa processes are stopped and BACKUP YOUR DB!
# pkg_add -u zarafa zarafa-webaccess zarafa-libvmime
===> merge configuration (compare /usr/local/share/examples/zarara/*.cfg
with their counterparts under /etc/zarafa/.
# /usr/local/bin/zarafa-server
===> this will only do sanity checks but not start the server
# pkg_add py-mysql
# python2.6 /usr/local/share/doc/zarafa/zarafa7-upgrade
# /etc/rc.d/zarafa start
------------------------------------------------------------------------

tested by robert@ and myself
ok robert@

diff --git a/mail/zarafa/zarafa/patches/patch-configure b/mail/zarafa/zarafa/patches/patch-configure
--- a/mail/zarafa/zarafa/patches/patch-configure
+++ b/mail/zarafa/zarafa/patches/patch-configure
@@ -1,63 +1,10 @@
-$OpenBSD: patch-configure,v 1.13 2011/05/19 17:18:18 ajacoutot Exp $
---- configure.orig	Thu May 19 12:23:58 2011
-+++ configure	Thu May 19 18:30:36 2011
-@@ -21807,12 +21807,7 @@ else
-   want_release=no
- fi
+$OpenBSD: patch-configure,v 1.14 2011/06/02 12:46:37 ajacoutot Exp $
+--- configure.orig	Wed Apr 20 16:39:39 2011
++++ configure	Sun May 29 09:27:20 2011
+@@ -21919,13 +21919,13 @@ fi
  
--if test "$want_release" = "yes"; then
--    CXXFLAGS="$CXXFLAGS -O2 -fno-strict-aliasing"
--else
--# -fPIC must be present on x86_64 when -O2 isn't used
-     CXXFLAGS="$CXXFLAGS -fPIC"
--fi
- 
- # Check whether --enable-tcmalloc was given.
- if test "${enable_tcmalloc+set}" = set; then
-@@ -21840,7 +21835,7 @@ else
-   with_distro=rhel
- fi
- 
--if test "$with_distro" != "rhel" -a "$with_distro" != "suse" -a "$with_distro" != "sles"; then
-+if test "$with_distro" != "rhel" -a "$with_distro" != "suse" -a "$with_distro" != "sles" -a "$with_distro" != "openbsd"; then
-    { echo "$as_me:$LINENO: result: invalid distro, using rhel instead" >&5
- echo "${ECHO_T}invalid distro, using rhel instead" >&6; }
- else
-@@ -22180,21 +22175,6 @@ echo "$as_me: error: Cannot execute $PHP_CONFIG" >&2;}
-   PHP_LDFLAGS=`$PHP_CONFIG --ldflags`
-   PHP_EXTENSION_DIR=`$PHP_CONFIG --extension-dir`
-   PHP_VERSION=`$PHP_CONFIG --version`
--  # watch escaping for brackets
--  PHP_SYSCONF_DIR=`$PHP_CONFIG --configure-options | sed -e 's_.*with-config-file-scan-dir=\([^ ]\+\).*_\1_'`
--  if test ${PHP_SYSCONF_DIR:0:1} != "/"; then
--	# find path in existing paths
--	if test -d "/etc/php.d"; then
--		PHP_SYSCONF_DIR="/etc/php.d"
--	elif test -d "/etc/php5/conf.d"; then
--		PHP_SYSCONF_DIR="/etc/php5/conf.d"
--	else
--		# this happens on old distributions
--	    { echo "$as_me:$LINENO: result: Cannot find php sysconf path, forcing /usr/share/doc/zarafa" >&5
--echo "${ECHO_T}Cannot find php sysconf path, forcing /usr/share/doc/zarafa" >&6; }
--		PHP_SYSCONF_DIR="/usr/share/doc/zarafa"
--	fi
--  fi
- 
-   if test -z "$PHP_EXTENSION_DIR"; then
-     { { echo "$as_me:$LINENO: error: Cannot find php-config. Please use --with-php-config=PATH" >&5
-@@ -22720,7 +22700,7 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
- _ACEOF
- 
- 		VMIME_CFLAGS=-I$VMIME_PREFIX
--	VMIME_LIBS="-lvmime"
-+	VMIME_LIBS="${ZAFARA_LDFLAGS} -lvmime-zarafa"
- 
- else
- 
-@@ -26092,13 +26072,13 @@ LIBS=$libs_keep
- libs_keep=$LIBS
- # check lib, but do not set in link list
- 
+ # Everything uses pthread
+ # check lib, but do not set in link list, but use -pthread instead (gnu c/c++ only?)
 -{ echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
 -echo $ECHO_N "checking for pthread_create in -lpthread... $ECHO_C" >&6; }
 +{ echo "$as_me:$LINENO: checking for pthread_create in -pthread" >&5
@@ -71,12 +18,92 @@ $OpenBSD: patch-configure,v 1.13 2011/05/19 17:18:18 ajacoutot Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -26158,7 +26138,7 @@ if test $ac_cv_lib_pthread_pthread_create = yes; then
- #define HAVE_LIBPTHREAD 1
+@@ -22044,7 +22044,7 @@ else
+   with_distro=rhel
+ fi
+ 
+-if test "$with_distro" != "rhel" -a "$with_distro" != "suse" -a "$with_distro" != "sles"; then
++if test "$with_distro" != "rhel" -a "$with_distro" != "suse" -a "$with_distro" != "sles" -a "$with_distro" != "openbsd"; then
+    { echo "$as_me:$LINENO: result: invalid distro, using rhel instead" >&5
+ echo "${ECHO_T}invalid distro, using rhel instead" >&6; }
+    with_distro=rhel
+@@ -24444,7 +24444,7 @@ if test "${ac_cv_lib_intl_strftime+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+-LIBS="-lintl  $LIBS"
++LIBS="-lintl -liconv $LIBS"
+ cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+ _ACEOF
+@@ -24504,7 +24504,7 @@ if test $ac_cv_lib_intl_strftime = yes; then
+ #define HAVE_STRFTIME 1
  _ACEOF
  
--  LIBS="-lpthread $LIBS"
-+  LIBS="-pthread $LIBS"
+-LIBS="-lintl $LIBS"
++LIBS="-lintl -liconv $LIBS"
+ fi
+ 
+ fi
+@@ -26018,7 +26018,7 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
+ _ACEOF
+ 
+ 		VMIME_CFLAGS=-I$VMIME_PREFIX
+-	VMIME_LIBS="$VMIME_LIBS -lvmime"
++	VMIME_LIBS="$VMIME_LIBS -lvmime-zarafa"
  
  else
-   { { echo "$as_me:$LINENO: error: required library libpthread missing or unusable" >&5
+ 
+@@ -27535,13 +27535,13 @@ sed 's/^/| /' conftest.$ac_ext >&5
+ 	 { echo "$as_me:$LINENO: result: no" >&5
+ echo "${ECHO_T}no" >&6; }
+ 
+-{ echo "$as_me:$LINENO: checking for crypt in -lcrypt" >&5
+-echo $ECHO_N "checking for crypt in -lcrypt... $ECHO_C" >&6; }
++{ echo "$as_me:$LINENO: checking for crypt in -lcrypto" >&5
++echo $ECHO_N "checking for crypt in -lcrypto... $ECHO_C" >&6; }
+ if test "${ac_cv_lib_crypt_crypt+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+-LIBS="-lcrypt  $LIBS"
++LIBS="-lcrypto  $LIBS"
+ cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+ _ACEOF
+@@ -27601,7 +27601,7 @@ if test $ac_cv_lib_crypt_crypt = yes; then
+ #define HAVE_LIBCRYPT 1
+ _ACEOF
+ 
+-  LIBS="-lcrypt $LIBS"
++  LIBS="-lcrypto $LIBS"
+ 
+ else
+   { { echo "$as_me:$LINENO: error: required library libcrypt missing or unusable" >&5
+@@ -27695,7 +27695,7 @@ if test "${ac_cv_lib_ssl_SSL_accept+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+-LIBS="-lssl  $LIBS"
++LIBS="-lssl -lcrypto $LIBS"
+ cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+ _ACEOF
+@@ -28802,7 +28802,7 @@ if test "${ac_cv_lib_intl_gettext+set}" = set; then
+   echo $ECHO_N "(cached) $ECHO_C" >&6
+ else
+   ac_check_lib_save_LIBS=$LIBS
+-LIBS="-lintl  $LIBS"
++LIBS="-lintl -liconv $LIBS"
+ cat >conftest.$ac_ext <<_ACEOF
+ /* confdefs.h.  */
+ _ACEOF
+@@ -28858,7 +28858,7 @@ fi
+ { echo "$as_me:$LINENO: result: $ac_cv_lib_intl_gettext" >&5
+ echo "${ECHO_T}$ac_cv_lib_intl_gettext" >&6; }
+ if test $ac_cv_lib_intl_gettext = yes; then
+-  INTL_LIBS="-lintl"
++  INTL_LIBS="-lintl -liconv"
+ else
+       { { echo "$as_me:$LINENO: error: required library libintl missing or unusable" >&5
+ echo "$as_me: error: required library libintl missing or unusable" >&2;}
