Update zarafa to version 6.40.1. See http://download.zarafa.com/zarafa/release/docs/changelog.en.txt for details.

diff --git a/mail/zarafa/zarafa/patches/patch-configure b/mail/zarafa/zarafa/patches/patch-configure
--- a/mail/zarafa/zarafa/patches/patch-configure
+++ b/mail/zarafa/zarafa/patches/patch-configure
@@ -1,7 +1,7 @@
-$OpenBSD: patch-configure,v 1.7 2010/06/30 02:46:48 ajacoutot Exp $
---- configure.orig	Mon May 31 16:37:57 2010
-+++ configure	Tue Jun 29 03:42:19 2010
-@@ -21781,12 +21781,7 @@ else
+$OpenBSD: patch-configure,v 1.8 2010/08/22 10:13:27 ajacoutot Exp $
+--- configure.orig	Tue Aug  3 11:42:48 2010
++++ configure	Sun Aug 22 10:22:53 2010
+@@ -21780,12 +21780,7 @@ else
    want_release=no
  fi
  
@@ -14,7 +14,7 @@ $OpenBSD: patch-configure,v 1.7 2010/06/30 02:46:48 ajacoutot Exp $
  
  # Check whether --enable-tcmalloc was given.
  if test "${enable_tcmalloc+set}" = set; then
-@@ -21814,7 +21809,7 @@ else
+@@ -21813,7 +21808,7 @@ else
    with_distro=rhel
  fi
  
@@ -23,7 +23,7 @@ $OpenBSD: patch-configure,v 1.7 2010/06/30 02:46:48 ajacoutot Exp $
     { echo "$as_me:$LINENO: result: invalid distro, using rhel instead" >&5
  echo "${ECHO_T}invalid distro, using rhel instead" >&6; }
  else
-@@ -22154,21 +22149,6 @@ echo "$as_me: error: Cannot execute $PHP_CONFIG" >&2;}
+@@ -22153,21 +22148,6 @@ echo "$as_me: error: Cannot execute $PHP_CONFIG" >&2;}
    PHP_LDFLAGS=`$PHP_CONFIG --ldflags`
    PHP_EXTENSION_DIR=`$PHP_CONFIG --extension-dir`
    PHP_VERSION=`$PHP_CONFIG --version`
@@ -45,7 +45,7 @@ $OpenBSD: patch-configure,v 1.7 2010/06/30 02:46:48 ajacoutot Exp $
  
    if test -z "$PHP_EXTENSION_DIR"; then
      { { echo "$as_me:$LINENO: error: Cannot find php-config. Please use --with-php-config=PATH" >&5
-@@ -22694,7 +22674,7 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
+@@ -22693,7 +22673,7 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
  _ACEOF
  
  		VMIME_CFLAGS=-I$VMIME_PREFIX
@@ -54,9 +54,9 @@ $OpenBSD: patch-configure,v 1.7 2010/06/30 02:46:48 ajacoutot Exp $
  
  else
  
-@@ -23369,8 +23349,10 @@ else
-   WITH_CLUCENE_FALSE=
- fi
+@@ -23103,8 +23083,10 @@ fi
+ 
+ done
  
 +# XXX force removing clucene support
 +WITH_CLUCENE_TRUE='#'
@@ -64,9 +64,9 @@ $OpenBSD: patch-configure,v 1.7 2010/06/30 02:46:48 ajacoutot Exp $
  
 -
  CFLAGS=$cflags_keep
- CXXFLAGS=$cxxflags_keep
- ac_ext=c
-@@ -24399,13 +24381,13 @@ LIBS=$libs_keep
+ 
+ # Check for CLucene availability
+@@ -24476,13 +24458,13 @@ LIBS=$libs_keep
  libs_keep=$LIBS
  # check lib, but do not set in link list
  
@@ -83,7 +83,7 @@ $OpenBSD: patch-configure,v 1.7 2010/06/30 02:46:48 ajacoutot Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -24465,7 +24447,7 @@ if test $ac_cv_lib_pthread_pthread_create = yes; then
+@@ -24542,7 +24524,7 @@ if test $ac_cv_lib_pthread_pthread_create = yes; then
  #define HAVE_LIBPTHREAD 1
  _ACEOF
  
