Bugfix update to zarafa-6.40.8. More details at: http://download.zarafa.com/community/final/6.40/changelog-6.40.txt

diff --git a/mail/zarafa/zarafa/patches/patch-configure b/mail/zarafa/zarafa/patches/patch-configure
--- a/mail/zarafa/zarafa/patches/patch-configure
+++ b/mail/zarafa/zarafa/patches/patch-configure
@@ -1,7 +1,7 @@
-$OpenBSD: patch-configure,v 1.12 2011/04/04 08:01:04 ajacoutot Exp $
---- configure.orig	Mon Mar 28 20:32:47 2011
-+++ configure	Sun Apr  3 09:11:19 2011
-@@ -21801,12 +21801,7 @@ else
+$OpenBSD: patch-configure,v 1.13 2011/05/19 17:18:18 ajacoutot Exp $
+--- configure.orig	Thu May 19 12:23:58 2011
++++ configure	Thu May 19 18:30:36 2011
+@@ -21807,12 +21807,7 @@ else
    want_release=no
  fi
  
@@ -14,7 +14,7 @@ $OpenBSD: patch-configure,v 1.12 2011/04/04 08:01:04 ajacoutot Exp $
  
  # Check whether --enable-tcmalloc was given.
  if test "${enable_tcmalloc+set}" = set; then
-@@ -21834,7 +21829,7 @@ else
+@@ -21840,7 +21835,7 @@ else
    with_distro=rhel
  fi
  
@@ -23,7 +23,7 @@ $OpenBSD: patch-configure,v 1.12 2011/04/04 08:01:04 ajacoutot Exp $
     { echo "$as_me:$LINENO: result: invalid distro, using rhel instead" >&5
  echo "${ECHO_T}invalid distro, using rhel instead" >&6; }
  else
-@@ -22174,21 +22169,6 @@ echo "$as_me: error: Cannot execute $PHP_CONFIG" >&2;}
+@@ -22180,21 +22175,6 @@ echo "$as_me: error: Cannot execute $PHP_CONFIG" >&2;}
    PHP_LDFLAGS=`$PHP_CONFIG --ldflags`
    PHP_EXTENSION_DIR=`$PHP_CONFIG --extension-dir`
    PHP_VERSION=`$PHP_CONFIG --version`
@@ -45,7 +45,7 @@ $OpenBSD: patch-configure,v 1.12 2011/04/04 08:01:04 ajacoutot Exp $
  
    if test -z "$PHP_EXTENSION_DIR"; then
      { { echo "$as_me:$LINENO: error: Cannot find php-config. Please use --with-php-config=PATH" >&5
-@@ -22714,7 +22694,7 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
+@@ -22720,7 +22700,7 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
  _ACEOF
  
  		VMIME_CFLAGS=-I$VMIME_PREFIX
@@ -54,7 +54,7 @@ $OpenBSD: patch-configure,v 1.12 2011/04/04 08:01:04 ajacoutot Exp $
  
  else
  
-@@ -25116,13 +25096,13 @@ LIBS=$libs_keep
+@@ -26092,13 +26072,13 @@ LIBS=$libs_keep
  libs_keep=$LIBS
  # check lib, but do not set in link list
  
@@ -71,7 +71,7 @@ $OpenBSD: patch-configure,v 1.12 2011/04/04 08:01:04 ajacoutot Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -25182,7 +25162,7 @@ if test $ac_cv_lib_pthread_pthread_create = yes; then
+@@ -26158,7 +26138,7 @@ if test $ac_cv_lib_pthread_pthread_create = yes; then
  #define HAVE_LIBPTHREAD 1
  _ACEOF
  
