*MAJOR* version update to zarafa-6.40.0. Read the complete changelog here: http://download.zarafa.com/zarafa/release/docs/changelog.en.txt
Upgrade documentation is available at:
http://doc.zarafa.com/6.40/Administrator_Manual/en-US/html-single/index.html#_performing_the_upgrade

zarafa-libical has been removed, current version from ports works fine
for zarafa needs.

php5-mapi has been merged into zarafa-webaccess.

diff --git a/mail/zarafa/zarafa/patches/patch-configure b/mail/zarafa/zarafa/patches/patch-configure
--- a/mail/zarafa/zarafa/patches/patch-configure
+++ b/mail/zarafa/zarafa/patches/patch-configure
@@ -1,7 +1,7 @@
-$OpenBSD: patch-configure,v 1.6 2010/01/09 14:03:25 ajacoutot Exp $
---- configure.orig	Wed Jan  6 04:28:18 2010
-+++ configure	Sat Jan  9 14:10:30 2010
-@@ -21647,12 +21647,7 @@ else
+$OpenBSD: patch-configure,v 1.7 2010/06/30 02:46:48 ajacoutot Exp $
+--- configure.orig	Mon May 31 16:37:57 2010
++++ configure	Tue Jun 29 03:42:19 2010
+@@ -21781,12 +21781,7 @@ else
    want_release=no
  fi
  
@@ -14,7 +14,38 @@ $OpenBSD: patch-configure,v 1.6 2010/01/09 14:03:25 ajacoutot Exp $
  
  # Check whether --enable-tcmalloc was given.
  if test "${enable_tcmalloc+set}" = set; then
-@@ -22494,7 +22489,7 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
+@@ -21814,7 +21809,7 @@ else
+   with_distro=rhel
+ fi
+ 
+-if test "$with_distro" != "rhel" -a "$with_distro" != "suse" -a "$with_distro" != "sles"; then
++if test "$with_distro" != "rhel" -a "$with_distro" != "suse" -a "$with_distro" != "sles" -a "$with_distro" != "openbsd"; then
+    { echo "$as_me:$LINENO: result: invalid distro, using rhel instead" >&5
+ echo "${ECHO_T}invalid distro, using rhel instead" >&6; }
+ else
+@@ -22154,21 +22149,6 @@ echo "$as_me: error: Cannot execute $PHP_CONFIG" >&2;}
+   PHP_LDFLAGS=`$PHP_CONFIG --ldflags`
+   PHP_EXTENSION_DIR=`$PHP_CONFIG --extension-dir`
+   PHP_VERSION=`$PHP_CONFIG --version`
+-  # watch escaping for brackets
+-  PHP_SYSCONF_DIR=`$PHP_CONFIG --configure-options | sed -e 's_.*with-config-file-scan-dir=\([^ ]\+\).*_\1_'`
+-  if test ${PHP_SYSCONF_DIR:0:1} != "/"; then
+-	# find path in existing paths
+-	if test -d "/etc/php.d"; then
+-		PHP_SYSCONF_DIR="/etc/php.d"
+-	elif test -d "/etc/php5/conf.d"; then
+-		PHP_SYSCONF_DIR="/etc/php5/conf.d"
+-	else
+-		# this happens on old distributions
+-	    { echo "$as_me:$LINENO: result: Cannot find php sysconf path, forcing /usr/share/doc/zarafa" >&5
+-echo "${ECHO_T}Cannot find php sysconf path, forcing /usr/share/doc/zarafa" >&6; }
+-		PHP_SYSCONF_DIR="/usr/share/doc/zarafa"
+-	fi
+-  fi
+ 
+   if test -z "$PHP_EXTENSION_DIR"; then
+     { { echo "$as_me:$LINENO: error: Cannot find php-config. Please use --with-php-config=PATH" >&5
+@@ -22694,7 +22674,7 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
  _ACEOF
  
  		VMIME_CFLAGS=-I$VMIME_PREFIX
@@ -23,16 +54,19 @@ $OpenBSD: patch-configure,v 1.6 2010/01/09 14:03:25 ajacoutot Exp $
  
  else
  
-@@ -22897,7 +22892,7 @@ if test `eval echo '${'$as_ac_Header'}'` = yes; then
- #define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
- _ACEOF
-   ICAL_CFLAGS=-I$ICAL_PREFIX
--	ICAL_LIBS="-lical -licalss"
-+	ICAL_LIBS="${ZAFARA_LDFLAGS} -lical-zarafa -licalss-zarafa"
- else
-   WITH_ICAL=no
+@@ -23369,8 +23349,10 @@ else
+   WITH_CLUCENE_FALSE=
  fi
-@@ -23766,13 +23761,13 @@ LIBS=$libs_keep
+ 
++# XXX force removing clucene support
++WITH_CLUCENE_TRUE='#'
++WITH_CLUCENE_FALSE=
+ 
+-
+ CFLAGS=$cflags_keep
+ CXXFLAGS=$cxxflags_keep
+ ac_ext=c
+@@ -24399,13 +24381,13 @@ LIBS=$libs_keep
  libs_keep=$LIBS
  # check lib, but do not set in link list
  
@@ -49,7 +83,7 @@ $OpenBSD: patch-configure,v 1.6 2010/01/09 14:03:25 ajacoutot Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -23832,7 +23827,7 @@ if test $ac_cv_lib_pthread_pthread_create = yes; then
+@@ -24465,7 +24447,7 @@ if test $ac_cv_lib_pthread_pthread_create = yes; then
  #define HAVE_LIBPTHREAD 1
  _ACEOF
  
