OpenBSD does not require -lcrypt, DES encryption is part of the standard libc.

diff --git a/mail/zarafa/zarafa/patches/patch-configure b/mail/zarafa/zarafa/patches/patch-configure
--- a/mail/zarafa/zarafa/patches/patch-configure
+++ b/mail/zarafa/zarafa/patches/patch-configure
@@ -1,6 +1,9 @@
-$OpenBSD: patch-configure,v 1.18 2011/12/22 17:10:04 ajacoutot Exp $
+$OpenBSD: patch-configure,v 1.19 2012/01/12 14:17:23 ajacoutot Exp $
+
+OpenBSD does NOT require -lcrypt, DES encryption is part of the standard libc.
+
 --- configure.orig	Wed Dec 21 20:17:32 2011
-+++ configure	Thu Dec 22 12:14:19 2011
++++ configure	Thu Jan 12 14:51:50 2012
 @@ -21934,13 +21934,13 @@ fi
  
  # Everything uses pthread
@@ -45,33 +48,93 @@ $OpenBSD: patch-configure,v 1.18 2011/12/22 17:10:04 ajacoutot Exp $
  
  else
  
-@@ -27552,13 +27552,13 @@ sed 's/^/| /' conftest.$ac_ext >&5
+@@ -27552,84 +27552,10 @@ sed 's/^/| /' conftest.$ac_ext >&5
  	 { echo "$as_me:$LINENO: result: no" >&5
  echo "${ECHO_T}no" >&6; }
  
 -{ echo "$as_me:$LINENO: checking for crypt in -lcrypt" >&5
 -echo $ECHO_N "checking for crypt in -lcrypt... $ECHO_C" >&6; }
-+{ echo "$as_me:$LINENO: checking for crypt in -lcrypto" >&5
-+echo $ECHO_N "checking for crypt in -lcrypto... $ECHO_C" >&6; }
- if test "${ac_cv_lib_crypt_crypt+set}" = set; then
-   echo $ECHO_N "(cached) $ECHO_C" >&6
- else
-   ac_check_lib_save_LIBS=$LIBS
+-if test "${ac_cv_lib_crypt_crypt+set}" = set; then
+-  echo $ECHO_N "(cached) $ECHO_C" >&6
+-else
+-  ac_check_lib_save_LIBS=$LIBS
 -LIBS="-lcrypt  $LIBS"
-+LIBS="-lcrypto  $LIBS"
- cat >conftest.$ac_ext <<_ACEOF
- /* confdefs.h.  */
- _ACEOF
-@@ -27618,7 +27618,7 @@ if test $ac_cv_lib_crypt_crypt = yes; then
- #define HAVE_LIBCRYPT 1
- _ACEOF
- 
+-cat >conftest.$ac_ext <<_ACEOF
+-/* confdefs.h.  */
+-_ACEOF
+-cat confdefs.h >>conftest.$ac_ext
+-cat >>conftest.$ac_ext <<_ACEOF
+-/* end confdefs.h.  */
+-
+-/* Override any GCC internal prototype to avoid an error.
+-   Use char because int might match the return type of a GCC
+-   builtin and then its argument prototype would still apply.  */
+-#ifdef __cplusplus
+-extern "C"
+-#endif
+-char crypt ();
+-int
+-main ()
+-{
+-return crypt ();
+-  ;
+-  return 0;
+-}
+-_ACEOF
+-rm -f conftest.$ac_objext conftest$ac_exeext
+-if { (ac_try="$ac_link"
+-case "(($ac_try" in
+-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+-  *) ac_try_echo=$ac_try;;
+-esac
+-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+-  (eval "$ac_link") 2>conftest.er1
+-  ac_status=$?
+-  grep -v '^ *+' conftest.er1 >conftest.err
+-  rm -f conftest.er1
+-  cat conftest.err >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); } && {
+-	 test -z "$ac_cxx_werror_flag" ||
+-	 test ! -s conftest.err
+-       } && test -s conftest$ac_exeext &&
+-       $as_test_x conftest$ac_exeext; then
+-  ac_cv_lib_crypt_crypt=yes
+-else
+-  echo "$as_me: failed program was:" >&5
+-sed 's/^/| /' conftest.$ac_ext >&5
+-
+-	ac_cv_lib_crypt_crypt=no
+ fi
+-
++        
+ rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+       conftest$ac_exeext conftest.$ac_ext
+-LIBS=$ac_check_lib_save_LIBS
+-fi
+-{ echo "$as_me:$LINENO: result: $ac_cv_lib_crypt_crypt" >&5
+-echo "${ECHO_T}$ac_cv_lib_crypt_crypt" >&6; }
+-if test $ac_cv_lib_crypt_crypt = yes; then
+-  cat >>confdefs.h <<_ACEOF
+-#define HAVE_LIBCRYPT 1
+-_ACEOF
+-
 -  LIBS="-lcrypt $LIBS"
-+  LIBS="-lcrypto $LIBS"
+-
+-else
+-  { { echo "$as_me:$LINENO: error: required library libcrypt missing or unusable" >&5
+-echo "$as_me: error: required library libcrypt missing or unusable" >&2;}
+-   { (exit 1); exit 1; }; }
+-fi
+-
+-fi
+-
+-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+-      conftest$ac_exeext conftest.$ac_ext
+ CRYPT_LIBS=$LIBS
+ LIBS=$LIBS_system
  
- else
-   { { echo "$as_me:$LINENO: error: required library libcrypt missing or unusable" >&5
-@@ -27644,7 +27644,7 @@ if test "${ac_cv_lib_ssl_SSL_accept+set}" = set; then
+@@ -27644,7 +27570,7 @@ if test "${ac_cv_lib_ssl_SSL_accept+set}" = set; then
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
    ac_check_lib_save_LIBS=$LIBS
@@ -80,7 +143,7 @@ $OpenBSD: patch-configure,v 1.18 2011/12/22 17:10:04 ajacoutot Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -28820,7 +28820,7 @@ if test "${ac_cv_lib_intl_gettext+set}" = set; then
+@@ -28820,7 +28746,7 @@ if test "${ac_cv_lib_intl_gettext+set}" = set; then
    echo $ECHO_N "(cached) $ECHO_C" >&6
  else
    ac_check_lib_save_LIBS=$LIBS
@@ -89,7 +152,7 @@ $OpenBSD: patch-configure,v 1.18 2011/12/22 17:10:04 ajacoutot Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -28876,7 +28876,7 @@ fi
+@@ -28876,7 +28802,7 @@ fi
  { echo "$as_me:$LINENO: result: $ac_cv_lib_intl_gettext" >&5
  echo "${ECHO_T}$ac_cv_lib_intl_gettext" >&6; }
  if test $ac_cv_lib_intl_gettext = yes; then
