- rearrange - fix comment

diff --git a/security/ssh/pkg/INSTALL b/security/ssh/pkg/INSTALL
--- a/security/ssh/pkg/INSTALL
+++ b/security/ssh/pkg/INSTALL
@@ -1,7 +1,14 @@
 #!/bin/sh
-# $OpenBSD: INSTALL,v 1.1 1999/04/08 05:36:12 marc Exp $
+# $OpenBSD: INSTALL,v 1.2 2000/03/25 05:52:39 brad Exp $
 #
 # Pre/post-installation setup of ssh
+
+# exit on errors, use a sane path and install prefix
+#
+set -e
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+PREFIX=${PKG_PREFIX:-/usr/local}
+PIDFILE=/var/run/sshd.pid
 
 # Function: tell the user what s/he needs to do to use the port just installed
 #
@@ -13,18 +20,11 @@ do_notice()
     echo "|"
     echo "|        ${PREFIX}/sbin/sshd"
     echo "|"
-    echo "| This is done automatically in the stock /etc/rc.local"
+    echo "| This is done automatically in the stock /etc/rc"
     echo "| whenever you restart your system"
     echo "+---------------"
     echo
 }
-
-# exit on errors, use a sane path and install prefix
-#
-set -e
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
-PREFIX=${PKG_PREFIX:-/usr/local}
-PIDFILE=/var/run/sshd.pid
 
 # verify proper execution
 #
