Patches to fix dynamic libraries, especially on ppc which understands only major/minor.
Add DYNLIBDIR where needed.

Some style issues.

From peter@, brad@ and peter_e@gmx.net

diff --git a/databases/postgresql/pkg/INSTALL b/databases/postgresql/pkg/INSTALL
--- a/databases/postgresql/pkg/INSTALL
+++ b/databases/postgresql/pkg/INSTALL
@@ -1,8 +1,14 @@
 #!/bin/sh
 #
-# $OpenBSD: INSTALL,v 1.3 2001/04/21 18:25:53 peter Exp $
+# $OpenBSD: INSTALL,v 1.4 2001/04/23 21:58:44 espie Exp $
 #
 # Pre/post-installation setup of postgresql
+
+# exit on errors, use a sane path and install prefix
+#
+set -e
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+PREFIX=${PKG_PREFIX:-/usr/local}
 
 # Function: tell the user what s/he needs to do to use the port just installed
 #
@@ -11,17 +17,11 @@ do_notice()
 	echo
 	echo "+---------------"
 	echo "| The $1 package installation completed."
-	echo "| See ${PREFIX}/share/doc/postgresql/README.OpenBSD for"
+	echo "| See $PREFIX/share/doc/postgresql/README.OpenBSD for"
 	echo "| information on using PostgreSQL package in OpenBSD environment."
 	echo "+---------------"
 	echo
 }
-
-# exit on errors, use a sane path and install prefix
-#
-set -e
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
-PREFIX=${PKG_PREFIX:-/usr/local}
 
 # verify proper execution
 #
