Upgrade to postgresql 7.1. ok'd espie@
* The package is now called `postgresql' and not `pgsql'.

* The default user that is suggested for the admin account is also
  `postgresql'. This will work with OpenBSD-current with long username
  support. If anything breaks please report to the maintainers.

* pgwrap is no longer shipped or supported

* Please note, you will HAVE TO BACKUP your old data if you are
  upgrading from a previous release of postgresql. Do this before
  removing the old pgsql package.

From the announcement last weekend:

Key New Features and Capabilities of Version 7.1 Include:

* Write-ahead Log (WAL) increases data integrity and processing
speed. To maintain database consistency in case of an operating
system crash, previous releases of PostgreSQL have forced all all
data modifications to disk before each transaction commit. With
WAL, only one log file must be flushed to disk, greatly improving
performance. (Tech note: can eliminate use of -F in to disable disk
flushes)

* TOAST (The Oversized-Attribute Storage Technique) Past releases
had compiled-in row length limit typically between 8Kb & 32Kb. This
restriction made storage of long text fields difficult, cumbersome
and slow. TOAST enables rows of any length while maintaing the high
performance PostgreSQL users have come to expect.

* SQL92 Outer Joins are now supported. (Tech note: eliminates the
UNION/NOT IN workaround)

* 64-bit C Language Function Manager support The previous C function
manager did not handle support 64-bit CPU's (e.g. Alpha, Sun,
Itanium). (Tech note: This change should not impact existing custom
functions developed for past versions, but performance will be
improved through rewriting to use the new call interface.)

* Complex Queries that are better, stronger and faster Many complex
queries were unsupported in previous releases. With v7.1 combinations
of views, aggregates, UNION, LIMIT, cursors, subqueries, and inherited
tables are enabled. Inherited tables are now accessed by default,
and subqueries in FROM are now supported.

diff --git a/databases/postgresql/pkg/INSTALL b/databases/postgresql/pkg/INSTALL
--- a/databases/postgresql/pkg/INSTALL
+++ b/databases/postgresql/pkg/INSTALL
@@ -1,14 +1,7 @@
 #!/bin/sh
 #
-# $OpenBSD: INSTALL,v 1.2 2001/04/13 07:00:46 brad Exp $
+# $OpenBSD: INSTALL,v 1.3 2001/04/21 18:25:53 peter Exp $
 #
-
-# exit on errors, use a sane path and install prefix
-#
-set -e
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
-PREFIX=${PKG_PREFIX:-/usr/local}
-
 # Pre/post-installation setup of postgresql
 
 # Function: tell the user what s/he needs to do to use the port just installed
@@ -18,11 +11,17 @@ do_notice()
 	echo
 	echo "+---------------"
 	echo "| The $1 package installation completed."
-	echo "| See $PREFIX/share/doc/pgsql/README.OpenBSD for"
+	echo "| See ${PREFIX}/share/doc/postgresql/README.OpenBSD for"
 	echo "| information on using PostgreSQL package in OpenBSD environment."
 	echo "+---------------"
 	echo
 }
+
+# exit on errors, use a sane path and install prefix
+#
+set -e
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+PREFIX=${PKG_PREFIX:-/usr/local}
 
 # verify proper execution
 #
