Update to libvpx-1.7.0. - survived a bulk
from Brad (maintainer)

diff --git a/multimedia/libvpx/patches/patch-configure b/multimedia/libvpx/patches/patch-configure
--- a/multimedia/libvpx/patches/patch-configure
+++ b/multimedia/libvpx/patches/patch-configure
@@ -1,16 +1,25 @@
-$OpenBSD: patch-configure,v 1.15 2018/02/16 14:46:50 ajacoutot Exp $
+$OpenBSD: patch-configure,v 1.16 2018/09/26 07:14:28 ajacoutot Exp $
 Index: configure
 --- configure.orig
 +++ configure
-@@ -113,6 +113,7 @@ all_platforms="${all_platforms} armv7s-darwin-gcc"
- all_platforms="${all_platforms} armv8-linux-gcc"
- all_platforms="${all_platforms} mips32-linux-gcc"
+@@ -116,6 +116,7 @@ all_platforms="${all_platforms} mips32-linux-gcc"
  all_platforms="${all_platforms} mips64-linux-gcc"
+ all_platforms="${all_platforms} ppc64-linux-gcc"
+ all_platforms="${all_platforms} ppc64le-linux-gcc"
 +all_platforms="${all_platforms} sparc-linux-gcc"
  all_platforms="${all_platforms} sparc-solaris-gcc"
  all_platforms="${all_platforms} x86-android-gcc"
  all_platforms="${all_platforms} x86-darwin8-gcc"
-@@ -175,19 +176,6 @@ if [ "`cd \"${source_path}\" && pwd`" != "`pwd`" ]; th
+@@ -170,7 +171,7 @@ for t in ${all_targets}; do
+     [ -f "${source_path}/${t}.mk" ] && enable_feature ${t}
+ done
+ 
+-if ! diff --version >/dev/null; then
++if ! hash diff >/dev/null; then
+   die "diff missing: Try installing diffutils via your package manager."
+ fi
+ 
+@@ -185,19 +186,6 @@ if [ "`cd \"${source_path}\" && pwd`" != "`pwd`" ]; th
    fi
  fi
  
@@ -30,7 +39,7 @@ Index: configure
  # disable codecs when their source directory does not exist
  [ -d "${source_path}/vp8" ] || disable_codec vp8
  [ -d "${source_path}/vp9" ] || disable_codec vp9
-@@ -496,7 +484,7 @@ process_detect() {
+@@ -518,7 +506,7 @@ process_detect() {
          # here rather than at option parse time because the target auto-detect
          # magic happens after the command line has been parsed.
          case "${tgt_os}" in
