Major update to hplip-3.9.6b. Refer to the project homepage for the complete changelog.
This port now comes into 5 subpackages (ala Fedora):
- main: complete hplip functionnalities
- hpijs: deprecated hpijs printer driver
- hpcups: new-gen printer driver
- libs: libraries and helpers used by other subpackages
- gui: graphical tools (systray applet...)

It seems this version works a least as good as the previous one we had
in-tree. I could use some feedbacks for the fancier stuffs that hplip
provides (besides regular printing using hpcups and/or hpijs), like
printer communication, ink levels... because I have no hp equipment, but
at least, there was no regression reported.
(some features are Linux-only and are expected not to work)

Tested by several, thanks!

diff --git a/print/hplip/patches/patch-configure b/print/hplip/patches/patch-configure
--- a/print/hplip/patches/patch-configure
+++ b/print/hplip/patches/patch-configure
@@ -1,29 +1,31 @@
-$OpenBSD: patch-configure,v 1.2 2008/03/15 10:18:30 ajacoutot Exp $
---- configure.orig	Fri Mar  7 09:26:40 2008
-+++ configure	Fri Mar  7 09:28:25 2008
-@@ -726,10 +726,10 @@ MAKEFLAGS=
+$OpenBSD: patch-configure,v 1.3 2009/07/13 08:14:28 ajacoutot Exp $
+--- configure.orig	Thu Jun 25 22:02:20 2009
++++ configure	Thu Jul  2 14:23:32 2009
+@@ -743,10 +743,10 @@ MAKEFLAGS=
  SHELL=${CONFIG_SHELL-/bin/sh}
  
  # Identity of this package.
 -PACKAGE_NAME='HP Linux Imaging and Printing'
-+PACKAGE_NAME='HP Linux (Unix) Imaging and Printing'
++PACKAGE_NAME='HP Linux (& Unix) Imaging and Printing'
  PACKAGE_TARNAME='hplip'
- PACKAGE_VERSION='2.7.12'
--PACKAGE_STRING='HP Linux Imaging and Printing 2.7.12'
-+PACKAGE_STRING='HP Linux (Unix) Imaging and Printing 2.7.12'
- PACKAGE_BUGREPORT='2.7.12.10'
+ PACKAGE_VERSION='3.9.6b'
+-PACKAGE_STRING='HP Linux Imaging and Printing 3.9.6b'
++PACKAGE_STRING='HP Linux (& Unix) Imaging and Printing 3.9.6b'
+ PACKAGE_BUGREPORT='3.9.6b.4'
  
  # Factoring default headers for most tests.
-@@ -20513,13 +20513,13 @@ test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m
+@@ -16233,14 +16233,14 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL
+ test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
  
- # Checks for required libraries, sets -lpthread, -lm, -ljpeg, ... for LIBS and HAVE_PTHREAD, ...
  
--{ echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
--echo $ECHO_N "checking for pthread_create in -lpthread... $ECHO_C" >&6; }
-+{ echo "$as_me:$LINENO: checking for pthread_create in -pthread" >&5
-+echo $ECHO_N "checking for pthread_create in -pthread... $ECHO_C" >&6; }
+-# Checks for required libraries, don't set global -lpthread, -lm, -ljpeg, ... here, set in Makefile.
+-{ $as_echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
+-$as_echo_n "checking for pthread_create in -lpthread... " >&6; }
++# Checks for required libraries, don't set global -pthread, -lm, -ljpeg, ... here, set in Makefile.
++{ $as_echo "$as_me:$LINENO: checking for pthread_create in -pthread" >&5
++$as_echo_n "checking for pthread_create in -pthread... " >&6; }
  if test "${ac_cv_lib_pthread_pthread_create+set}" = set; then
-   echo $ECHO_N "(cached) $ECHO_C" >&6
+   $as_echo_n "(cached) " >&6
  else
    ac_check_lib_save_LIBS=$LIBS
 -LIBS="-lpthread  $LIBS"
@@ -31,25 +33,14 @@ $OpenBSD: patch-configure,v 1.2 2008/03/15 10:18:30 ajacoutot Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -20579,7 +20579,7 @@ if test $ac_cv_lib_pthread_pthread_create = yes; then
- #define HAVE_LIBPTHREAD 1
- _ACEOF
- 
--  LIBS="-lpthread $LIBS"
-+  LIBS="-pthread $LIBS"
- 
- fi
- 
-@@ -20732,82 +20732,6 @@ else
- echo "$as_me: error: \"cannot find libjpeg support\"" >&2;}
+@@ -16453,81 +16453,7 @@ $as_echo "$as_me: error: \"cannot find libjpeg support
     { (exit 102); exit 102; }; }
  fi
--
--
--{ echo "$as_me:$LINENO: checking for dlopen in -ldl" >&5
--echo $ECHO_N "checking for dlopen in -ldl... $ECHO_C" >&6; }
+ 
+-{ $as_echo "$as_me:$LINENO: checking for dlopen in -ldl" >&5
+-$as_echo_n "checking for dlopen in -ldl... " >&6; }
 -if test "${ac_cv_lib_dl_dlopen+set}" = set; then
--  echo $ECHO_N "(cached) $ECHO_C" >&6
+-  $as_echo_n "(cached) " >&6
 -else
 -  ac_check_lib_save_LIBS=$LIBS
 -LIBS="-ldl  $LIBS"
@@ -81,45 +72,46 @@ $OpenBSD: patch-configure,v 1.2 2008/03/15 10:18:30 ajacoutot Exp $
 -  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
 -  *) ac_try_echo=$ac_try;;
 -esac
--eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+-eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+-$as_echo "$ac_try_echo") >&5
 -  (eval "$ac_link") 2>conftest.er1
 -  ac_status=$?
 -  grep -v '^ *+' conftest.er1 >conftest.err
 -  rm -f conftest.er1
 -  cat conftest.err >&5
--  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
 -  (exit $ac_status); } && {
 -	 test -z "$ac_c_werror_flag" ||
 -	 test ! -s conftest.err
--       } && test -s conftest$ac_exeext &&
--       $as_test_x conftest$ac_exeext; then
--  ac_cv_lib_dl_dlopen=yes
+-       } && test -s conftest$ac_exeext && {
+-	 test "$cross_compiling" = yes ||
+-	 $as_test_x conftest$ac_exeext
+-       }; then
+   ac_cv_lib_dl_dlopen=yes
 -else
--  echo "$as_me: failed program was:" >&5
+-  $as_echo "$as_me: failed program was:" >&5
 -sed 's/^/| /' conftest.$ac_ext >&5
 -
 -	ac_cv_lib_dl_dlopen=no
 -fi
 -
+-rm -rf conftest.dSYM
 -rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
 -      conftest$ac_exeext conftest.$ac_ext
 -LIBS=$ac_check_lib_save_LIBS
 -fi
--{ echo "$as_me:$LINENO: result: $ac_cv_lib_dl_dlopen" >&5
--echo "${ECHO_T}$ac_cv_lib_dl_dlopen" >&6; }
--if test $ac_cv_lib_dl_dlopen = yes; then
--  cat >>confdefs.h <<_ACEOF
+-{ $as_echo "$as_me:$LINENO: result: $ac_cv_lib_dl_dlopen" >&5
+-$as_echo "$ac_cv_lib_dl_dlopen" >&6; }
+-if test "x$ac_cv_lib_dl_dlopen" = x""yes; then
+-  LIBS="$LIBS" cat >>confdefs.h <<\_ACEOF
 -#define HAVE_LIBDL 1
 -_ACEOF
 -
--  LIBS="-ldl $LIBS"
--
 -else
--  { { echo "$as_me:$LINENO: error: \"cannot find libdl support\"" >&5
--echo "$as_me: error: \"cannot find libdl support\"" >&2;}
+-  { { $as_echo "$as_me:$LINENO: error: \"cannot find libdl support\"" >&5
+-$as_echo "$as_me: error: \"cannot find libdl support\"" >&2;}
 -   { (exit 104); exit 104; }; }
 -fi
--
+ 
  
  # Checks for required header files.
- { echo "$as_me:$LINENO: checking for ANSI C header files" >&5
