Updated to hplip-3.9.8 Fix SHARED_LIBS. sane-hpaio is a loadable module. Move some PPD files from -hpijs to -hpcups.

diff --git a/print/hplip/patches/patch-configure b/print/hplip/patches/patch-configure
--- a/print/hplip/patches/patch-configure
+++ b/print/hplip/patches/patch-configure
@@ -1,6 +1,6 @@
-$OpenBSD: patch-configure,v 1.3 2009/07/13 08:14:28 ajacoutot Exp $
---- configure.orig	Thu Jun 25 22:02:20 2009
-+++ configure	Thu Jul  2 14:23:32 2009
+$OpenBSD: patch-configure,v 1.4 2009/08/20 08:07:48 ajacoutot Exp $
+--- configure.orig	Thu Aug 20 09:22:03 2009
++++ configure	Thu Aug 20 09:23:14 2009
 @@ -743,10 +743,10 @@ MAKEFLAGS=
  SHELL=${CONFIG_SHELL-/bin/sh}
  
@@ -8,13 +8,13 @@ $OpenBSD: patch-configure,v 1.3 2009/07/13 08:14:28 ajacoutot Exp $
 -PACKAGE_NAME='HP Linux Imaging and Printing'
 +PACKAGE_NAME='HP Linux (& Unix) Imaging and Printing'
  PACKAGE_TARNAME='hplip'
- PACKAGE_VERSION='3.9.6b'
--PACKAGE_STRING='HP Linux Imaging and Printing 3.9.6b'
-+PACKAGE_STRING='HP Linux (& Unix) Imaging and Printing 3.9.6b'
- PACKAGE_BUGREPORT='3.9.6b.4'
+ PACKAGE_VERSION='3.9.8'
+-PACKAGE_STRING='HP Linux Imaging and Printing 3.9.8'
++PACKAGE_STRING='HP Linux (& Unix) Imaging and Printing 3.9.8'
+ PACKAGE_BUGREPORT='3.9.8.36'
  
  # Factoring default headers for most tests.
-@@ -16233,14 +16233,14 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL
+@@ -16242,14 +16242,14 @@ test -z "$INSTALL_SCRIPT" && INSTALL_SCRIPT='${INSTALL
  test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
  
  
@@ -33,10 +33,12 @@ $OpenBSD: patch-configure,v 1.3 2009/07/13 08:14:28 ajacoutot Exp $
  cat >conftest.$ac_ext <<_ACEOF
  /* confdefs.h.  */
  _ACEOF
-@@ -16453,81 +16453,7 @@ $as_echo "$as_me: error: \"cannot find libjpeg support
+@@ -16460,82 +16460,6 @@ else
+   { { $as_echo "$as_me:$LINENO: error: \"cannot find libjpeg support\"" >&5
+ $as_echo "$as_me: error: \"cannot find libjpeg support\"" >&2;}
     { (exit 102); exit 102; }; }
- fi
- 
+-fi
+-
 -{ $as_echo "$as_me:$LINENO: checking for dlopen in -ldl" >&5
 -$as_echo_n "checking for dlopen in -ldl... " >&6; }
 -if test "${ac_cv_lib_dl_dlopen+set}" = set; then
@@ -87,7 +89,7 @@ $OpenBSD: patch-configure,v 1.3 2009/07/13 08:14:28 ajacoutot Exp $
 -	 test "$cross_compiling" = yes ||
 -	 $as_test_x conftest$ac_exeext
 -       }; then
-   ac_cv_lib_dl_dlopen=yes
+-  ac_cv_lib_dl_dlopen=yes
 -else
 -  $as_echo "$as_me: failed program was:" >&5
 -sed 's/^/| /' conftest.$ac_ext >&5
@@ -111,7 +113,6 @@ $OpenBSD: patch-configure,v 1.3 2009/07/13 08:14:28 ajacoutot Exp $
 -  { { $as_echo "$as_me:$LINENO: error: \"cannot find libdl support\"" >&5
 -$as_echo "$as_me: error: \"cannot find libdl support\"" >&2;}
 -   { (exit 104); exit 104; }; }
--fi
+ fi
  
  
- # Checks for required header files.
