Compile with -pthread and don't use --as-needed.
ok jasper@

diff --git a/x11/e17/eet/patches/patch-configure b/x11/e17/eet/patches/patch-configure
--- a/x11/e17/eet/patches/patch-configure
+++ b/x11/e17/eet/patches/patch-configure
@@ -1,9 +1,10 @@
-$OpenBSD: patch-configure,v 1.1 2010/01/11 15:02:35 jasper Exp $
+$OpenBSD: patch-configure,v 1.2 2010/01/12 08:41:53 ajacoutot Exp $
 
 Don't check for OpenSSL with pkg-config(1).
+Don't use --as-needed to force registration of -pthread
 
---- configure.orig	Wed Jul 22 11:53:01 2009
-+++ configure	Wed Jul 22 11:53:01 2009
+--- configure.orig	Mon Jun 15 07:35:46 2009
++++ configure	Mon Jan 11 21:51:01 2010
 @@ -13031,7 +13031,7 @@ cat >>confdefs.h <<\_ACEOF
  #define HAVE_OPENSSL 1
  _ACEOF
@@ -13,3 +14,62 @@ Don't check for OpenSSL with pkg-config(1).
  
  fi
  fi
+@@ -14486,58 +14486,6 @@ case "$host_os" in
+       ;;
+ esac
+ 
+-
+-# use --as-needed if supported
+-
+-LDFLAGS_SAVE=${LDFLAGS}
+-LDFLAGS="${LDFLAGS} -Wl,--as-needed"
+-
+-cat >conftest.$ac_ext <<_ACEOF
+-/* confdefs.h.  */
+-_ACEOF
+-cat confdefs.h >>conftest.$ac_ext
+-cat >>conftest.$ac_ext <<_ACEOF
+-/* end confdefs.h.  */
+-
+-int
+-main ()
+-{
+-
+-  ;
+-  return 0;
+-}
+-_ACEOF
+-rm -f conftest.$ac_objext conftest$ac_exeext
+-if { (ac_try="$ac_link"
+-case "(($ac_try" in
+-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+-  *) ac_try_echo=$ac_try;;
+-esac
+-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+-  (eval "$ac_link") 2>conftest.er1
+-  ac_status=$?
+-  grep -v '^ *+' conftest.er1 >conftest.err
+-  rm -f conftest.er1
+-  cat conftest.err >&5
+-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+-  (exit $ac_status); } && {
+-	 test -z "$ac_c_werror_flag" ||
+-	 test ! -s conftest.err
+-       } && test -s conftest$ac_exeext &&
+-       $as_test_x conftest$ac_exeext; then
+-  ld_as_needed="-Wl,--as-needed"
+-else
+-  echo "$as_me: failed program was:" >&5
+-sed 's/^/| /' conftest.$ac_ext >&5
+-
+-	ld_as_needed=""
+-
+-fi
+-
+-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+-      conftest$ac_exeext conftest.$ac_ext
+-
+-LDFLAGS=${LDFLAGS_SAVE}
+ 
+ 
+ 
