Tweak build, so that it won't try to pull in audiofile, and so that it pulls the right gsm build, thus avoiding rebuild.

diff --git a/mbone/vat/patches/patch-configure b/mbone/vat/patches/patch-configure
--- a/mbone/vat/patches/patch-configure
+++ b/mbone/vat/patches/patch-configure
@@ -1,6 +1,6 @@
-$OpenBSD: patch-configure,v 1.2 2001/07/30 15:33:22 espie Exp $
+$OpenBSD: patch-configure,v 1.3 2001/07/30 15:47:16 espie Exp $
 --- configure.orig	Thu May 16 10:03:58 1996
-+++ configure	Mon Jul 30 17:25:38 2001
++++ configure	Mon Jul 30 15:38:05 2001
 @@ -1533,6 +1533,7 @@ rm -f conftest*
  			$x_includes/tk \
  			$x_includes \
@@ -57,3 +57,59 @@ $OpenBSD: patch-configure,v 1.2 2001/07/30 15:33:22 espie Exp $
  		/usr/contrib/lib/tk4.1 \
  		/usr/lib/tk4.1 \
  		/usr/lib/tk/tk4.1 \
+@@ -1861,10 +1863,12 @@ if test "$d" != "" ; then
+ 		echo "'$d' is not a directory"
+ 		exit 1
+ 	fi
+-	V_LIB_GSM=$d/lib/libgsm.a
+-	if test ! -r $V_LIB_GSM ; then
+-		echo "can't find libgsm.a in $d/lib"
+-		exit 1
++	if test x"$V_LIB_GSM" == x""; then
++	    V_LIB_GSM=$d/lib/libgsm.a
++	    if test ! -r $V_LIB_GSM ; then
++		    echo "can't find libgsm.a in $d/lib"
++		    exit 1
++	    fi
+ 	fi
+ 	V_INCLUDE_GSM=-I$d/inc
+ 	if test ! -r $d/inc/private.h ; then
+@@ -1905,21 +1909,23 @@ else
+ fi
+ 
+ if test "$d" != "" ; then
+-	if test ! -d $d ; then 
+-		echo "'$d' is not a directory"
+-		exit 1
+-	fi
+-	if test ! -r $d/AF/lib/AF/libAF.a ; then
+-		echo "can't find libAF.a in $d/AF/lib/AF"
+-		exit 1
+-	fi
+-	if test ! -r $d/AF/lib/AF/AFlib.h ; then
+-		echo "can't find AFlib.h in $d/AF/lib/AF"
+-		exit 1
+-	fi
+-	V_LIB="$V_LIB $d/AF/lib/AF/libAF.a"
+-	V_INCLUDE="$V_INCLUDE -I$d/AF/lib -I$d/AF"
+-	V_OBJ_AUDIO="$V_OBJ_AUDIO audio-af.o"
++	if test "$d" != "no"; then
++	    if test ! -d $d ; then 
++		    echo "'$d' is not a directory"
++		    exit 1
++	    fi
++	    if test ! -r $d/AF/lib/AF/libAF.a ; then
++		    echo "can't find libAF.a in $d/AF/lib/AF"
++		    exit 1
++	    fi
++	    if test ! -r $d/AF/lib/AF/AFlib.h ; then
++		    echo "can't find AFlib.h in $d/AF/lib/AF"
++		    exit 1
++	    fi
++	    V_LIB="$V_LIB $d/AF/lib/AF/libAF.a"
++	    V_INCLUDE="$V_INCLUDE -I$d/AF/lib -I$d/AF"
++	    V_OBJ_AUDIO="$V_OBJ_AUDIO audio-af.o"
++   	fi
+ else
+ 	echo "checking for AudioFile"
+ 	places="../AudioFile-3.1 \
