Unbreak after recent grilo update. Enable the zeitgeist plugin. @comment -> post-install rm

diff --git a/audio/rhythmbox/patches/patch-configure b/audio/rhythmbox/patches/patch-configure
--- a/audio/rhythmbox/patches/patch-configure
+++ b/audio/rhythmbox/patches/patch-configure
@@ -1,10 +1,24 @@
-$OpenBSD: patch-configure,v 1.14 2012/06/03 11:12:31 ajacoutot Exp $
+$OpenBSD: patch-configure,v 1.15 2012/09/29 12:20:14 ajacoutot Exp $
+
+From 86eb47f705b2f0e6e8ba8d90073c961d47dbfb95 Mon Sep 17 00:00:00 2001
+From: Jasper Lievisse Adriaanse <jasper@humppa.nl>
+Date: Fri, 17 Aug 2012 13:28:05 +0000
+Subject: grilo: Port to the grilo 0.2 API
 
 audiocd plugin requires cdda support in gvfs which we do not provide as
 this would require HAL or gudev.
 
 --- configure.orig	Sun Jun  3 11:07:09 2012
-+++ configure	Sun Jun  3 12:01:41 2012
++++ configure	Sat Sep 29 14:06:22 2012
+@@ -15085,7 +15085,7 @@ LIBSOUP_REQS=2.26.0
+ GUDEV_REQS=143
+ LIBMTP_REQS=0.3.0
+ LIBPEAS_REQS=0.7.3
+-GRILO_REQS=0.1.17
++GRILO_REQS=0.2.0
+ LIBXML2_REQS=2.7.8
+ 
+ LIBNOTIFY_REQS=0.7.0
 @@ -16851,99 +16851,6 @@ fi
  
  
@@ -105,3 +119,47 @@ this would require HAL or gudev.
  have_sj_metadata_getter=no
  # Check whether --enable-musicbrainz was given.
  if test "${enable_musicbrainz+set}" = set; then :
+@@ -20437,12 +20344,12 @@ if test -n "$GRILO_CFLAGS"; then
+     pkg_cv_GRILO_CFLAGS="$GRILO_CFLAGS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"grilo-0.1 >= \$GRILO_REQS\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "grilo-0.1 >= $GRILO_REQS") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"grilo-0.2 >= \$GRILO_REQS\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "grilo-0.2 >= $GRILO_REQS") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_GRILO_CFLAGS=`$PKG_CONFIG --cflags "grilo-0.1 >= $GRILO_REQS" 2>/dev/null`
++  pkg_cv_GRILO_CFLAGS=`$PKG_CONFIG --cflags "grilo-0.2 >= $GRILO_REQS" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -20453,12 +20360,12 @@ if test -n "$GRILO_LIBS"; then
+     pkg_cv_GRILO_LIBS="$GRILO_LIBS"
+  elif test -n "$PKG_CONFIG"; then
+     if test -n "$PKG_CONFIG" && \
+-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"grilo-0.1 >= \$GRILO_REQS\""; } >&5
+-  ($PKG_CONFIG --exists --print-errors "grilo-0.1 >= $GRILO_REQS") 2>&5
++    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"grilo-0.2 >= \$GRILO_REQS\""; } >&5
++  ($PKG_CONFIG --exists --print-errors "grilo-0.2 >= $GRILO_REQS") 2>&5
+   ac_status=$?
+   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   test $ac_status = 0; }; then
+-  pkg_cv_GRILO_LIBS=`$PKG_CONFIG --libs "grilo-0.1 >= $GRILO_REQS" 2>/dev/null`
++  pkg_cv_GRILO_LIBS=`$PKG_CONFIG --libs "grilo-0.2 >= $GRILO_REQS" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -20478,9 +20385,9 @@ else
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        GRILO_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "grilo-0.1 >= $GRILO_REQS" 2>&1`
++	        GRILO_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "grilo-0.2 >= $GRILO_REQS" 2>&1`
+         else
+-	        GRILO_PKG_ERRORS=`$PKG_CONFIG --print-errors "grilo-0.1 >= $GRILO_REQS" 2>&1`
++	        GRILO_PKG_ERRORS=`$PKG_CONFIG --print-errors "grilo-0.2 >= $GRILO_REQS" 2>&1`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$GRILO_PKG_ERRORS" >&5
