Update to 0.25; from Jim Geovedi <jim@corebsd.or.id>.

diff --git a/audio/easytag/patches/patch-configure b/audio/easytag/patches/patch-configure
--- a/audio/easytag/patches/patch-configure
+++ b/audio/easytag/patches/patch-configure
@@ -1,12 +1,30 @@
-$OpenBSD: patch-configure,v 1.1.1.1 2002/08/26 06:01:48 pvalchev Exp $
---- configure.orig	Thu Aug 22 04:37:17 2002
-+++ configure	Thu Aug 22 04:38:36 2002
-@@ -8034,7 +8034,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
+$OpenBSD: patch-configure,v 1.2 2002/11/26 15:52:42 naddy Exp $
+--- configure.orig	Mon Nov 11 17:19:08 2002
++++ configure	Mon Nov 25 14:37:55 2002
+@@ -5486,7 +5486,7 @@ else
+     ;;
+ 
+   openbsd*)
+-    archive_cmds='$LD -Bshareable -o $lib $libobjs $deplibs $linker_flags'
++    archive_cmds='$LD -Bshareable -o $lib $libobjs $deplibs $compiler_flags'
+     hardcode_libdir_flag_spec='-R$libdir'
+     hardcode_direct=yes
+     hardcode_shlibpath_var=no
+@@ -8150,7 +8150,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; }; then
+-  . conftest.flac; echo "${LIBFLAC_MAJOR}.${LIBFLAC_MINOR}.${LIBFLAC_PATCH}"
++  . ./conftest.flac; echo "${LIBFLAC_MAJOR}.${LIBFLAC_MINOR}.${LIBFLAC_PATCH}"
+ else
+   echo "$as_me: program exited with status $ac_status" >&5
+ echo "$as_me: failed program was:" >&5
+@@ -8330,7 +8330,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_l
    ac_status=$?
    echo "$as_me:$LINENO: \$? = $ac_status" >&5
    (exit $ac_status); }; }; then
 -  . conftest.id3; echo "${ID3LIB_MAJOR}.${ID3LIB_MINOR}.${ID3LIB_PATCH}"
-+  $SHELL conftest.id3; echo "${ID3LIB_MAJOR}.${ID3LIB_MINOR}.${ID3LIB_PATCH}"
++  . ./conftest.id3; echo "${ID3LIB_MAJOR}.${ID3LIB_MINOR}.${ID3LIB_PATCH}"
  else
    echo "$as_me: program exited with status $ac_status" >&5
  echo "$as_me: failed program was:" >&5
