Update to 1.2.1.
The 1.2 series includes a host of new features including IPv6 support and
SSL support via OpenSSL instead of mucking about with Mozilla libraries.

For a complete list of the new features, the 1.2 series release notes are
here:
http://developer.ximian.com/projects/evolution/release_notes/1.2.html

while the 1.2.1 release notes are here:
http://developer.ximian.com/projects/evolution/release_notes/1.2.1.html

ok todd@

diff --git a/mail/evolution/Makefile b/mail/evolution/Makefile
--- a/mail/evolution/Makefile
+++ b/mail/evolution/Makefile
@@ -1,9 +1,10 @@
-# $OpenBSD: Makefile,v 1.7 2002/10/18 20:53:01 naddy Exp $
+# $OpenBSD: Makefile,v 1.8 2003/01/03 21:53:07 marcm Exp $
 
 COMMENT=		"integrated email and PIM software for GNOME"
 COMMENT-devguide=	"Evolution Developer's Guide"
 
-VERSION=		1.0.8
+V=			1.2
+VERSION=		${V}.1
 DISTNAME=		evolution-${VERSION}
 FULLPKGNAME-devguide=	evolution-devguide-${VERSION}
 CATEGORIES=    		mail x11
@@ -18,32 +19,33 @@ PERMIT_PACKAGE_FTP=	Yes
 PERMIT_DISTFILES_CDROM=	Yes
 PERMIT_DISTFILES_FTP=	Yes
 
-MASTER_SITES=		${MASTER_SITE_GNOME:=sources/evolution/1.0/}
+MASTER_SITES=		${MASTER_SITE_GNOME:S@$@sources/evolution/${V}/@}
 
 MODULES=		gettext
 
 BUILD_DEPENDS=		:bison-*:devel/bison \
 			:db-3.1.17:databases/db \
-			:scrollkeeper->=0.1.4:textproc/scrollkeeper
-RUN_DEPENDS=		:db-3.1.17:databases/db \
-			:scrollkeeper->=0.1.4:textproc/scrollkeeper
+			:scrollkeeper->=0.3.11:textproc/scrollkeeper
+RUN_DEPENDS=		:scrollkeeper->=0.3.11:textproc/scrollkeeper
 LIB_DEPENDS=		bonobo.2,bonobo-print.2,bonobox.2::x11/gnome/bonobo \
 			bonobo_conf::x11/gnome/bonobo-conf \
 			glade.5,glade-gnome.5::devel/libglade,gnome \
 			gnomecanvaspixbuf.1::graphics/gdk-pixbuf,-gnome \
-			gtkhtml.21::www/gtkhtml
+			gtkhtml-1.1.3.2::www/gtkhtml \
+			soup.5::devel/soup
 
 USE_X11=		Yes
 USE_GMAKE=		Yes
 YACC=			bison
 CONFIGURE_STYLE=	autoconf
-CONFIGURE_ARGS+=	${CONFIGURE_SHARED} \
-			--with-db3=${LOCALBASE} \
-			--with-krb5=/usr \
-			--with-krb4=/usr \
-			--disable-pilot-conduits \
-			--disable-gtk-doc \
-			--disable-nntp
+CONFIGURE_ARGS+=	${CONFIGURE_SHARED}
+CONFIGURE_ARGS+=	--with-db3=${LOCALBASE}
+CONFIGURE_ARGS+=	--with-krb5=/usr
+CONFIGURE_ARGS+=	--with-krb4=/usr
+CONFIGURE_ARGS+=	--enable-ipv6
+CONFIGURE_ARGS+=	--enable-openssl
+CONFIGURE_ARGS+=	--disable-pilot-conduits
+CONFIGURE_ARGS+=	--disable-gtk-doc
 CONFIGURE_ENV=		CPPFLAGS="-I${LOCALBASE}/include" \
 			LDFLAGS="-L${LOCALBASE}/lib"
 
@@ -73,15 +75,19 @@ LIB_DEPENDS=
 
 pre-configure:
 	@if pkg dependencies check evolution-\*; then \
-		echo 1>&2 "+-------------------"; \
-		echo 1>&2 "| Error: you must remove the existing evolution installation"; \
-		echo 1>&2 "| before compiling this version. To fully remove run"; \
-		echo 1>&2 "| these commands as user root"; \
-		echo 1>&2 "|"; \
-		echo 1>&2 "|	  pkg_delete -f `pkg_info -e 'evolution-*'`"; \
-		echo 1>&2 "|"; \
-		echo 1>&2 "+-------------------"; \
-		exit 1; \
+		if pkg dependencies check ${DISTNAME}; then \
+			:; \
+		else \
+			echo 1>&2 "+-------------------"; \
+			echo 1>&2 "| Error: you must remove the existing evolution installation"; \
+			echo 1>&2 "| before compiling this version. To fully remove run"; \
+			echo 1>&2 "| these commands as user root"; \
+			echo 1>&2 "|"; \
+			echo 1>&2 "|	  pkg_delete -f `pkg_info -e 'evolution-*'`"; \
+			echo 1>&2 "|"; \
+			echo 1>&2 "+-------------------"; \
+			exit 1; \
+		fi; \
 	fi
 
 post-patch:
