- add HOMEPAGE - remove FAKE=Yes and license type - fixup INSTALL - add @comment with RCS id to PLIST

diff --git a/shells/bash/pkg/INSTALL b/shells/bash/pkg/INSTALL
--- a/shells/bash/pkg/INSTALL
+++ b/shells/bash/pkg/INSTALL
@@ -1,7 +1,13 @@
 #!/bin/sh
-# $OpenBSD: INSTALL,v 1.1 1999/12/10 15:16:59 brad Exp $
+# $OpenBSD: INSTALL,v 1.2 2000/07/04 21:30:17 brad Exp $
 #
 # Pre/post-installation setup of bash
+
+# exit on errors, use a sane path and install prefix
+#
+set -e
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+PREFIX=${PKG_PREFIX:-/usr/local}
 
 # Function: tell the user what s/he needs to do to use the port just installed
 #
@@ -16,12 +22,6 @@ do_notice()
     echo "+---------------"
     echo
 }
-
-# exit on errors, use a sane path and install prefix
-#
-set -e
-PATH=/bin:/usr/bin:/sbin:/usr/sbin
-PREFIX=${PKG_PREFIX:-/usr/local}
 
 # verify proper execution
 #
@@ -50,4 +50,3 @@ case $2 in
 esac
 
 exit 0
-
